### ISSUE TITLE
Review predicates in new models

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1029]
### Done Looks Like

Issues generated with changes to properties.

**Comment by davidschober** [comment]
Devs will work with fake predicated. Julie will review.

**Comment by jlhardes** [comment]
The developers are moving forward with migration work to Fedora 4 by bringing over some simple data streams at this point and translating those elements into RDF predicates. They are, in fact, making up predicates as they go (you can see the current list of placeholder predicates here: https://github.com/avalonmediasystem/avalon/blob/hydra10-fresh/app/models/avalon/rdf_vocab.rb).

I am going to work with that same list of predicates and make recommendations where ontologies that exist already provide appropriate predicates to use. I’m not going to aim to come up with a predicate for everything because that probably isn’t possible and some of these are for internal Avalon use only (such as transcoding) and likely don't need to be set up for external sharing or use. But there are recommendations already in place for technical metadata and other types of metadata that are covered by some of the fake predicates listed here so there are some changes that can be made that will be helpful for Avalon to implement.

Any new predicates will be added to this list as the developers continue to work so it is the single source for all pretend predicates.

**Comment by jlhardes** [comment]
#1042 - Derivative class predicate review

**Comment by jlhardes** [comment]
#1053 MasterFile class predicate review

**Comment by jlhardes** [comment]
#1069 MediaObject class predicate review

**Comment by davidschober** [comment]
@julesies @jenyoung is this done?

**Comment by jlhardes** [comment]
I sent out a property review for created items on Sept. 29 to the avalon team list. There are a couple of properties that weren't coming through that should be so that is why this story is still open. I can post that review spreadsheet here but it contains links to things on spruce so I wasn't sure if that was ok or not. And I think I'm @jlhardes - @julesies is Julie Rudder.

**Comment by davidschober** [comment]
Sounds good. Is the team OK with spruce links here? (sorry I tagged Julie Rudder)>
