### ISSUE TITLE
Playlist becomes inaccessible if one of the videos under it is permanently deleted.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1100]
Environment:- mallorn.dlib.indiana.edu
                       media.dlib.indiana.edu
                       All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on any browser and login with admin credentials.
2. Navigate to Playlist and access any non-empty playlist.e.g:- Playlist1
3. Pick any video from it, find and locate the video.
4. Delete video permanently. 
5. Navigate back to Playlist and access same playlist again.i.e. Playlist1

Observe error message "Unknown item" is displayed and playlist becomes inaccessible.

Please refer screenshot and URL for video as mentioned below:

https://drive.google.com/drive/u/0/folders/0B-Lv-tiSRqEuMEtlMkYyRkVUYlE

Video name:- Playlist_issue

**Done looks like**

Playlist should be accessible to user even if contents under it may be deleted permanently.

**Comment by anirudhpillai16** [comment]
![unknow_playlist](https://cloud.githubusercontent.com/assets/15963595/17993466/023ee310-6b1e-11e6-9847-0332e1e3ca14.jpg)

**Comment by davidschober** [comment]
Per discussion: it should gracefully skip to the next one. 

We might need a notification for the creator to say that this needs to be edited. This should operate in an analogous manner to how items users do not have permissions for operates.

**Comment by carrickr** [comment]
We need to cover two cases here:

One where the entire media object has been deleted.  User can be told something in the vein of "object with pid (the media object's pid) has been deleted".  The second case would be the media object has not been deleted, but the specific master file used in the playlist has.  So in the second case we can't just tell the user the media object pid has been deleted, because it is still there.  So we need to tell the user it has been modified and specific section they referenced was deleted.

**Comment by joncameron** [comment]
@davidschober and I made the decision to put this fix in 6.0 and not backport for another 5.1.x release.
