### ISSUE TITLE
Lease class predicate review

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1107]
- [ ] begin_time - http://schema.org/startDate (schema:startDate)
- [ ] end_time - http://schema.org/endDate (schema:endDate)

**Comment by mbklein** [comment]
@jlhardes @jenyoung I don't have a problem using EBUCore for the start and end dates, since it has convenient predicates; I just want to make sure we're all clear that leases aren't specific to audio/video/media objects. They're generic access controls on digital objects. Does that fall within the purview of EBUCore?

**Comment by jlhardes** [comment]
The EBUCore properties are associated with an Event class - is that not generic enough? If not, what about something like http://schema.org/startDate and http://schema.org/endDate? Those require ISO 8601 format which I think lines up with our data format and should definitely be generic enough. Is schema.org better for this type of predicate that can be used in many different ways?

**Comment by mbklein** [comment]
Yeah, I think schema.org would be perfect. Just in case someone wants to take our Lease class and repurpose it. :)

**Comment by jlhardes** [comment]
OK, changing the checkbox list and clearing the checkboxes.
