### ISSUE TITLE
Discuss  updating Mediaelement.js

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1202]
### Description
Beginning the discussion of dropping RTMP support, which has been on the Avalon road map for some time.

### The Case for a Modern Mediaelement
https://northwestern.app.box.com/notes/191234905354?s=x0ei2r5zla05ribfrm4xw1kl3n1uzsra
This write-up makes a case for updating the version of mediaelement.js that Avalon has used for a while in favor of a new version that will allow HLS on non-Apple devices and provide MPEG-DASH support, resulting in Flash only being used for older browsers as a fallback.

### Done Looks Like
The discussion is started and first steps are planned out.

**Comment by carrickr** [comment]
Keeping RTMP and Flash currently creates issues with streaming switching in Avalon, namely moving between video and audio (or vice versa) without triggering a page reload.  Even using Ajax to swap out the entire flash container doesn't work properly.  Going from audio to video fails to create an area to play the video in, and the opposite leaves a large black area intended for video.  Some of this may be due to global javascript variables.

Moving over to HTML5 though will make the entire process less painful.

**Comment by davidschober** [comment]
I believe this discussion took place. John and I represented and reworked some IIIF issues for discussion tomorrow. I move to close this issue. We can discuss the work at hand now.

**Comment by joncameron** [comment]
Yes, I'll be closing this issue since the direction has moved toward upgrading to MediaElement 4 and issues have been rewritten to begin this work.
