### ISSUE TITLE
Break out Performance Testing issues

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1203]
## Done
- [ ] Identify possible performance issues with Fedora 4 and how to mitigate these
- [ ] Schedule a swarm session to discuss further and break out into specific work/issues
- [ ] plan made for VM performance testing/ issues written
- [ ] plan for large-scale production load and performance testing/ issues written

**Comment by davidschober** [comment]
We will need issues for each: 

Parent child relationship. 
lookups
problem: We don't have a production. Team should do a two step. Basic performance testing for VM, then plan out a full production load test.

#1299 assign to Julie. Find a collection. 

Subgroup needed.

**Comment by carrickr** [comment]
We need to be sure to test:

- Migrated Collections
- New Collections

Because there may be different tree structures for them (depending on how our migration tool works) which results in difference performance penalties.  So this may inform the need to either fix the migration tool or do some post migration rearrangement.

**Comment by davidschober** [comment]
@carrickr, @mbklein, @cjcolvar, and @mcwhitaker I want to make sure we get started on this next week. I know we planned to swarm on #1330. Do we need two swarms, or can we knock out a plan via comments?

**Comment by mcwhitaker** [comment]
[Fedore 4 Testing.docx](https://github.com/avalonmediasystem/avalon/files/607752/Fedore.4.Testing.docx)

@davidschober @mbklein @carrickr @cjcolvar @joncameron  - This is a discussion starter. Also, I need to understand from the developers if the instance we will use for performance testing is mallorn or spruce (I've seen references to both).

**Comment by mcwhitaker** [comment]
[Fedora 4 Testing - Outline.docx](https://github.com/avalonmediasystem/avalon/files/610093/Fedora.4.Testing.-.Outline.docx)
[Migration to F4 - dependency of testing tasks.xlsx](https://github.com/avalonmediasystem/avalon/files/610092/Migration.to.F4.-.dependency.of.testing.tasks.xlsx)

Updated the Word document with the outline. Adding a spreadsheet with my attempt at determining dependencies. I think a couple of the lines do not mean a real dependency, but a logical way to approach. 

Again, this is to start us from something so adjustments can be made.

**Comment by cjcolvar** [comment]
Maria, that looks fine enough to me with the exception that, as I said at standup, work on the migration may cause code changes in avalon core which would need to happen before regression testing.  Unless we're okay with the migration coming post release which I think  would take more time since we'd potentially have to migrate data in two ways.

**Comment by mcwhitaker** [comment]
[Migration to F4 - dependency of testing tasks - v2.xlsx](https://github.com/avalonmediasystem/avalon/files/619576/Migration.to.F4.-.dependency.of.testing.tasks.-.v2.xlsx)

@cjcolvar @davidschober - I have updated the dependency graph to include the dependency of regression testing on the migration tool work as suggested by Chris. To do that, I had to move things a little, but besides this the only other change is I replaced #1369 with #1417.

**Comment by davidschober** [comment]
Thanks Maria!
