### ISSUE TITLE
[6.0 Specific]:- User is unable to view audio or video in embed view due to missing https in embed code.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1206]
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**
1. Launch URL on any browser.e.g:- Chrome.
2. Access and play any audio or video.
3. Navigate to embed from share.
4. Copy embed code and paste it in editor on (http://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro)
5. Click Run button.

Observe bad request is shown on trying to view in embed mode.
# Note:-
1. If user adds https in front of URL then embed works fine.
2. Issue is not reproducible on mallorn.

**Done looks like**

Embed code should have https in URL to make embed view work.

Please refer attached screenshot for details:-

**Comment by anirudhpillai16** [comment]
![embed_issue](https://cloud.githubusercontent.com/assets/15963595/18960884/39fcaa7c-8639-11e6-8328-ad8413db66c1.jpg)

**Comment by davidschober** [comment]
Discussion:

originally this was trying to match the protocol on the page to avoid a mixed-content error. If we go to https only we'll get mixed content error.  It may be that Spruce isn't working properly. 

- [ ] verify that this happens on Hemlock. @anirudhpillai16

**Comment by bkeese** [comment]
There are more problems with embed that just the embed link, related to the change in the way we use the asset pipeline. I'm working to fix these. PR forthcoming.

**Comment by joncameron** [comment]
Brian reported on 10/20 that this still isn't fixed.

**Comment by cjcolvar** [comment]
Related to id tickets so this is on hold until #1301 and others are resolved.

**Comment by cjcolvar** [comment]
With #1301 merged, this works when I remove the port from the domain in avalon.yml

**Comment by cjcolvar** [comment]
Avalon's embed uses '//' and doesn't specify a protocol to avoid getting mixed content warning in browsers because we don't know what the protocol will be for the parent page where it is being embedded.  Avalon also allows setting the hostname, port, and protocol to use when generating urls.  A problem arrises when one specifies a port which implies a protocol (80 for http/443 for https).  Thus continued use of '//' requires that a default port not be specified in avalon.yml.  Avalon (or Avalon implemented at IU) might assume that the port is specified and we need to watch for this when testing for 6.0 release.

**Comment by davidschober** [comment]
Sounds good @cjcolvar. So we are OK to close. I will write a test issue.

**Comment by anirudhpillai16** [comment]
Embed view is working fine now for both audio and video hence closing this issue. Please refer attached screenshot for details:-

![audio_embed](https://cloud.githubusercontent.com/assets/15963595/20280460/941a6cf0-aa7a-11e6-921c-a22643137171.jpg)
![video_embed](https://cloud.githubusercontent.com/assets/15963595/20280466/96e634fa-aa7a-11e6-8b72-3b8f804b6987.jpg)
