### ISSUE TITLE
Choose collections for Migration validation

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1299]
We would like to have a few collections that could serve as test data for the Migration. We can selectively import into mallorn the fedora data associated with collections that are sufficiently representative. 

This data will be the set for Metadata experts to use to validate the migration.

**Comment by davidschober** [comment]
Note, this is for the final turn of the crank of #1310. First few will be dev driven

**Comment by jlhardes** [comment]
Collections on MCO to use for migration testing:
* AHEYM collection - https://media.dlib.indiana.edu/catalog?_=1480540806125&f%5Bcollection_ssim%5D%5B%5D=AHEYM%3A+The+Archive+of+Historical+and+Ethnographic+Yiddish+Memories
    * 1 video multiple sections
* University Archives - https://media.dlib.indiana.edu/catalog?_=1480540645924&f%5Bcollection_ssim%5D%5B%5D=University+Archives
    * 30 items, 29 video and 1 audio with multiple sections
* JSoM Performances - https://media.dlib.indiana.edu/catalog?_=1480540645924&f%5Bcollection_ssim%5D%5B%5D=JSoM+Performance
    * 11 items, 4 video, 7 audio, multiple sections on both, catalog records imported, related items linked
* History: Modern Theater, 1978-1979 - https://media.dlib.indiana.edu/catalog?_=1480541148998&f%5Bcollection_ssim%5D%5B%5D=History%3A+Modern+Theater%2C+1978-1979
    * 1 item, available to public but collection is collection staff only
    * need to ask if this is good example of complex permissions
* Research Now Sample Media - https://media.dlib.indiana.edu/catalog?_=1480541606848&f%5Bcollection_ssim%5D%5B%5D=Research+Now+Sample+Media
    * 5 items, not all published, specific people in specific roles, not all people listed are with IU anymore
* SP16-BL-MSCH-F326-30329 - https://media.dlib.indiana.edu/catalog?_=1480541743622&f%5Bread_access_virtual_group_ssim%5D%5B%5D=SP16-BL-MSCH-F326-30329
    * 1 item, think this can work for LTI permission check but Jen and I don’t have access to it on MCO to see original permission settings
* Variations Bookmarks - https://media.dlib.indiana.edu/playlists/195
    * Julie’s playlist - has 3 items but can this work for a test migration since they’re all from Variations and Variations is a huge collection? Might also work to check Avalon Group permissions (VariationsMCOUsers) but Julie and Jen don’t have high enough access to see original permissions
* No examples for the following (need permissions or help identifying):
    * Avalon user
    * IP Address or Range
    * permissions with begin and end dates
    * Logged in users
    * Hidden from search results

**Comment by mcwhitaker** [comment]
@jlhardes WRT playlists, is there anything special about your playlist? Would it be acceptable to just create a new playlist with items in the collections you chose? This would be simpler.

**Comment by jlhardes** [comment]
I can create a new playlist with items from the collections that are listed above. I think we would then still need a way to verify Avalon Group permissions since none of those collections have that kind of permission setting on them. I'll update what we'll use for testing and what we still need for testing after I set up a new playlist on MCO.

**Comment by jlhardes** [comment]
The collection list is updated with a new playlist. Also, item numbers in some collections only reflected what was available when not logged in. There are more items in these collections that become available when logged in, a little over 250. Is that total number of items still OK for a test migration?

**Comment by jlhardes** [comment]
Since permissions are not needed for this testing, here is an updated list of collections and a playlist to use for migration testing:

* AHEYM collection - https://media.dlib.indiana.edu/catalog?_=1480540806125&f%5Bcollection_ssim%5D%5B%5D=AHEYM%3A+The+Archive+of+Historical+and+Ethnographic+Yiddish+Memories
    * 1 video multiple sections
* University Archives - https://media.dlib.indiana.edu/catalog?_=1480540645924&f%5Bcollection_ssim%5D%5B%5D=University+Archives
    * 30 items, 29 video and 1 audio with multiple sections, metadata not from catalog records (not logged in)
    * 54 items, 53 video and 1 audio (logged in)
* JSoM Performances - https://media.dlib.indiana.edu/catalog?_=1480540645924&f%5Bcollection_ssim%5D%5B%5D=JSoM+Performance
    * 11 items, 4 video, 7 audio, multiple sections on both, catalog records imported, related items linked (not logged in)
    * 200 items, 43 video, 156 audio (logged in)
    * can bring over first 10 items available when logged in, 1 video and 9 audio
* Migration test - https://media.dlib.indiana.edu/playlists/707
    * Julie’s playlist with items from other collections (all items available when not logged in)

Bringing over the first 10 items from the JSoM collection will give us 65 items total and a playlist using 3 of those items. Does that work?

**Comment by mcwhitaker** [comment]
Thank you, @jlhardes  and @jenyoung. 

For the load test, the playlist will have to be public. @carrickr Can you make the list public when you import it?

**Comment by joncameron** [comment]
This list seems like it'll work great. Thanks @jlhardes and @jenyoung!

**Comment by bkeese** [comment]
I have exported these items in fedora foxml format. They can be downloaded from here: http://www.avalonmediasystem.org/downloads/avalon_export.tar.gz
