### ISSUE TITLE
Testing data integrity in Fedora 4 (not ui)

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1309]
- [ ] verify tree structure for metadata stores has been generated (think this means to check that all data streams have come over)
- [ ] verify that metadata is correct / RDF properties and files

**Comment by davidschober** [comment]
This is comparing Fed 3 data to Fed 4.

**Comment by mcwhitaker** [comment]
We are assuming this is visual check that @jlhardes  and @jenyoung  will do.

**Comment by cjcolvar** [comment]
@jlhardes @jenyoung I thought we already went through this for new items with the spreadsheet of RDF properties and with verifying the migration on mallorn maybe this is done?

**Comment by jlhardes** [comment]
I've done some checking of properties but not against the spreadsheet and I don't think @jenyoung has been able to access mallorn yet at all. I wouldn't call this done yet.

**Comment by cjcolvar** [comment]
@jenyoung should have access as of yesterday morning.

**Comment by jlhardes** [comment]
I've corrected what needs to be checked in my comment. I don't think @jenyoung has access to Fedora on mallorn yet.

**Comment by jlhardes** [comment]
One item (video) and 2 collections reviewed. Still need to review an audio item.

Reviewed against properties listed for each class on #1029 

Item (Boryslav) - https://mallorn.dlib.indiana.edu/media_objects/gm80hv33v (looked at Permalink, MasterFile, Derivative, Encoding, MediaObject properties in #1029)
MediaObject - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/gm/80/hv/33/gm80hv33v 
- properties ok
MasterFile - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/7p/88/cg/54/7p88cg54n 
- missing premis:hasFormatName for file format
- missing ebucore:hasFormat for physical description
- avalon:resolution is still there as a property even though ebucore:width and ebucore:height are in place and are listed as replacing resolution in Encoding class (#1055) 

Both MediaObject and MasterFile have permalink listed but property used is <http://projecthydra.org/ns/relations#hasPermalink> instead of dc:identifier as listed in #1068 

Can’t locate Derivative objects in Fedora

Workflow - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/gm/80/hv/33/gm80hv33v/workflow/fcr:metadata 
- ebucore:hasMimeType located here but no other properties from Encoding class for video (ebucore:encodingLevel, ebucore:height, ebucore:width, ebucore:hasCodec, ebucore:bitRate)

Collection (AHEYM) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/rj/43/04/57/rj430457n (looked at Collection and Lease properties in #1029)
- http://bibframe.org/vocab/heldBy is from BF1.0, not BF2.0 (http://id.loc.gov/ontologies/bibframe/heldBy)
using BF2.0, value needs to be URI
recommendation was to use BF2.0 term, but either way expected value is a URI, not text
- this example has no description so no dcterms:description property makes sense
- avalon properties that are not present
-- avalon:default_read_users
-- avalon:default_read_groups
-- avalon:default_visibility
- no Lease properties

Collection (JSoM Performance) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/25/14/nk/49/2514nk499  (looked at Collection and Lease properties in #1029)
- avalon properties that are not present
-- avalon:default_read_users
-- avalon:default_visibility
- no Lease properties

**Comment by cjcolvar** [comment]
Comments broken out for each object class to follow.

**Comment by cjcolvar** [comment]
MasterFile - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/7p/88/cg/54/7p88cg54n

missing premis:hasFormatName for file format
**Fixed in develop branch**

missing ebucore:hasFormat for physical description
**I couldn't find any master files in MCO which have a physical description so it makes sense that you can't find any.**

avalonCommon:resolution is still there as a property even though ebucore:width and ebucore:height are in place and are listed as replacing resolution in Encoding class (#1055)
**It looks like we have both avalon:resolution as well as the ebucore properties.  Is it important that we don't have the avalon:resolution?**

**Comment by cjcolvar** [comment]
Both MediaObject and MasterFile have permalink listed but property used is http://projecthydra.org/ns/relations#hasPermalink instead of dc:identifier as listed in #1068
**This seems like a bug and I'll write a ticket for this.**

**Comment by cjcolvar** [comment]
Derivative - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/1c/59/de/b8/1c59deb8-42bf-4460-a1b9-192e264d605a (looked at Derivative class on #1029)

missing avalonDerivative:hlsTrackID
**This item doesn't have any hls_track_id in MCO probably due to our use of AMS and ceasing to create a HLS derivative within Matterhorn a while ago.**

ebucore:encodingLevel, ebucore:hasMimeType, ebucore:hasCodec, ebucore:bitRate, avalonEncoding:audioCodec, and avalonEncoding:audioBitRate are here from Encoding class (#1055) but not ebucore:height, ebucore:width
**Looks like a bug I'll create a ticket.**

Same finding for other derivatives:

http://mallorn.dlib.indiana.edu:8984/fedora4/rest/51/bb/64/31/51bb6431-1007-425a-a89f-8f042906c21c
http://mallorn.dlib.indiana.edu:8984/fedora4/rest/ca/95/bd/f6/ca95bdf6-854e-4e7f-b6e0-7619c7915a43

**Comment by cjcolvar** [comment]
Workflow - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/gm/80/hv/33/gm80hv33v/workflow/fcr:metadata

ebucore:hasMimeType located here but no other properties from Encoding class (ebucore:encodingLevel, ebucore:height, ebucore:width, ebucore:hasCodec, ebucore:bitRate, avalonEncoding:audioCodec, avalonEncoding:audioBitRate)
**I'm confused by this one since the workflow is an xml datastream which holds information about the steps in getting to published for a media object and thus shouldn't have any of the encoding class properties.**

**Comment by cjcolvar** [comment]
Collection (AHEYM) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/rj/43/04/57/rj430457n (looked at Collection and Lease properties in #1029)

http://bibframe.org/vocab/heldBy is from BF1.0, not BF2.0 (http://id.loc.gov/ontologies/bibframe/heldBy)
using BF2.0, value needs to be URI
recommendation was to use BF2.0 term, but either way expected value is a URI, not text
**I'll make a ticket for this one.**

this example has no description so no dcterms:description property makes sense
avalon properties that are not present
avalonCollection:default_read_users
avalonCollection:default_read_groups
avalonCollection:default_visibility
**This collection doesn't have any defaults beyond private so it makes sense that none of these are present.  I removed default_visibility as a property that is persisted and instead it is dynamically determined.**

no Lease properties
**I'm confused since collections shouldn't have any lease properties.**

**Comment by cjcolvar** [comment]
Collection (JSoM Performance) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/25/14/nk/49/2514nk499 (looked at Collection and Lease properties in #1029)

avalon properties that are not present
avalonCollection:default_read_users
avalonCollection:default_visibility
no Lease properties
**Same as for the other collection.
I was noticing that not all users who are managers on MCO are managers on mallorn.  This could be because our manager group snapshot is too old or was incomplete.
I also noticed that one manager/editor didn't make it to the collection on mallorn.  I'll make a ticket for this.
The default special access didn't appear to migrate.  I'll create a ticket for this.**

**Comment by cjcolvar** [comment]
Lease migration still needs to be tested.

**Comment by jlhardes** [comment]
I'm not sure how to test Lease migration. Is that information that would be associated with a MediaObject? What other type of object would have this info on Fedora? I haven't encountered those properties yet on anything I've reviewed but the video item I looked at might not have those kind of properties anyway. I noted that I didn't see them on the Collection objects but those objects are the wrong place to look for those properties, for sure.

**Comment by jlhardes** [comment]
Spruce testing:

Video item (Cat Boxing) - https://spruce.dlib.indiana.edu/media_objects/th83kz33c
MediaObject - http://spruce.dlib.indiana.edu:8985/fedora4/rest/th/83/kz/33/th83kz33c
	•	contains dcterms:identifier for permalink with no value (might be because item is not published)
	•	does not contain loc:local for identifier as defined in https://github.com/avalonmediasystem/avalon/issues/1069 but that might be OK
	•	does not contain avalon_publisher but item is not published

MasterFile - http://spruce.dlib.indiana.edu:8985/fedora4/rest/fb/49/48/40/fb4948403
	•	contains ebucore:title with no value
	•	does not contain ebucore:hasFormat for physical description but not sure that property is needed on MasterFile (https://github.com/avalonmediasystem/avalon/issues/1053)
	•	does not contain loc:local for identifier but that might be ok
	•	contains dcterms:identifier for permalink with no value (might be because item is not published)

Derivative - http://spruce.dlib.indiana.edu:8985/fedora4/rest/05/fe/3c/11/05fe3c11-d113-4ca3-9595-d14d1794bc75
	•	does not contain avalon:audioCodec and avalon:audioBitrate but it is a video item so those properties might not be used

Collection (Lease Test) - http://spruce.dlib.indiana.edu:8985/fedora4/rest/vh/53/wv/73/vh53wv730
	•	contains dcterms:description for collection description with no value (collection doesn’t have a description)
	•	does not contain default_read_users, default_read_groups, default_visibility, or default_hidden

Can’t find lease properties - https://github.com/avalonmediasystem/avalon/issues/1107
	•	leases look like they are being applied to all items so they might not actually go with this item

Audio item (Jerry) - https://spruce.dlib.indiana.edu/media_objects/g732d8963
MediaObject - http://spruce.dlib.indiana.edu:8985/fedora4/rest/g7/32/d8/96/g732d8963
	•	does not contain loc:local for identifier but that might be ok
	•	item is published and has avalon_publisher
	•	contains dc:identifier for permalink with no value (item is published)

MasterFile - http://spruce.dlib.indiana.edu:8985/fedora4/rest/qv/33/rw/64/qv33rw64w
	•	contains ebucore:title with no value
	•	no ebucore:hasFormat for physical description but not sure that property is needed on MasterFile
	•	does not contain loc:local for identifier but that might be ok
	•	contains dcterms:identifier for permalink but with no value (item is published)

Derivative - http://spruce.dlib.indiana.edu:8985/fedora4/rest/a6/03/12/76/a6031276-4c66-4555-84b1-8c3704b833f5
	•	properties ok for Derivative class (#1042)
	•	properties ok for Encoding class (#1055)

Collection (Lease Test) - same as video item

Lease - http://spruce.dlib.indiana.edu:8985/fedora4/rest/a6/9e/a3/b8/a69ea3b8-f78b-4786-9ed6-cc140e684edb
	•	properties ok for Lease class (#1107)
