### ISSUE TITLE
Design Interface for second scrubber

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1387]
### Done Looks Like
With team input, Matt designs simple interface to allow toggling of second scrubber show single track view/time.

- [x] Matt does designs
- [ ] Stakeholders gets a hallway preview of mockup -- generally OK. 
- [ ] Dev team writes issues for completion.

**Comment by davidschober** [comment]
possible team @csyversen @cjcolvar and a third developer. 

This will be a 5.x feature ported to 6.x later.  Possibly have a swarm give input to designer (e.g. data available, etc). 

@joncameron to schedule with @gfitzwat

**Comment by gfitzwat** [comment]
![dual-scrubber](https://cloud.githubusercontent.com/assets/7095544/20674282/54c11c70-b556-11e6-9bff-479c71849844.png)

Here are a couple of concepts, feedback is appreciated!

**Comment by davidschober** [comment]
These are great starts. I like the visual cue of the arrow in the first one.

**Comment by mcwhitaker** [comment]
@gfitzwat @davidschober Is the arrow on the first one supposed to be moving as it plays? Or is it only meant to indicate that that is the segment we are zooming into?

I prefer the second one with the segment marked with a surrounding visual element instead of just a color change. I also prefer the fact that the begin/end numbers are white, consistent with the numbers on the top scrubber.

**Comment by gfitzwat** [comment]
@mcwhitaker I was thinking that the arrow would be static indicating the current segment playing.

**Comment by joncameron** [comment]
@gfitzwat I also like the color scheme with the lighter gray in the second one, as well as the larger size of area containing the scrubber. A thought @mcwhitaker and I had was for the + on the magnifying glass symbol to be a - when the second scrubber is opened... toggling between the +/- depending on whether the second scrubber would be displayed.

**Comment by joncameron** [comment]
The playhead/endpoint of the fill in the scrubber will also always be within the highlighted region corresponding to a track:
![scrubber_mockup](https://cloud.githubusercontent.com/assets/1406618/20730678/f9aa3f1a-b654-11e6-9fdb-012a56b8362d.png)

**Comment by gfitzwat** [comment]
![dual-scrubber 2](https://cloud.githubusercontent.com/assets/7095544/20730830/98e747a8-b655-11e6-98ce-46096e2a1b64.png)
Revised concept

**Comment by mcwhitaker** [comment]
@gfitzwat In your revised concept, and the original one, on the top scrubber, what is the bubble surrounding? I see @joncameron 's mock and that makes more sense to me if the bubble is supposed to be highlighting the current track. The 2nd scrubber shows the zoomed in view of that track and if the bubble highlights that track, one will never see white past the bubble unless the whole track has already played.

@csyversen @bkeese @joncameron @davidschober @gfitzwat I don't remember talking about what happens when the track ends. Will the 2nd scrubber automatically switch to the next track? Or will it automatically disappear? Remaining there unchanged will be very confusing, I think.

**Comment by gfitzwat** [comment]
@mcwhitaker  -- Jon's mockup makes sense to me.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober @gfitzwat  - I believe the developers will need feedback from you on the question I posed above - what to do with the 2nd scrubber as the player moves from track to track.

@jwd and I think that the 2nd scrubber should update to refer to the next track and keep in sync with the 1st scrubber.

**Comment by davidschober** [comment]
I agree with that @mcwhitaker. The highlight should jump to the next track and the second scrubber should track with new track.

**Comment by davidschober** [comment]
With that answered I believe this is closed, correct @joncameron?
