### ISSUE TITLE
MARC to MODS Related Item URL Label not coming through correctly

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1398]
Currently a text label provided for 856 URLs on bib import is coming through as \<relatedItem/url@displayLabel\> but Avalon only shows that text as the link if it is \<relatedItem@displayLabel\>. We need to either change the XSL or change where Avalon is reading @displayLabel for Related Item URLs.

MCO has an example item showing a manually entered label for Related Item ("Testing") and the MODS contains the label brought in through bib import ("Program"): https://media.dlib.indiana.edu/media_objects/avalon:5844

This was reported by IU Music Library.

**Comment by davidschober** [comment]
@jlhardes I'm assuming this needs to be fixed in 5.x as well as 6.0 correct?

**Comment by jlhardes** [comment]
Yes, MCO is currently on Avalon 5.1.4 and is showing this problem so this should be fixed for both 5.x and 6.0.

**Comment by joncameron** [comment]
I've broken this into two issues. The issue for 6.x is #1433

**Comment by joncameron** [comment]
To show the error: 

The Catalog Key to import is: 

15551486 

and the title comes through as: 

10th USA International Harp Competition : laureate recital

**Comment by joncameron** [comment]
Latest update from Michelle at the IU Music Library:

"As far as the 856 thing...that originated because of the added “Related Item” field is currently being populated directly in MCO, but we will need it to be populated from an 856 42 field (where the “2” is the critical factor in distinguishing between multiple 856 fields). And, while the field name should remain “Related Item”, the link that displays in the field should have the text that is embedded in the subfield 3 of the 856.
 
While Julie was looking into it, she came across the bug. I think the bug and the new field mapping are interrelated—is the existence of the bug an indication that the field mapping is a go? She had given me a link to look at it (https://media.dlib.indiana.edu/media_objects/avalon:5844), but it was not a test collection for which I had access so I couldn’t see the bug."

She noted that this can wait until

**Comment by joncameron** [comment]
What we're doing in the bibimport needs to change—it should be pulled in as a relatedItem element rather than a location element

**Comment by jlhardes** [comment]
And the provided label should be @displayLabel on <relatedItem> and not on <url>

**Comment by joncameron** [comment]
Julie would prefer we change the bibimport XSL to fix this bug.

**Comment by cjcolvar** [comment]
@davidschober @joncameron Do we really need to backport this now that IU is going to 6 in a month?

**Comment by joncameron** [comment]
@cjcolvar @davidschober I don't think so. I'll close this and have it noted as a 5.x issue in the docs.
