### ISSUE TITLE
Ask Project Hydra maintainers for point releases

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1411]
## Done Looks Like

Ask For Releases of:

- [x] About Page #1426
- [x] LDP projecthydra/ldp#73
- [x] Hydra-Head projecthydra/hydra-head#389
- [x] Fedora-Noid currently using 2.0.0.beta4 but we can probably get this to non beta
- [x] Active-Fedora released: 10.3.0
- [x] active-encode 0.0.03

Update Gemfile to Track Releases for:

- [x] About Page 
- [x] LDP
- [x] Hydra-Head 10.3.3
- [x] Fedora-Noid 2.0.0
- [x] Active-Fedora 10.3.0
- [x] active-encode 0.0.3

**Comment by carrickr** [comment]
Active-Fedora and Active-Encode are done (assuming Travis tests pass).  I am in the process of cutting a Fedora Noid release.

**Comment by carrickr** [comment]
hydra-head will be out as v10.3.3, we will want to track that

**Comment by carrickr** [comment]
noid is done

**Comment by carrickr** [comment]
Hydra head is done

**Comment by carrickr** [comment]
we'll release about-page just by tag for now, I've written a draft for release notes for ldp, release will be discussed on the tech call

**Comment by carrickr** [comment]
hydra-head to 10.3.4 due to finding a bug in its user controls

**Comment by carrickr** [comment]
ldp 0.6.2 is out for use in Chris C's branch

**Comment by carrickr** [comment]
@anirudhpillai16 @davidschober @joncameron 

This needs general Q&A since I'm changing out gems here, so our release regression testing should exercise this.  Only specific area that stands out is uploading an item and ensuring it has a noid minted instead of the ugly Fedora 4 identifier /abc/123/ab/etc...

Also for retro this was totally not a 2 in hindsight, more like a 3 to 5.
