### ISSUE TITLE
out database migration

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1418]
Write tools and/or instructions to migrate database tables. This may include migrating identifiers from old avalon:id pids to newly assigned noids.

**Comment by davidschober** [comment]
FROM SWARM: This assumes that we're not upgrading in place. A user will need to create a new database.  Because we're reassigning IDs we will have to update all of links to them. This does not need to be completed before regression testing. 

Note whoever comes up with a good method, put it in this issue.
