### ISSUE TITLE
Database Migration - SelectedItems

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1421]
### Description
#1418 is the master issue for database migrations and contains the pattern or method to follow when creating each migration.
### Done Looks Like
Tools and/or instructions are written to migrate database tables for **SelectedItems**. This may include migrating identifiers from old avalon:id pids to newly assigned noids.

- [x] add their migration status to the reporting tool
- [x] write a rake task to delete ones that have failed migration
- [x] rename migration report view columns to be "Avalon 5 ID" and "Avalon 6 ID"

**Comment by cjcolvar** [comment]
Dump, load, then migrate document_id  from fedora3 pid to new noid.

**Comment by cjcolvar** [comment]
What should we do if item referenced didn't migrate successfully?  Maybe we should leave the old selected item in place with the fedora3 pid and warn.  This way the migration could be rerun until it succeeds.  If some are still not resolvable then provide a method for removal since they would probably break things if a user tries to go to their selected items when one still has a fedora3 pid.

**Comment by cjcolvar** [comment]
Migrating a selected item should be as simple as:
ActiveFedora::Base.where("identifier_ssim:\"#{fedora3_pid}\"").id
