### ISSUE TITLE
Create New Playlists From Object View Page

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1434]
### Description
As a user, I want to create a new playlist directly from an object page and add an item to the playlist I've newly created. This is so that I don't have to go through the many steps of creating a playlist that take me away from the media I wanted to make a playlist item from.

### Descriptive summary
Users would like the “Add to playlist” feature to allow the creation of a new playlist on the spot instead of only allowing them to choose from existing playlists. Once they create the new playlist, they want to be taken back to the item they want to add to the playlist instead of having to navigate back. We currently allow users to create a playlist on the spot if they don’t have any, but then they have to start over and find the item again (using the back button does not work unless the user is savvy enough to try refreshing the item page).
 
### Expected behavior

When a user clicks "Add to playlist" there should be an optional "OR Create New Playlist" under the list of existing playlists possibly with a text field for adding the playlist title. 

### DONE

- [x] Design created (mockups by a designer if necessary)
- [ ] a link is added and user can create an on the fly playlist and add the selected item to it. 

![screen shot 2016-12-02 at 11 50 35 am](https://cloud.githubusercontent.com/assets/4803230/20844530/dd36e1c0-b885-11e6-9e27-eba11eaecb84.png)

**Comment by davidschober** [comment]
@joncameron let's punch this into 6.2

**Comment by gfitzwat** [comment]
Attaching some concpets of the process...
![1artboard-1](https://user-images.githubusercontent.com/7095544/27200225-fbedaf68-51e6-11e7-96f3-fdb9ed26f59b.png)
![1artboard-2](https://user-images.githubusercontent.com/7095544/27200230-002b0fa8-51e7-11e7-97c1-481ecf0f9de3.png)
![1artboard-3](https://user-images.githubusercontent.com/7095544/27200236-043cd658-51e7-11e7-96b5-caf37da683a6.png)
![1artboard-4](https://user-images.githubusercontent.com/7095544/27200238-065a3ebc-51e7-11e7-99fd-f47b77df134b.png)

**Comment by lealeelu** [comment]
I used a javascript library called select2 in order to make the select dropdown.
![image](https://user-images.githubusercontent.com/5091130/27486221-f01e880c-57fd-11e7-83b2-8342af9fdefa.png)
It offers a field to filter/search through your options.
![image](https://user-images.githubusercontent.com/5091130/27486247-fdbd5a7e-57fd-11e7-8709-402fc0b9e5ae.png)
When you type something into the search box it highlights the search term in each of the options and offers you the option of creating what you're searching for.
![image](https://user-images.githubusercontent.com/5091130/27486325-319a94ec-57fe-11e7-8d61-b4175d9fb6f4.png)
I still need to get the modal to appear when the add new option is selected.

**Comment by joncameron** [comment]
We also need to review this from an accessibility standpoint for users that may be using something like a screen reader.

**Comment by lealeelu** [comment]
the pull request was approved, just need to get it into develop after the 6.1 release.
