### ISSUE TITLE
Publication of an item is failing to re-index

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1441]
This is a theory based on production issues at IU. The story should be to:

- [x] Confirm the theory
- [ ] Fix the code

**Comment by carrickr** [comment]
For POs, what is happening is:

1.  An media object is ingested into Avalon in an unpublished state (via Batch, API, whatever it is method agnostic)
1.  Collection Manager publishes the media object at some future date.  At the time of publication a noid is generated for use as a purl and in the share link for an item (media objects and master files both get noids).
1.  The items should be reindexed so that this noid is included in dc_identifiers_ssim.  However this does not appear to be happening and thus the noid is not resolvable.

We've seen this happen multiple times with regard to IU's variation import.  There are two things to check out.

1. Are media object noids reindexing properly
1. Are master file noids reindexing properly (we are almost certain these are not).

There is a relevant difference between the two because media objects are reindexed on publish, whereas master file reindexing is farmed out to a background task.  So it could be the reindex code works but the background task is failing or it could be bad overall reindexing code on publish.

**Comment by joncameron** [comment]
Carrick reports: Solr query once every hour, or every 40 minutes (which will bring the total within an hour) should suffice.

I will break this out into two issues for 5.x and 6. Fixing this in 5.x is a high priority.

**Comment by joncameron** [comment]
I'm going to close this since it's now broken up into #1449 and #1448
