### ISSUE TITLE
Inheritable Permissions For Collection Items

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1482]
### Description
Collection managers should be able to set permissions on a collection that are inherited by the items contain within it. 

### For What Purpose?
Managing permissions on large collection requires scripting and lots of time. It makes small changes to permissions upon a collection time intensive. Having inheritable permissions defined on a higher level object would make life easier for developers and collection maintainers.

**Comment by carrickr** [comment]
So there are two patterns here, one is to have the item look upstream every time it is accessed (typically one would point to an APO, but we don't use APOs in Avalon...).  However this is expensive and going to make things like loading playlists even more expensive.  Since now every item calls upstream to its collection (since playlist items may be from different collections).

The other option is to give collection managers a button to automatically reapply collection permissions downstream.  So click the button, all the members get the permissions applied, but then may grow stale (or do it whenever the collection changes).  This saves us lookups but the staleness is an issue and the application time as well.  

WebACL may offer better options, but typically I've had better luck with the second approach.  As long as you ensure you have background tasks to apply permissions properly and collection managers understand it takes time to replicate it works well.

**Comment by joncameron** [comment]
Tagging as 7.0 for future reference. This isn't going to make it in 6.x but I'd like an improved permissions model in a future Avalon release.

**Comment by davidschober** [comment]
abandoning. We will handle this with permissions work in 7.
