### ISSUE TITLE
Investigate use of private dropboxes

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1574]
Currently all users share the same dropbox, which does not provide privacy.  Suggestion was to use a samba share instead of sftp.

Deliverable 
- [ ] Ability to decide whether this is feasible;
- [ ] list of pros and cons, if applicable.

In the future, we could try to implement the creation of a new samba box and new upload script when a new Collection is created.

**Comment by MethkupalliVasanth** [comment]
Samba feasibility and the list of pros and cons are as follows.

Feasibility: 
Samba is more preferred if we are using Windows servers. Can be used in several different ways based on the needs.

Pros: 
 1.  Essential technology when using heterogeneous network of Linux or Unix servers.
 2.  Good open source support.
 3.  Remote file updates
 4.  To manage content remotely on Websites,  WebServers running Apache and Linux may choose Samba over FTP.


Cons:

1.  If the entire network is purely Linux, Samba might not be the way to go.
2.  Name mangling issues can occur.
3.  Since Unix and Windows systems implement EOL(End of Line) conventions differently for ASCII text files, transfers between them might not be handled by Samba.

This list is not exhaustive, but a good place to start.

If you want to add a folder that is password protected, it can be done by samba. This can probably be modified to creating a new samba box and upload script when a new Collection is created.


How about using NFS 4.0 instead of Samba share ?  It is fast evolving and proving to be a good competitor for Samba for the following reasons.

1.  Easy installation and setup
2.  Simple configuration for share/s.
3.  Configuration of Security settings and also choice of opting for advanced security features.
4.  Reliable and faster without the overhead of SMB/CIFS protocol.

However, if there is any concrete reason why we would like to use Samba share, it can be further explored if NFS 4.0 can support that.

**Comment by davidschober** [comment]
This feels more like a local setup issue. Closing as stale.
