### ISSUE TITLE
No value for ebucore:filename on binary resources in Fedora4

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1582]
Empty file name properties are in place for all F3 bitstreams that were migrated over. When viewing content that can be downloaded in F4, ebucore:filename property is present but the value is empty. This happens for all bitstreams that are migrated over as files (workflow, descMetadata, and structuralMetadata).

**Comment by davidschober** [comment]
It needs to get changed in two places. One in migration one in Avalon.

**Comment by davidschober** [comment]
This is a migration issue. We will grab it after release.

**Comment by cjcolvar** [comment]
@david.schober @joncameron @jlhardes
Julie and I talked and decided that setting these to <id>_<filename>.<extension> made the most sense so all of the filenames were identifiable (e.g. all workflow docs don’t get named workflow.xml)…
But it looks like this is hard to do since we would have to update the filename once the file was saved in Fedora…
AND active-fedora doesn’t handle updating the filename right now.
So doing this would require putting a PR into active-fedora and updating avalon to use this new version of active-fedora (and dependencies).
Alternatively, we could be okay with plain old <filename>.<extension> which would be easy.
Thoughts?

**Comment by joncameron** [comment]
After talking with Chris I think using static names (e.g. workflow.xml) for all of these properties is the best route to take at the moment. We can make a note to go back and add niceties later (something along the lines of 'NOIDVALUE-workflow.xml' to make it distinguishable once downloaded) but the time involved with make upstream changes probably isn't worth it right now. Looking at @jlhardes for a final call on whether that sounds OK.

**Comment by jlhardes** [comment]
Just spoke with @joncameron and @cjcolvar and we ended up at this: if all .xml files on an object can have the unique identifier added (without the complications listed in @cjcolvar's comment) then it's worth it to have the unique object identifier included in the filename for downloading purposes. If only some of the .xml files for an object can have that unique identifier added to the filename (workflow and structure, for example) and others cannot without complications (descMetadata, for example) then keep them all consistently unhelpful and don't include the unique identifier.

**Comment by cjcolvar** [comment]
I'm going to use static filenames all around since it was giving me trouble when I was working on it yesterday.
