### ISSUE TITLE
AWS Kick-off Meeting

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1677]
### Description
Phuong and MBK need to meet to talk about AWS, Docker, and how to start proceeding with the AWS work.

### Done Looks Like
Key players meet to discuss the work ahead. Issues are created and organized as needed.

**Comment by davidschober** [comment]
@mcwhitaker I'm going to invite David Venckus from NU as well. (as optional)

**Comment by phuongdh** [comment]
Maria's notes

1. June 7th - NU's production date (cutover)
2. Mid May - go-no-go for NU
3. May 7th - architecture defined and all components working as desired
4. Nice to haves vs.
  a. Elastic cache - nice to have, but not required -- Running our own redis is acceptable. Probably just a plug-in.
  b. Cloud search - nice to have, but can cutover in summer as refine. Either a quick win or a huge pain - nothing in between (MK)
  c. Cloudfront is a must - but PD has not been able to make it work with rtmp authorization.
  d. Elastic transcoding -will deliver
  e. RDS straightforward
 
  f. Master files and derivatives stored in S3 and this is already working.
  g. Route53 - a requirement for DNS and our deliverables.
  h. Cloud formation script for Lyrasis
  i. Elastic container service - is what PD runs solr fedora avalon on.
  ii. Elastic container registry - all the custom containers
  iii. Installing ruby and the bundle are the most time consuming
  iv. Figure out a way to do cloud formation for custom avalon versions - more mock-ery way to do it - NU board.
  i. Dropbox: MBK suggests to use S3 but browseEverything does not support s3, but MBK thinks it is easy. Shared storage attached to the tiny (??) EC2 container to provide a gateway to S3 -- ftp files to.
  j. LDAP  - what does lyrasis use? Shibolleth? IU will have an easier time because all we need to do is redirect to CAS.
5. AWS - can Michael have access to our install so the collaboration can occur? NU thinks they will have difficulties with their IT to assign that to Phuong.
