### ISSUE TITLE
Make Hyrax Plugin for Hydra Derivatives Work With FlipFlop

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1829]
### Description

The Hydra Plugin in #1826. Avalon-style derivatives should able to be turned on and off using as a hyrax flip-flop plugin. This would require an administrator to have something that could create derivatives for avalon-style derivatives (e.g. AWS, matterhorn, etc).  

### Done looks like

The plugin can be enabled or disabled by flipping and flopping (state toggle in the application using the flipflop gem)

### Tasks
- [ ] Add plugin to hyrax features
- [ ] Add logic checks for feature state
- [ ] Test

**Comment by davidschober** [comment]
@cjcolvar This needed your input for pointing. Feel free to size and/or discuss.

**Comment by joncameron** [comment]
@cjcolvar Can you describe what the benefits are for having this plugin work with FlipFlop versus just having it active via configuration file(s)?

**Comment by cjcolvar** [comment]
I think just making it visible and giving the ability to turn it off easily without machine access.  I'm also hoping that by declaring it a feature we will be able to use a Hyrax construct instead of doing our own thing which may be beneficial.  For instance, I thought there was interest in Hyrax having features togglable per admin set which seems useful for this feature.  If this were a flipflop feature then maybe we would get that for free if someone else implements it.

**Comment by davidschober** [comment]
@cjcolvar are these still valid or did we go a different direction?

**Comment by cjcolvar** [comment]
@davidschober I think this still makes sense to do.

**Comment by davidschober** [comment]
I believe we wenta  different direction. We will rewrite if necessary.
