### ISSUE TITLE
Define performance parameters for mallorn

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1962]

**Comment by Karthikeya212** [comment]
Please find the performance parameters that were noted down on Mallorn.
[Performance Params on Mallorn.xlsx](https://github.com/avalonmediasystem/avalon/files/1046148/Performance.Params.on.Mallorn.xlsx)

Note: Parameters for Bulk actions are pending to be done after rc2 update on Mallorn

**Comment by mcwhitaker** [comment]
@davidschober @joncameron 

On the document uploaded by @Karthikeya212 we see:

![image](https://cloud.githubusercontent.com/assets/16720883/26702985/79411b78-46f5-11e7-9722-6805edf6729d.png)

Should we find a number for which this works? Say we support these operations on items with up to 70 sections.

**Comment by joncameron** [comment]
@mcwhitaker @davidschober I'd like to shoot for support for deletion of an item that has any number of sections, the length of deletion probably being bound to the number of sections the item has. We have an issue for cleaning up why this happens, https://github.com/avalonmediasystem/avalon/issues/2047, and @phuongdh noted in another referenced ticket that the problems @Karthikeya212 may have run into was due to server error rather than Avalon error and that it would be good to retest.

It would also be good if we can figure out the limit at which it breaks, for future testing but also to note in the Known Issues page of the wiki.

**Comment by Karthikeya212** [comment]
Updated document with parameters related to Bulk operations.
[Performance Params on Mallorn.xlsx](https://github.com/avalonmediasystem/avalon/files/1072170/Performance.Params.on.Mallorn.xlsx)
