### ISSUE TITLE
No Facets When Logged Out

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2054]
Visit media.northwestern.edu logged out, no facets are show.

<img width="1540" alt="screen shot 2017-06-12 at 12 34 23 pm" src="https://user-images.githubusercontent.com/5350060/27044543-e50282c4-4f6b-11e7-8a55-6c1ea12a2afd.png">
<img width="1529" alt="screen shot 2017-06-12 at 12 34 30 pm" src="https://user-images.githubusercontent.com/5350060/27044542-e5011164-4f6b-11e7-8aba-52cd57e06475.png">

**Comment by mcwhitaker** [comment]
@carrickr You have probably already figured out why this is since the ticket is closed, but in order to document one explanation for this behavior if someone runs across the same issue (we did here last week and for a moment I was puzzled), I will add one here.

The facets shown are those that include references to items you have access to. When you sign out, if there are no public items, the facets are empty; empty facets are not displayed.
