### ISSUE TITLE
Successful login sometimes redirects to unexpected pages

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2109]
I'm not sure if I can reproduce this but I signed out in one tab while another was playing audio which had already played through from one section to another.  After closing both tabs and going to log back in, Avalon redirected me, but it was an authorize.txt used for streaming authorization.  I'm not really sure how or why this happened.  This was on neon.

**Comment by joncameron** [comment]
@Karthikeya212 can you try to reproduce? I didn't have any success.

**Comment by Karthikeya212** [comment]
I think I had some success, try the below steps in sequence.

1. Open two tabs of avalon and login in both tabs.
2. Start playing an item in tab-1.
3. Go to tab-2 and sign-out of system, but don't close it.
4. Now go to tab-1 and reload the page, user will be navigated to sign-in page. Sign-in with same credentials.
5. Now go to tab-2 (do not reload this page) and click on sign-in, user will be redirected (in my case I was redirected to a poster/thumbnail of the video that I was playing in tab-1 earlier).
6. The only way to login to avalon in this tab is to click on browser back button and refresh the page as clicking on sign-in doesn't navigate to sign-in page.

This redirection might be different depending on the media element type (Audio, Video, Item with both audio & video) that we play in tab-1.

**Comment by Karthikeya212** [comment]
I think this issue is observed even on Embed page yesterday. Embed two items of same server on the embed page, signing in to first item will start playing it, but the second item will still be asking for sign-in. Once we click sign-in on second item it did redirect to the poster of the first video that was playing, but never to sign-in page.

@phuong fixed this on that embed page. Now it is opening a pop-up like for a fraction of second (can't notice if it again opened poster or correctly navigated to sign-in page) and closes it and starts playing the item.

**Comment by joncameron** [comment]
Another edge case bug that only happens when doing a lot of multiple sessions.
