### ISSUE TITLE
Review Test Script for Testing Streaming

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2139]
### Description
We have (or should have) a testing script for human testing of streaming media within the context of the media player. Common actions like seeking, seek during pause, etc. should be in this script.

### Done Looks Like
Test script is reviewed and updated as needed.

### Test Script Location
https://docs.google.com/spreadsheets/d/1KPaYP-Lk_PQOX_ayWXllLGIJd9UUjQRX5DafhjdzT7U/edit#gid=1730858809

**Comment by Karthikeya212** [comment]
@davidschober could you please upload the link to this script

**Comment by davidschober** [comment]
@joncameron did you get a chance to look over what's there?

**Comment by joncameron** [comment]
@davidschober Not yet, so I'm kicking this back to _in progress_. Looks like it might have gotten accidentally moved.

**Comment by jlhardes** [comment]
That was me that moved it - we thought @Karthikeya212 was the only one working on it and he was done and it only needed reviewing. Sorry about that!

**Comment by joncameron** [comment]
https://docs.google.com/spreadsheets/d/1KPaYP-Lk_PQOX_ayWXllLGIJd9UUjQRX5DafhjdzT7U/edit#gid=1730858809, #9 and #11

**Comment by cjcolvar** [comment]
#10 is important too

If I were writing this fresh, I'd maybe do:
1. Load item view page
1. Check poster (if video)
1. Click play and verify playback (audio/video, scrubber advancing, and time elapsing)
1. Test play/pause with both control and overlay button
1. Test volume adjustment and click to mute/unmute
1. Test click to fullscreen and click/Escape key to get out of fullscreen
1. Click on scrubber to jump to new playback position and verify everything updating correctly (audio/video, scrubber, structure highlighting, time elapsed, current track highlighting)
1. Repeat last step buy click on structure node to change position
1. Repeat using lil scrub
1. Repeat in full screen
1. Repeat last 4 tests with the player paused instead of playing
1. Click on structure node of another section while playing and ensure player changes and updates appropriately
1. Repeat with the player paused
1. Test playthrough by seeking to the end of a section and letting play into next section
1. Change quality while playing and verify quality changed
1. Repeat last step with player paused (play in order to test quality changed)
1. Test accessibility tab navigation both forwards and backwards including in and out of player
1. Test keyboard activation (space/enter) of focused player controls
1. Test thumbnail grabber tool
1. Test add to playlist tool

There is probably something else I forgot but I think that covers most player things.

**Comment by mcwhitaker** [comment]
@joncameron I don't have access to the document. Could you please go over permissions and grant access to everyone on the team?

**Comment by joncameron** [comment]
@mcwhitaker I've moved the test script to the Avalon_General folder in Box for ease of access and editing: https://iu.app.box.com/file/199625855775. I've also created #2163 for making some minor updates based on Chris' suggestions.
