### ISSUE TITLE
Create a query param to switch between ME4 and ME2

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2174]
In order to make it easier to test ME we should have a swappable query parameter. That will allow us to merge ME 4 into dev and test on spruce

Done:

- create a query string to swap player
- merge into dev and deploy to spruce

**Comment by davidschober** [comment]
work to represent on #2134

**Comment by adamjarling** [comment]
@bkeese @cjcolvar For some reason on this branch, the AJAX request for a new section media item is not returning the same data as my previous MEJS4 branch.  So clicking on section links and changing a player in the same browser window w/o a refresh is not working since it's missing source file data.   I might need some eyes tomorrow to help me diagnose if possible.
