### ISSUE TITLE
Decide if we need ME2 to be configurable

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2278]
## Description

If people are nervous about the upgrade to MediaElement 4, do we need to have a configurable ME2 available via query parameter or some other switch to be flipped? This would mean we would have to support it. The other option is give people a clear path to **not** upgrade. 

We are kicking off an issue to test RTMP alone so anyone who had only RTMP derivatives would be OK.

### Done Looks Like
- The flag currently used to flip the player to ME4 is changed to be ME2- ME4 is the new default.

**Comment by joncameron** [comment]
We're keeping it because it's easier to swap a flag because it's easier than gutting the ME2 code. It's easier on us, not because we're giving people an out. The flag could be used for testing and debugging, but it will not be something that will be officially supported.
<flash>DON'T USE IN PRODUCTION</flash>

**Comment by davidschober** [comment]
abandoned form #2279
