### ISSUE TITLE
Copy Button Not Working or Displaying for Viewers of Playlists with "Share by link" Permissions

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2333]
### Description
When a playlist is set to "Share by link" for its permissions, the Copy button that usually appears doesn't show up for anyone except the playlist owner.

### Done Looks Like
For a viewer of a playlist that is "Share by link", the copy button should appear as it does when viewing a public playlist.

**Comment by Karthikeya212** [comment]
Failing when tried to copy the playlist on spruce

![image](https://user-images.githubusercontent.com/25850972/31020906-3afff472-a502-11e7-816c-06bde46e59eb.png)

**Comment by bkeese** [comment]
@lealeelu ^^

**Comment by bkeese** [comment]
@Karthikeya212 I can't duplicate the error. If you can, please provide more info.

**Comment by mcwhitaker** [comment]
@lealeelu could your PR have fixed this?
https://github.com/avalonmediasystem/avalon/pull/2246

**Comment by bkeese** [comment]
#2246 was merged back on August 25, long before this testing was done.

**Comment by mcwhitaker** [comment]
I skipped the whole month of September when counting the days! Ooops...

**Comment by bkeese** [comment]
@Karthikeya212 just showed me the test he's doing and it's more complicated than I imagined. It is broken when a non-admin user is looking at a playlist via an LTI share link.

**Comment by bkeese** [comment]
The ajax call to playlists#duplicate is failing to authorize in this case. The error message is displaying because the controller is responding not with a json error message, but rather with the avalon homepage (plus flash message about not being authorized to perform the duplicate). I think we need to rework how the authorization is happening in the duplicate function. Probably just remove :duplicate from the load_and_authorize_resource callback and add it to the load_resource callback. Then manually do the authorization in the duplicate method and return a json error message there if it fails.
