### ISSUE TITLE
After saving the Manage Files page without uploading any files, later it is not detecting the files when trying to upload

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2387]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: After saving the Manage Files page without uploading any files, later it is not detecting the files when trying to upload.

### Steps to reproduce
1. Click on "Create Item" to start creating an item.
2. It open the Manage Files page, do not upload any file and click on save and continue
3. It navigates to Resource description page.
4. Go back to Manage Files page and try to upload any file, it is returning "MediaObject invalid" error.
![mediaobject_invalid](https://user-images.githubusercontent.com/25850972/31560671-36bad8b0-b023-11e7-8903-f11be380198a.PNG)

**Comment by cjcolvar** [comment]
This is the expected behavior now: Title and Publication Date (the required fields) and other metadata validations are skipped until you reach the Resource Description step then they apply even if you navigate back to the manage files step.   This was to deal with https://github.com/avalonmediasystem/avalon/issues/2045.  At that time we did talk about the UX of entering data but then navigating away before saving and I mentioned this case in my PR (see #2 in https://github.com/avalonmediasystem/avalon/pull/2107#issuecomment-316811225).  If others think this issue needs to be revisited please say so otherwise I move to close this.

**Comment by joncameron** [comment]
I'm going to move to close this too, although I'd like to have this in documentation somewhere for reference, and in case users bump into this edge case.

**Comment by mcwhitaker** [comment]
@joncameron Is this in documentation somewhere? Do we need a ticket to add it to documentation?

**Comment by joncameron** [comment]
@mcwhitaker I've written a new story for it, #2460.
