### ISSUE TITLE
Avalon Website: Project History is out of date

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2414]
We should update the information about Variations having been retired at IU and other institutions, and also add information about the latest IMLS grant.

![image](https://user-images.githubusercontent.com/16720883/31905947-ba370ac4-b7fd-11e7-9cae-1ee73ea1962a.png)

**Comment by mschnaars** [comment]
How's this? I could use a proofread:

"Avalon is a follow-up product to the Variations Digital Music Library, an open-source system developed at Indiana University and employed since 1996 in various forms. Variations was also used at approximately 20 other institutions, primarily for streaming music course reserves.
 
In 2010, the Institute of Museum and Library Services (IMLS) awarded a $50,000 National Leadership Grant to Indiana University and Northwestern University to plan development of Variations on Video--since renamed the Avalon Media System--from August 2010 through June 2011. Since then, Avalon's development has received continual support from several other generous grants:

--IMLS National Leadership Grant for $948,000 from October 2011 through September 2014
--Andrew W. Mellon Foundation grant for $750,000 from January 2015 through January 2017
--IMLS National Leadership Grant for $967,000 from Spring 2017 to the present

The first working version of the Avalon Media System was released in the spring of 2013. By the summer of 2016, the Variations Digital Music Library was fully retired and replaced by Media Collections Online, an Avalon-powered portal for accessing audio and video materials held by the Indiana University Libraries. The Avalon Media System continues to receives additional features and improvements as part of its development process, and has been adopted by numerous other institutions as the access solution for digital audio and video collections."

**Comment by mcwhitaker** [comment]
@mschnaars A detail: there is a typo on this sentence (sorry I did not catch it before)

The Avalon Media System continues to receives
