### ISSUE TITLE
Not receiving batch success and manifest error mails on Spruce

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2420]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Batch Ingest 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10

Issue: Not receiving batch success and manifest error mails on Spruce. The email indicating that a manifest has sucessfully been processed without errors (the validation email) is being received by the user, but not the final success/fail message.

### Steps to reproduce
1. Ingest a successful batch, and the user has to receive mail about the successfully ingested items.
2. Ingest a batch with errors in manifest file (such as invalid username, missing metadata), user should be receiving mails about these errors.

**Comment by cjcolvar** [comment]
I did some testing on Friday and the invalid manifest due to invalid user appears to be sending but is sending to a non-existent account so is held up.  We could reconfigure spruce to receive these emails in the future (<-- @pdinh).  I think the other emails are failing to send due to #2418 so I'm going to work on that now.

**Comment by cjcolvar** [comment]
@pdinh could you please configure spruce so that it sends the batch notification emails to a real account that we can monitor instead of a fake one?  (I'm pretty sure resque will need to be restarted to pick up this change.)

Once that is done, I believe batch will be ready for retesting and this story can be QA'd or moved to done in favor of #2424.

**Comment by phuongdh** [comment]
Configured as avalon-core-l

**Comment by phuongdh** [comment]
I believe this has been resolved per @Karthikeya212

**Comment by Karthikeya212** [comment]
Success: Receiving manifest errors through mails
Failed: Not receiving Batch Ingest success mails or Batch ingest failure mails stating that which items failed to ingest

**Comment by Karthikeya254** [comment]
Also it would be good to have a setup that sends mails to the admin group if there is any user mail-id related issues in manifest according to #2350

**Comment by Karthikeya212** [comment]
Also it would be good to have a setup that sends mails to the admin group if there is any user mail-id related issues in manifest according to #2350

**Comment by cjcolvar** [comment]
There is one for this if the manifest doesn't have a valid email address / username.  In that case it sends an email to the same email address as the other admin notifications like new collection being created.

**Comment by Karthikeya212** [comment]
So as I receive the collection creation mails from spruce, should I be receiving this error mail as well if there is an invalid mail-id in manifest?
I didn't receive any when I tried a manifest without mail-id

**Comment by cjcolvar** [comment]
@Karthikeya212 at this point I think this might be a bug for @carrickr to take a look at if he has time.  I'm guessing that the rake task that runs every 15 minutes to check for completed/stalled batches must have a bug and it isn't sending emails.
