### ISSUE TITLE
Continued Testing for Rewritten Batch Ingest Functionality

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2424]
### Description
Further testing from #2287

## Done looks like

- [x] Wait until #2420 is completed and deployed to spruce
- [x]  end to end testing is completed using Batch ingestion testing script
- [x] Special focus will be given to email functionality
- [ ] Any bugs are generated and prioritized.

**Comment by phuongdh** [comment]
Waiting on bugs to be fixed

**Comment by davidschober** [comment]
Retest #2423 to verify

**Comment by carrickr** [comment]
Working locally, once changes are on spruce do an end to end retest.

**Comment by cjcolvar** [comment]
@carrickr were batch stalled or batch completed processing emails (#2420) sending correctly for you?  They weren't on spruce when I last tested.

**Comment by joncameron** [comment]
@Karthikeya212 Can we call this done, or is the more to test/bugs to write up?

**Comment by davidschober** [comment]
I'm a little unclear on what done is on this issue. @carrickr @cjcolvar . @Karthikeya212 tested, and created some bugs that we've acted on correct? cc: @joncameron

**Comment by cjcolvar** [comment]
@davidschober @joncameron This is not done yet.  @Karthikeya212 did a first round of testing but was blocked from full testing because of bugs with batch ingest on spruce.  I believe he retested and found that completed/stalled emails weren't sending so couldn't test batch replay.   He also ran into an issue with some rows failing on a really large batch but that mostly worked for me when I tested except for a `sqlite` bug which I expect is only a problem on spruce.
So we need #2420 fixed and then a full test of batch ingest including replay would be good to do.

**Comment by davidschober** [comment]
Right so it seems he tested and wrote new bugs. We’ve gotten stuck in the past with issues like this. I suggest we close it and have done criteria for related issues be that those issues are tested to be working.

**Comment by cjcolvar** [comment]
I think we still need this issue because he wasn't able to do full end to end testing and someone will still need to do that.

**Comment by davidschober** [comment]
We can regroup in the morning. But it's very unclear to me what done is with this issue. He tested and it failed and we wrote bugs. That should be complete for a testing issue. As a general rule, i don't like leaving testing issues open after a cycle is done and bugs are written.

**Comment by Karthikeya212** [comment]
@davidschober this is a second ticket that was created to test the bug fixes, which I have created after testing the first ticket #2287. But all the bugs weren't fixed yet, there are still some issues, there were no new bugs raised based on this testing. So, this testing is pending to be done. My concern is that email changes are the majority use cases that were supposed to be tested with batch changes and I couldn't test them end to end because of the bugs. So even this ticket is closed for now, we would need to have a similar one once the bugs are fixed and is ready to be tested.

**Comment by davidschober** [comment]
I added done criteria so that we can move this ticket along. Please add anything I missed.

@joncameron @Karthikeya212 @cjcolvar @mcwhitaker

**Comment by Karthikeya212** [comment]
Tested the batch ingest in different scenarios, below are some of the scenarios and corresponding mails.

1. All items are successfully ingested.
![all_success](https://user-images.githubusercontent.com/25850972/34173171-9cb2be7a-e4c2-11e7-8850-5af6e438dbee.PNG)

2. No valid metadata.
![no_valid_metadata](https://user-images.githubusercontent.com/25850972/34173195-aee2b26c-e4c2-11e7-8843-90d4671af3c8.PNG)

3. Missing File.
![no_valid_file](https://user-images.githubusercontent.com/25850972/34173218-bf357f6e-e4c2-11e7-8b7f-464626c45995.PNG)

4. Invalid Mail ID.
![invalid_mailid](https://user-images.githubusercontent.com/25850972/34173234-cb33d4dc-e4c2-11e7-8f55-eb45781404af.PNG)

5. User has no access rights to ingest.
![user_no_access](https://user-images.githubusercontent.com/25850972/34173258-dbe2745a-e4c2-11e7-98ae-ee741fc5b707.PNG)

### Observations
1. I found the collection name to be strange, because in case(5), we can see that collection name is identified properly when reporting missing access rights for user, but in the description of every mail the collection name is displayed as some id. In rest of the cases it is always represented with the ID, even the subject content includes this ID rather than collection name.

2. The items for which ingest is successful, they are also represented with an id (may be fedora id), rather than the file name or title (which is a case before the changes, see below)
![ingest_fails_earlier](https://user-images.githubusercontent.com/25850972/34173518-add54d5c-e4c3-11e7-96d9-47dee049bd65.PNG)
