### ISSUE TITLE
6.3 Release - OVA

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2469]
### Description
As a technical user or potential implementer interested in trying Avalon, I want to be able to easily run a full instance within a contained environment so that it's easy to see a running Avalon stack without performing a manual installation. To this end, our OVA file is updated for each new Avalon release so interested users can download and run the full Avalon stack in a preconfigured VM environment.

### Done Looks Like
- The OVA ships with Avalon 6.3 and is configured to run the application at login.
- The new OVA is available at http://www.avalonmediasystem.org/downloads/avalon-vm.ova

### Tasks
- [ ] Build OVA
- [ ] Test
- [ ] Push to server

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners we had previously moved away from bridged networking to avoid the potential security issues with default credentials.  This seems to be a hang up with getting the ova out quickly due to the nat networking requiring the user to access avalon from the guest vm and our default encoding of h.264 not being supported in linux without proprietary packages.  Is it possible to switch back to bridged networking and just give a warning in the documentation?

**Comment by joncameron** [comment]
I'm good with that. Let's switch back to bridged networking unless there are strong thoughts from @davidschober otherwise. Putting a warning in the docs seems like enough to cover bases.

**Comment by phuongdh** [comment]
We need to decide whether to do one of these things
- enable accessing Avalon from host machine:
   + bridged: currently not working
   + host-only: has special instructions on Mac
- install Chrome automatically
- ask the user to install Chrome in the instruction

**Comment by cjcolvar** [comment]
Testing ova available at http://avalonmediasystem.org/downloads/avalon-6.3.2.ova
To run this use the instructions on https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=515277053 and https://wiki.dlib.indiana.edu/display/VarVideo/VirtualBox+Networking but don't change the network configuration for the imported virtual machine.  Start up the virtual machine and click "finish configuration".  Wait a little while for avalon to boot then try accessing avalon at http://192.168.56.199 from the host machine (not the guest VM).
