### ISSUE TITLE
Highlighting Issue on Sections, Seems to Lag a Section

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2602]
To reproduce on Spruce:

1. Go to `hx11xf31z`
1. Go to Sexction 2, Centaur
1.  While that plays open Lil Scrub and close it before the clip ends, no highlighting occurs on Senior Scrub

<img width="948" alt="screen shot 2017-12-18 at 3 28 43 pm" src="https://user-images.githubusercontent.com/5350060/34126609-2de3e0b0-e408-11e7-8cf2-641ee887ed45.png">

4.  When the player autoadvances to Section 3, Lonesome Highway, there will be hightlight on Senior Scrub

<img width="931" alt="screen shot 2017-12-18 at 3 26 56 pm" src="https://user-images.githubusercontent.com/5350060/34126557-f58f34e4-e407-11e7-8961-90f31c78d8e8.png">

**Comment by cjcolvar** [comment]
@carrickr The section highlighting happens only when there is structural metadata.  The `Centaur` doesn't have any so I think it is behaving as expected.

I was seeing oddness in the first section where highlighting for the first span sticks around until the highlighting for the second span starts.  Since the second span doesn't start at the end of the first span it looks weird.

**Comment by cjcolvar** [comment]
Nevermind the section highlighting is looking good to me now for that first section.

**Comment by cjcolvar** [comment]
@joncameron @davidschober I don't understand what this issue is about.  I propose we close this and remove it from the Known Issues.

**Comment by joncameron** [comment]
Removed from Known Issues.
