### ISSUE TITLE
Matterhorn Errors Stay Internal to Matterhorn on Batch Ingest, Should we enhance?

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2628]
Matterhorn pretty much accepts anything you give it, corrupt mp4, pdf, docx, whatever and while it make eventually fail transcoding it provides no active feedback to the user.

Right now the process is:
- Submit a Batch Ingest with a .pdf file or something
- Batch runs since in Avalon land we only check for existence of file
- Media Object is created and background transcode kicks off
- User gets a 'your batch is done' email
- The only way user knows this failed is if they go check the media object, where there will be no associated media since the transcode died

There is no email sent to the user nor any kind of helpful "Hey you gave us a .pdf, we can't play that" error when you visit the media object in the browser.

Is this an area we want to improve?  I personally vote for low priority because only trusted power users are using Batch Ingest and they're not the type to upload pdfs or something.  The real error case is probably when someone uploads an audio or video file they think is valid but their transcoder can't transcode (we did see this at NU with the Quicktime home movies thing).  So there may be some value in the long run of having a task that runs over the BatchEntries table and checks for failed transcodes.  Say if 48 hours after the media object was created there are no derivatives for it you get an email alerting that you either your transcoder is really backed up or you have a bad file.

**Comment by cjcolvar** [comment]
I think we should be checking for this here: https://github.com/avalonmediasystem/avalon/blob/develop/app/jobs/ingest_batch_entry_job.rb#L32
After this line we could check that all of the master files have finished processing sucessfully but this looks like we'd have to make a few changes including making master files optionally process synchronously so I'd vote for `6.x`.  
FWIW it looks like the batch entry ingest job will finish before master files are done being processed because they are processed asynchronously.
