### ISSUE TITLE
6.3 Release - Upgrade Documentation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2695]
### Description
Write instructions for upgrading from 6.2 to 6.3

### Done Looks Like
- Wiki contains a page (https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.2+to+Avalon+6.3)  on upgrading from 6.2 to 6.3, with steps

**Comment by cjcolvar** [comment]
Avalon 6.3 requires ruby 2.3+.  I can't recall if we already had instructions on how to upgrade or not.  The manual install instructions need be updated to probably use ruby 2.4.  Everyone should probably move to 2.4 since 2.5 will probably be released on Christmas making 2.3 be security maintenance only.

**Comment by mschnaars** [comment]
Just updated the header on the wiki page for 6.3
