### ISSUE TITLE
Send Status Message Sooner to User When Batch Fails

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2767]
### Description
When a batch job dies, an email should be sent to the user notifying them that the job has failed and not been completed, rather than never sending an error email (in this particular case).

### Done Looks Like
- The _stalled_ status email is set to 1 day rather than 4 days to report back to the submitter.

**Comment by cjcolvar** [comment]
I also noticed that the media object is only attached to the batch for a row if processing is successful but the batch can error out after the media object is created.  We should probably save the media object reference in this case as well since there is still something hanging around in the repo.  Alternatively, we could delete the media object on failure but then debugging errors would be harder and sometimes one might want to manually fix the failed item instead of start the batch over again.

**Comment by joncameron** [comment]
Moved Chris' comment to a separate issue, #2812

**Comment by cjcolvar** [comment]
Looks like this is currently set to 1 day: https://github.com/avalonmediasystem/avalon/blob/master/config/schedule.rb#L13

Maybe the issue is a different one than just the timing of the stalled cron job?

**Comment by cjcolvar** [comment]
@joncameron Can we close this and remove it from the Known Issues?  I think it was resolved with some other issue that was keeping these emails from sending.

**Comment by joncameron** [comment]
Yep, this was resolved. Removing from Known Issues.
