### ISSUE TITLE
Create Docs on throttling batch

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2770]
## Description 

Batch got really powerful (we dug too deep). We  will need to create a brief, general doc for AV in case people blow up Fedora an need help.

Northwestern has a draft of docs for local use. We could generalize those. 

## Done looks like:

- Page is written describing of the problem, and proposed solutions, possibly stating how NU specifically solved it.

**Comment by carrickr** [comment]
Much of it is here: https://github.com/nulib/avalon/wiki/Throttling-Batch-Ingest-on-AWS

but we need to break it down for non AWS as well.

@cjcolvar if you find anything that my docs don't cover or are incorrect on with regard to IU's non AWS instance, toss them there or in slack please

**Comment by carrickr** [comment]
The stuff for POs, etc is on a NUL private wiki (although this particular content could be public),  we can steal from it:

### Batch in 6.3.2

Avalon 6.3.2 features a rewritten batch ingest pipeline focused on dispatching jobs to workers.  A job is a simple  task (create a media object, send a file to the transcoder, save the output from the transcoder as a derivative, etc).  Worker instances execute the jobs, by default we have two worker instances up at any given time in production and one instance up in staging.  

This architecture offers the benefit of removing a cap on the size of batches, previously we were unable to handle more than a few hundred items in a batch.  In testing we've been able to transcoder thousands.

### Fedora Limitations

Our primary limitation is that creating one new Avalon item takes at least five writes to Fedora.  The initial registration of the MediaObject and MasterFile and then additional updates as the transcoder creates derivatives and those derivatives need to be saved to Fedora.  MediaObjects with more than one file need additional writes.  

The failure point normally comes in the form of the Amazon Elastic Transcoder producing derivatives faster than 
Fedora can handle writing out derivatives.  AWS can simultaneously transcode 20 items at roughly a 1:1 rate (1 minute real time to transcode 1 minutes of video).  AWS can very quickly hand Fedora 40+ write operations if all 20 items finish up close to each other.  This was not a problem with our old Matterhorn based workflow since Matterhorn was a 3:1 rate (3 minutes real time for 1 minute of video) and had fewer simultaneous jobs.

To deal with this we've throttled the writing derivatives to Fedora to no more than 3 every 5 seconds.


### Database Connection Limitations

When a job is throttled it is written off to a database so that after a period of time it can try again.  The job writes itself, what it was going to do, and a retry time to the database.  Our database itself can handle thousands of simultaneous connections, however our worker instances are each limited to 40 connections to the database.  A worker can have more than 40 jobs that need to write out, since each write takes a fraction of a second and the worker will spend 5 seconds trying to write a job to the database.  Basically the jobs will get in line to be written to the database, but after 5 seconds if the job hasn't been written to the database the worker starts throwing errors.

Since batches have a 1 row leads to 5 Fedora writes and each Fedora write is a job, that means a thousand row spreadsheet is at least 5000 jobs.  

### So What Does This Mean?

Our transcoder is really the item that is supposed to buy us breathing room.  With Matterhorn that was always true, but AWS is faster at transcoding and can overload the rest of the pipeline.  For example you submit a batch of one thousand one hour films.  That's 5000 jobs, but...

1. The worker will initially need to create 1000 MediaObjects in Fedora and load all the derivative jobs into Amazons' transcoding service.
1. In one hour, 20 derivatives will be finished and the worker will need to register them in Fedora.  The worker will run three, write the other 17 to the database, wait, then run three more, write the remaining 14 to the database, etc.  This will take at most 3 minutes with our current throttling and waiting to retry periods.
1. Then the worker does nothing for the rest of the hour, after which it gets the next 20 derivatives.

However do the above with 1000 Red Hot Chili Peppers songs and the transcoder is emitting 20 derivatives every 1 to 2 minutes (since audio transcodes faster than film).  This is going to result in a rapid buildup of jobs that need to be throttled and the potential overload of the worker's connection back to the database.

### Has This Been Tested?

Yes.  However testing costs money since we pay by the minute every time we transcode something.  So we haven't exhaustively tested and we've been using shorter content, which is more prone to overloading the connection to the database.  

We know for a fact you can get 150 one second items (so very fast transcodes) into Avalon without any issues.  We can also get 1050 thirty second items into Avalon with a 99.99% success rate. Given most of our content is longer than thirty seconds we're counting on the transcoder to buy us more space. 

### So What Kind of Errors Do I Get?

When you submit a job to batch and something gets overloaded, there are two outcomes:

1.  When Fedora fails you'll get `Status: 500 org.modeshape...` errors in the email sent to you:
![](https://imgur.com/0xCA8SI.png)
1.  When the database connection fails, you won't get an email (since in the eyes of Avalon your batch never completed).  However both OpsGenie and Slack monitoring will report the 500 errors to dev-ops and the devs.  In the unlikely and unfortunately event folks fail to notice these alarms this after four days Avalon will send out a stalled batch email saying your batch appears to be in limbo.  

### What Can Be Done?

We have two line to walk, time and cost.  

By putting longer spacing between the Fedora writes you can make it extremely unlikely Fedora blows up on large batches.  However this means all batches, including really short ones, take much longer.  When a job is throttled it determines it will wait X seconds and try again.  X is 1 to 5 times the spacing, so for a throttling of 3 jobs ever 5 seconds that would be 5 to 25 seconds.

For example, right now a 150 line batch the worst possible time to completion (assuming no other ingests going on in Avalon):

1. All media objects written into Fedora within 31 minutes of the batch being submitted
1. All derivatives registered within 48 minutes of the last derivative completing transcoding (transcoding time dependent on derivative length)

So those timeouts can be bumped to make things easier on Fedora when someone submits an extremely large batch which makes the initial creation of the MediaObjects put less of a load on Fedora.  Since the retry is 1x to 5x adding one second to the spacing (that is say 3 jobs every 11 seconds instead of 3 jobs every 10 seconds) adds 5 seconds to the worst case time to complete. 

Bumping spacing means more writing to the database as more jobs are throttled and increases the risk of overloading the database connection.  Same for larger batches that spawn more total jobs.  This can be addressed by adding more workers, since each worker has 40 connections and jobs naturally spread out over the workers.  NUL pays for every worker we spin up, so we don't want to constantly leave a large number of workers online.  In these cases you should schedule an addition of workers will the Avalon instance managers at least a day in advance.

Beyond that consider what is being submitted.  3000 feature films is probably not going to be a major problem since the transcoder will emit derivatives slowly.  3000 songs is much riskier and probably needs to be broken into smaller batches of no more than a few hundred.

**Comment by joncameron** [comment]
Waiting on the PR to get merged, then we can come back and clean up this documentation and finish it off. 
PR: #2790

**Comment by joncameron** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Throttling+Batch+Ingest
