### ISSUE TITLE
Files In Dropbox Are Not Automatically Removed During Ingest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2903]
### Description
When a file placed in an Avalon dropbox directory is ingested, it is never deleted from the original dropbox location. This results in files that are never moved or removed from the original dropbox location, and so these dropbox locations fill up with files that have already been ingested and processed, as well as creating confusion as to whether the files have actually been managed properly during ingest. This is also a regression from how Avalon used to deal with these files. 

### Possible Causes
@phuongdh investigated and thought that the issue may lie in the master_file model

### Done Looks Like
If configured to do so, masterfiles are deleted after ingest from their dropbox directories.

**Comment by phuongdh** [comment]
The problem is when `media_path` is configured, Avalon will always copy the original file there, then ingest the copy. Any `MasterFileManagementJobs` will be carried out on the copy, not the original, so the original will always remain.

A possible fix is to always delete the copy, and perform `MasterFileManagementJobs` against the original. We might need a new field on `MasterFile` object to track the copy's location.

**Comment by carrickr** [comment]
#2946 also might impact this, we should confirm before we delete
