### ISSUE TITLE
Make prezi 3 default for a/v work

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2957]
## Description

For the IIIF Conference next week, for works of A/V type it would be good to have Avalon already default to version 3 instead of version 2 of the IIIF Presentation API spec. 

## done looks like 

- [ ] Prezi 3 is the default for works of type Audio or Video.
- [ ] Prezi 2 is the default for works of other types to maintain compatibility with current IIIF servers.
- [ ] This is deployed to fluorine on time for the demo.

**Comment by cjcolvar** [comment]
Since works can have child files of different types , I think we need to think through the various scenarios of mixed content.  (Unless we restrict to only audio and video for the Audiovisual work type but I think that approach has flaws and is a separate discussion.) 
 For now, I propose we change the wording in the first done looks like to `Prezi 3 is the default for works with representative media of type audio or video` and a similar change for the second done looks like as well.

**Comment by mcwhitaker** [comment]
@cjcolvar What you are suggesting is more than what I am suggesting, so I don't have objections to your wording. Your wording accomplishes what I expressed in my wording.
