### ISSUE TITLE
Blank structural metadata breaks view page

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3026]
### Description
The view page is broken when structural metadata is blank. Need to add an additional check to this line to handle the case when the structural metadata exists but is blank.
https://github.com/avalonmediasystem/avalon/blob/master/app/helpers/media_objects_helper.rb#L163

### Done Looks Like
- Checks are written for situations where structural metadata exists but is blank

**Comment by bkeese** [comment]
Steps to reproduce:
Choose a media object and go to its edit structure page.
Click the '+' button in the structure column and click the Edit button
Either preexisting or the default structure will be presented in the editor.
Click 'Save and Exit'
Click 'Preview'  tab and see the structure in the show page.
Return to the Edit structure page.
Click the '+' button in the structure column and click the Remove button.
Return to the Preview page and see an error screen.

When the bug is patched, the final step will show the item without structure instead of the error screen.
