### ISSUE TITLE
Scope Pawpaw in AWS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3036]

**Comment by davidschober** [comment]
## Description

We would like to have a reference implementation of Avalon (s) on aws. This can be done using MBKs terraform scripts. The goal of this issue is to get familiar with the scripts and write issues to complete work in the future. 

## Done looks like
- review terraform scripts and docs
- create issues

**Comment by phuongdh** [comment]
Note from metting with mbk:
Remove:
- stack/applications/cantaloupe
- cantaloupe 
- cloudwatch
- elasticsearch
- frontend
- lambdas/iiif
- iiif-related stuff

.tfvars:
prefix everything with environment value

upload certs to aws_acm, refers in avr/main.tf by name
setup trusted_signers and signing certificates manually, put value in .tfvars. 

AWS system manager/Parameter Store:
- email setting: stack-avr/Settings/email/comments
- signing key and id

data.terraform_remote_state.stack.index_endpoint

avr: main.tf 

NU Avalon:
- has config/_aws_config.rb forces Config to import from Parameter Store and overwrite env vars
- .ebextensions no longer used, is living in nulterra
- Dockerfile
- Jenkinsfile build new container and deploy
- Gemfile
- Gemfile.local

2 stage process:
- cd stack; terraform apply
- cd applications/avr, terraform apply

Most aws ssm stuff unnecessary 

More doc in gist.
