### ISSUE TITLE
Switching between player tracks

### ISSUE THREAD

**Issue by srsridh** [avalonmediasystem/avalon#3091]
#####Performance Testing #####

**Steps**
1.   Browse and open the 100-section item.
2. Start   playing the item.
3. The   sections should be switching and playing the next sections automatically.
4. Note   down the time taken from the end of playing a section to the start of playing   the next section.

The benchmark time recorded by Karthikeya was 300ms and it is taking about 507.6ms when I tested it. 

### Done Looks Like
- These steps are taken again so they can be recorded by Skylight
- Investigate how to improve performance issues related to this ticket
- Create new issues as needed

**Comment by joncameron** [comment]
These performance tickets from Krishna are almost a year old and geared toward Skylight, which we haven't used in a while. I'm going to close these in anticipation of some more formal testing closer to the release of Avalon 7. In particular there have been a lot of changes that make most or all of these no longer applicable to the codebase as it is now.

**Comment by mcwhitaker** [comment]
@joncameron The Skylight step was just to confirm the discrepancy that he was reporting. The ticket itself has no dependency on Skylight.

If you are closing this in anticipation of formal testing later, could you create the ticket for the future formal testing so it is in our radar? It has happened more than once that we didn't allow time enough to address issues found in performance testing because we did the testing right before a release and didn't want to hold the release to address the performance issue reported.
