### ISSUE TITLE
Master file management strategy `none` & web UI upload: result master file deletion

### ISSUE THREAD

**Issue by jefferya** [avalonmediasystem/avalon#3291]
Experienced behaviour:

When setting the master file management strategy to `none` and uploading a video via the web UI the result is the uploaded master file is no longer present in the filesystem.

How to reproduce:

- clone https://github.com/avalonmediasystem/avalon/commit/151dc4d9b7d7979af3cfb43242705f997ae8a57c
- alter `docker-compose.yml` adding `SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=none`
- `docker-compose up -d`
- via the web ui, add metadata and upload a new video
- within the docker container, the uploaded file is visible while transcoding occurs; when transcoding finished, the file disappears.
- inspecting Fedora, the filename and locator metadata use the `tmp` location e.g., `file:///tmp/videoshort.low.mp4`

Note: the following contains an example of the `docker-compose.yml` used to test the above:
https://github.com/jefferya/avalon/commit/761620ff8fb83e1bc0a5d45cf32e492b2954e390

**Comment by phuongdh** [comment]
@jefferya I think this is expected behavior. You were probably looking at working_file_path which does get [cleaned up after ingestion](https://wiki.dlib.indiana.edu/display/VarVideo/Working+File+Path). 

With `SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=none`, Avalon doesn't touch the original uploads but since they're in `/tmp`, they will eventually disappear.

If you want to keep the origin upload, I'd suggest setting `SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=move` and `SETTINGS__MASTER_FILE_MANAGEMENT__PATH=/path/to/preserve`. See results below.

During ingest:
```
 #<MasterFile id: "9p2909328", file_location: "/tmp/fireworks.mp4", masterFile: "file:///tmp/fireworks.mp4", working_file_path: ["/masterfiles/06b98d49-485c-416c-85bc-4a1fa2c1e930/fireworks.mp4"]>
```
After ingest:
```
 #<MasterFile id: "9p2909328", file_location: "/home/app/avalon/9p2909328-fireworks.mp4", masterFile: "file:///home/app/avalon/9p2909328-fireworks.mp4", working_file_path: []>
```
