### ISSUE TITLE
Add many forms of authentication to AWS turnkey

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3300]
Avalon auth from Notch8 (Persona) should be the default auth out of the box. The goal is to have a suite of authentication  as a starting point. 

-  Thinking about use with:
  * CAS
  * Shibboleth
  * Identity
  * LDAP
- Implement plugin from notch8 

### Done Looks Like
- Discussion about what is needed for auth config/setup in turnkey
- Preload things as much as possible to make it easy for users to configure other auth solutions (within reason)

Child of #3230

**Comment by cjcolvar** [comment]
We've been using omniauth for a number of years now and Avalon has been configured out of the box to work with omniauth-identity, LTI, API keys, and now persona.  I wonder if it makes sense now to ship defaults for CAS, LDAP, and Shibboleth since we know they are really the only other auth schemes being used.  Right now we point implementors in the right direction but require them to do the coding themselves.  The only downside to shipping implementation for these missing auth schemes is that we don't use them here at IU for avalon and thus implementation and maintenance might be time consuming or a bit naive.  If we don't create these defaults then maybe for this story we just need to add clearer documentation for how implementors add new auth schemes.

**Comment by joncameron** [comment]
Based on this I'm for documentation, rather than possibly underbaked code provided by us on how people _might_ want to configure auth. 

Maybe this could be supplemented with some example code from IU or Northwestern (like IU's CAS) as an example to draw from, as we've done in the past with some other things?

**Comment by joncameron** [comment]
## Discussion Notes

There are 3 core stacks: traditional, container, and AWS.

Traditional:
- Avalon
- FFmpeg
- NFS
- Streaming Server (Wowza)
This is represented by Spruce.

Container:
-avalon
-ffmpeg
-minio
-nginx
This is represented by the IU Docker Enterprise Sandbox.

we need a story for the above, to deploy and smoke test. This could be a 5, and include finishing minio work. All that these stacks need is a smoke test.

AWS
- Avalon
- Elastic Transcoder
- S3
- Cloudfront
This is represented by Demo (demo.avalonmediasystem.org).
This is the Turkey stack.

For 7.0, we can use demo box for testing the turnkey stack, since it’s not yet in production. In the future, we can spin up and tear down a turkey instance in AWS.

We also discussed the official support for mixing and matching between these. We won’t do that, but it’s expected that this will happen in the real world. For example, some instances are set up at IU with docker containers for Avalon and ffmpeg, and then central IT NFS and Wowzas. We can mention in docs that this it's certainly possible to mix and match between local and cloud services, but we don’t need to go with the complexity of supported in full any arbitrary number of configurations.
