### ISSUE TITLE
SME Structure edit modal requests waveform.json twice

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3414]
It looks like either the SME or the structural edit modal where the SME is being rendered is fetching the waveform.json twice.  It is downloading the whole file each time.  The waveform.json is rather large (~4 MB for a 47 minute file) and can be slow to retrieve.  I think the time to fully load the SME would be greatly reduced if we are able to take out this second request.

**Comment by Dananji** [comment]
The reason for this happening is because the React app fetches the `waveform.json` once and then pass the URL to Peaks, which then fetch the waveform.json again. The data from the 2nd request is used by the Peaks to populate the UI waveform.

The reason for fetching the `waveform.json` in the React app is to see if there are any errors and handle them properly before calling Peaks. 
Changing the React app API request to just check whether the resource exists instead of fully downloading it would work fix this.

**Comment by adamjarling** [comment]
Sounds like a good solution to me.  Mind running with this @Dananji ?

**Comment by Dananji** [comment]
Sure :+1:
