### ISSUE TITLE
Timeliner gives the wrong prompt when saving a shared timeline.

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#3479]
If a user sets the visibility of their timeline to shared, the next time they edit it and try to save they will be given the prompt intended for other users about saving a copy instead of the original.

If they proceed anyway, the timeline will be saved as expected (not as a copy).

The UI needs to use a more reliable method for determining if the current timeline is the current user's or someone else's and prompt accordingly.

Code here: https://github.com/IUBLibTech/timeliner/blob/master/src/sagas/index.js#L360

**Comment by Dananji** [comment]
@bkeese So I was looking into this and I did the following in `timelines_controller.rb` at [line 103](https://github.com/avalonmediasystem/avalon/blob/master/app/controllers/timelines_controller.rb#L103)
```
if current_user == @timeline.user
  url_fragment += "&resource=#{URI.escape(manifest_timeline_url(@timeline, format: :json), '://?=')}"
  url_fragment += "&callback=#{URI.escape(manifest_timeline_url(@timeline, format: :json), '://?=')}"
elsif current_user
  url_fragment += "&resource=#{URI.escape(manifest_timeline_url(@timeline, format: :json, token: @timeline.access_token), '://?=')}"
  url_fragment += "&callback=#{URI.escape(timelines_url, '://?=')}"
end
```
instead of this,
```
url_fragment += "&resource=#{URI.escape(manifest_timeline_url(@timeline, format: :json, token: @timeline.access_token), '://?=')}"
if current_user == @timeline.user
  url_fragment += "&callback=#{URI.escape(manifest_timeline_url(@timeline, format: :json), '://?=')}"
elsif current_user
  url_fragment += "&callback=#{URI.escape(timelines_url, '://?=')}"
end
```
Then I tested with timeline's (belongs to user 1) visibility set to `Share by link` and opening that particular timeline logged in as a different user (user 2).
Now, when saving the timeline, the message `'This timeline isn’t yours. Saving will create a personal copy of this timeline that includes any changes you’ve made. Proceed?'` is given only when the timeline is opened using the shareable link by `user 2`. 
When `user 1` edits the timeline and saves it, the message `Saved Successfully` appears.

When timeline's visibility is set to `Public` both users can edit and save it successfully (the expected behavior)

I'm not sure this affects other functionalities or this is the correct way to do this :)
What do you think?

**Comment by mcwhitaker** [comment]
I am not sure that we have ever meant for a public timeline to be editable by the creator and other users. I thought only the creator would ever be able to edit it. The way I understand it, _public_ or _shared by link_ should only affect how others get access to the timeline.

**Comment by Dananji** [comment]
@mcwhitaker Timelines with both `Public` and `Share by link` behaves the same way when they are opened by another user instead of the creator of the timeline. It prompts the message `This timeline isn’t yours. Saving will create a personal copy of this timeline that includes any changes you’ve made. Proceed?` when a different user edits the timeline and saves it.
The above comment was me misunderstanding the visibility concept for the timelines. Sorry about that.

**Comment by joncameron** [comment]
We either do something slightly different, or what @Dananji suggested.
