### ISSUE TITLE
Upgrade MediaElement.js to latest version

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3480]
### Description
A lot of bugs have been fixed since we first pulled in ME4 two years ago, including this one: https://github.com/avalonmediasystem/avalon/pull/3478

We should upgrade to 4.2.10 (or newer) to get all of the fixes plus new HLS.js. It will need extensive regression testing but I feel like it should be relatively safe https://github.com/mediaelement/mediaelement/releases

### Done Looks Like
- Mediaelement is upgraded to the 4.2.10 or newer within Avalon

**Comment by davidschober** [comment]
This makes sense. What kind of size is this story

**Comment by cjcolvar** [comment]
I think that most of the time for this ticket will be for regression testing the player in all browsers/platforms.

**Comment by cjcolvar** [comment]
I tested Chrome, Firefox, and Safari on my Mac and found the following small things (besides the 0:60 bug being fixed):
Firefox - spacebar on play button toggles but only for a split second instead of being permanent
Safari - Paused seeking by keyboard sometimes doesn't update slider or current time which also happens on MCO but spruce shows stripes (seems like buggy behavior in both cases just manifested slightly differently :shrug:); Embedded player jumps up slightly when tabbing through controls and giving focus to qualities gear icon
Present on MCO and Spruce - When in fullscreen and the user tabs past the exit fullscreen button it should give focus back to the play button instead of the next link/DOM element on the page past the player.

I haven't tested on mobile yet.

**Comment by bkeese** [comment]
Chrome on Android looks really good. The only bug is a pre-existing one: duration displays as 0:00 until playback begins.

**Comment by cjcolvar** [comment]
I can't test iOS on spruce through browserstack because spruce streaming requires VPN so I'll have to test on someone's physical device.

**Comment by cjcolvar** [comment]
Playback of qualities other than auto works on android on spruce (and not MCO) but I think that is due to this issue and not ME.js version: https://github.com/avalonmediasystem/avalon/issues/3394

**Comment by joncameron** [comment]
I'd like to keep this MediaElement upgrade on the reasoning that keeping up to date and fixing any bugs that spring up is a better option than pinning to specific older versions. I'll create a new issue to fix the things that Chris reported.
