### ISSUE TITLE
LTI Issue in Safari

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3543]
### Description
Safari has restrictions on iframes setting cookies, resulting in a situation where cookies can never be set for an embedded Avalon page, making it so that users cannot authenticate to access the content. This has been an issue on Safari 12.1, the latest as of this writing.

More testing needs to be done to nail down the scope of the issue.

### Done Looks Like
- When using an LTI share link from Avalon as a tool in Canvas, the embedded LTI Avalon context is able to use cookies and able to authenticate properly.

**Comment by cjcolvar** [comment]
Prior work: https://github.com/avalonmediasystem/avalon/issues/2319

I investigated this more and it seems like the previous workaround still works in Safari 12.1.1 on browserstack but not in Safari 12.1.2 locally.

I tried disabling google analytics on mco-staging but that didn't seem to have any impact.

I was able to workaround the issue entirely (without using the previous workaround) by disabling all tracking blocking globally in Safari (Preferences -> Privacy -> Uncheck Prevent cross-site tracking) and restarting Safari (each time this is unchecked Safari needs to be restarted as far as I can tell).  

Configuring external tools to open in new windows still works.

**Comment by cjcolvar** [comment]
I don't think there is an easy solution to this.

Using LTI v1.3 or Advantage services would be an epic of its own and it isn't clear to me if this would entirely workaround the Safari restriction.

The approach NU has taken is to use canvas apis to get the list of courses a user belongs to.  This would tie us to canvas since I don't believe there is an equivalent api in LTI Advantage. I'm also not sure if this works around the Safari restriction either.  It does have the benefit of users being able to see all of the resources from all of their courses no matter how they logged in.
https://github.com/nulib/avalon/blob/nu/deploy/production/app/services/canvas_service.rb
https://github.com/nulib/avalon/blob/nu/deploy/production/app/controllers/users/omniauth_callbacks_controller.rb#L55-L62

**Comment by cjcolvar** [comment]
I just tested and it looks like even trying to login to Avalon from within LTI launched within an iframe on Safari is blocked.  Iframes on Safari seems like it just won't work.
