### ISSUE TITLE
Upgrade to Latest active_encode Version

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3574]
### Description
To replace Matterhorn, the active_encode version used needs to be updated to a current version and the adapter used needs to be changed.

### Done Looks Like
- The active_encode version in Avalon is upgraded to the latest version needed
- The default adapter used is changed from the Matterhorn adapter to the local FFmpeg adapter 
- This is working outside of Docker (on Spruce)

### Notes
- The Elastic Transcoder integration will break once this happens (separate issue)
- The 'skip transcoding' feature will break once this happens (separate issue)
- This will break Docker :( (separate issue)

**Comment by cjcolvar** [comment]
This is now on spruce and working.  

We had to edit ~/.bashrc and add `export RAILS_ENV=development ENCODE_WORK_DIR=/srv/avalon/rtmp_streams` so that the Ffmpeg adapter would use the streaming directory as it's workspace.  It is a shortcut that works for now but we may want to do something different before release.  We also had to install the latest mediainfo from epel since the Ffmpeg adapter requires a newer version.
