### ISSUE TITLE
Docker-compose Works With FFmpeg Adapter in Latest Active_Encode

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3580]
### Description
Updating our Docker setup to work with the local FFmpeg adapter in active_encode updates to Avalon.

### Done Looks Like
- A new worker container is made which runs the FFmpeg adapter
- The worker listens to the background job queue
- Multiple worker containers are possible 
- Writes to the Avalon/active_encode database 
- Deploys derivatives to streaming server store
- Streaming should work

### Notes
- This issue depends on code changes to avalon (#3578)
- General goal for splitting resources out for transcoding is two-fold: Docker setup which allows you to use multiple containers, and splitting FFmpeg across a separate machine or machines

**Comment by cjcolvar** [comment]
We've been successful at moving the ffmpeg processing to a worker container separate from the avalon container, but are still stuck at one worker container for encoding due to the ffmpeg adapter's reliance on a local filesystem.  There is some hope that we could change the adapter to use a remote data store like minio but that would require more work.
