### ISSUE TITLE
Test the new Avalon demo system

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3583]
### Description
The new system is up on https://demo.avalonmediasystem.org. We need to make sure that it's functionally equivalent to pawpaw. A light regression test would probably suffice.

### Done Looks Like
- Regression testing done on demo.avalonmediasystem.org
- Bug/regression reports created as discovered

**Comment by SumithBaddam** [comment]
Performed regression testing on the demobox and there were few minor bugs. I am attaching the excel for the same. [https://app.zenhub.com/files/3336925/19ad7403-4177-4561-8f4b-6816ce606420/download](https://app.zenhub.com/files/3336925/19ad7403-4177-4561-8f4b-6816ce606420/download)

**Comment by mcwhitaker** [comment]
@joncameron - Would you like Sumith to create tickets for the items on his spreadsheet?

**Comment by joncameron** [comment]
@mcwhitaker Yes, please! The only thing I see that doesn't need to be noted is 
Acc_011–Video. Valid captions file formats are .vtt and .srt, which is why .txt and .cap files weren't accepted by the system.

@SumithBaddam, you can find an example vtt file and video here for use in testing here: https://northwestern.box.com/s/tdaommgty3fcvjwfs9qoaqairfxxufmk
