### ISSUE TITLE
Collections Index - Continued Styling

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3629]
### Description
Continued layout and styling work for the collections index page. This issue follows #3591.

### Done Looks Like
- [x] Styling implemented based on mockups and discussion
- [x] CSS is checked for good implementation and fixed as necessary

**Comment by adamjarling** [comment]
@joncameron @cjcolvar Will these collection thumbnails be a consistent size,  or different for each collection item?

![image](https://user-images.githubusercontent.com/3020266/66236571-7272ae00-e6b8-11e9-9f04-71ce7bb01c60.png)

**Comment by bkeese** [comment]
@adamjarling Those icons are expected to be all the same size.

**Comment by joncameron** [comment]
Thoughts from me:
# -
The font size should be bumped up given the currently layout. 
With font sizes increased:
<img width="1198" alt="Screen Shot 2019-10-04 at 11 09 20 AM" src="https://user-images.githubusercontent.com/1406618/66399248-40f62d00-e9ad-11e9-8a79-cc80b2bb1018.png">
Currently:
![Screen Shot 2019-10-08 at 9 22 48 AM](https://user-images.githubusercontent.com/1406618/66399253-45bae100-e9ad-11e9-83cf-deb7bf00ab77.png)

# -
Collection description probably shouldn't fill the rest of the width of the column. 
Currently:
![Screen Shot 2019-10-08 at 9 05 15 AM](https://user-images.githubusercontent.com/1406618/66398858-882fee00-e9ac-11e9-82ec-e0c5a6a07a3a.png)
At 70% width:
![Screen Shot 2019-10-08 at 9 05 11 AM](https://user-images.githubusercontent.com/1406618/66398868-8cf4a200-e9ac-11e9-8aa8-62de465c6039.png)
This could be part of a larger question about 

### -
Headers:
The font family for header tags should be outlined. I'm leaning toward thinking that h1 and h2 should be MuseoSlab and h3 and h4 are Arial.

**Comment by adamjarling** [comment]
More feedback

#### Collection Listing 
- Make sure multiple Units have some sort of UI grouping (border or something)
- Add some Units to test that visual
- Make all cards the same height.
- "See "X" number of collections" / "See less" for the + - button

#### Collection Landing
- Temporarily get rid of faceting
- Add a link "Filter this collection", and take right to the blacklight page
- Make the Unit name be bigger, and one headline size under page headline (so it looks more important).
- Update the top UI to look kind of like this:
- @joncameron  Possibly make the Collection image a square ratio, instead of 16:9?   See below example...
- Make collection title to use `page-title` class instead of it's current `h3`.
- Make description copy Bootstrap "lead" copy.
- Lead copy description, cut off the text at 100 or so words, and give a "read more" link to show rest of text in accordion.

![image](https://user-images.githubusercontent.com/3020266/66586849-f57b8480-eb4e-11e9-9475-2f7313729295.png)

![image](https://user-images.githubusercontent.com/3020266/66587115-6cb11880-eb4f-11e9-9d49-ff8b5c053c1e.png)

End result kind of looks like this:

![image](https://user-images.githubusercontent.com/3020266/66588099-5c9a3880-eb51-11e9-8e79-82db5a5e3aed.png)

**Comment by adamjarling** [comment]
@mcwhitaker And here's a screen shot to use for the Collection index page:

![image](https://user-images.githubusercontent.com/3020266/66590436-61152000-eb56-11e9-9d63-0705f549eed8.png)

**Comment by mcwhitaker** [comment]
@adamjarling Thank you for the screenshot for Collections Index page. Which one should I use for the collection landing page?

**Comment by adamjarling** [comment]
@mcwhitaker There's another screenshot in #3630 for the landing page.  David, Jon and myself worked through it and tweaked in the browser.  I'm not sure I can quickly re-create what we arrived at, so hopefully it works to get the idea across?

**Comment by adamjarling** [comment]
@joncameron @davidschober I'll create some issues today from the notes above from our Thursday meeting while they're still relatively fresh in my head.
