### ISSUE TITLE
Some Caption Files Do Not Display

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3668]
### Description
Videos with caption files in which the last cue has a time timecodes but no cue text do not display the captions within the video player, even when the closed caption toggle is enabled.

### Environment
Pawpaw, Spruce, IU Production. Tested with latest versions of Chrome, Firefox and Safari.

### Examples
SRT in Pawpaw: https://pawpaw.dlib.indiana.edu/media_objects/mw22v559x
SRT in Pawpaw: https://pawpaw.dlib.indiana.edu/media_objects/6682x405k/section/rn3011410
VTT in MCO Production: https://media.dlib.indiana.edu/media_objects/bk128b05q

**Comment by bkeese** [comment]
In the case I'm looking at (the first eample), this seems to be caused by the last line of the caption file. There is a time code, but no caption following it. I think even an empty line afterwards would fix it. Otherwise, remove that last empty caption, time code and all. We could add a condition in the mejs code that would handle this too, if we want. `text = text==null? '' : text.trim...`

**Comment by mcwhitaker** [comment]
Could this issue be related to this: https://bugs.dlib.indiana.edu/browse/VOV-5947

**Comment by bkeese** [comment]
@mcwhitaker That's a different issue, but we still need to handle that one too afaik.

**Comment by joncameron** [comment]
These files came straight from a vendor and are completely valid regarding the spec (https://www.w3.org/TR/webvtt1/#webvtt-caption-or-subtitle-cue-text) so this should be handled on our end in some way. Odd that MEjs chokes on it.

**Comment by joncameron** [comment]
Updated the description to note the specific circumstance that isn't being handled well here. I threw an empty line at the end of the failing WebVTT in question and and it worked without issue, as Brian predicted.
