### ISSUE TITLE
Inline MediaElement Plugins

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3710]
### Description
MediaElement plugins for Avalon currently sit in separate repositories within the Avalon organization. Some of these plugins may already be inlined, but it may be worthwhile to check this and inline any that exist separately, removing the unnecessary repositories from the Avalon Media System org in Github as desired.

### Done Looks Like
- Existing repositories for media element are looked over and evaluated
- Non-functional or legacy repositories are archived if desired

**Comment by Dananji** [comment]
`mediaelement-hd-toggle`: not used in Avalon at the moment. The functionality of this is somewhat similar to the functionality of quality-selector plugin. And the JS code in this gem is already in the Avalon code base as a mediaelement plugin. And this in-built plugin is also not being used in the application at the moment

`mediaelement-track-scrubber`, `mediaelement-add-to-playlist`, `media-element-thumbnail-selector`: there are references to these in the coffee script where the player is being initialized. Need to understand whether these references are to these external gems or the similar plugins written inside the Avalon code, as JS modules. **Needs further investigation

`mediaelement-title`, `mediaelement-skin-avalon`, `mediaelement_rails`, `media-element-logo-plugin`: these gems are in Avalon's Gemfile, but these are not actively being used at the moment

`mediaelement`: this contains all the plugins from mediaelement. But this is not used in Aavalon at the moment. This repository doesn't contain the  fixes we've put in for mediaelement player code in Avalon

All these plugins are referenced in the Avalon Gemfile, but seems like they are not actively being used in the player, because some have been written as plugins inside the Avalon code base with JavaScript.

**Comment by Dananji** [comment]
The existing mediaelement plugin repositories can be archived because, they are not being used in the Avalon code and we are not doing any active development on them (like bug fixes). The code for required plugins for the current Avalon player functionalities reside within the Avalon code itself.
