### ISSUE TITLE
Performance Testing for Avalon Turnkey using ECS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3725]
### Description
While evaluating the use of ECS, performance testing should be done.

### Done Looks Like
- Under a cloud install using ECS, standard performance testing metrics are taken

**Comment by phuongdh** [comment]
**Conclusion**: given enough time to scale out, ECS has a lot fewer errors such as pages not loading, stream not playing. A lot of these errors here are not load-related. Average page response time is slower due to Avalon containers being spread out to different hosts from Fedora/Solr and there's no assets caching yet (4.3s vs 1.85s)

Compose-based stack
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/9fd2df49-cd0c-4771-a42c-5ccabe937000)

ECS-based stack 
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/24c38743-f480-43d3-9b80-5c6550bdeaf8)
