### ISSUE TITLE
New ActiveEncode Adapter for Pre-Transcoded Derivatives

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3746]
### Description
To make pre-transcoded derivatives possible in Avalon 7.0 we'll create a new ActiveEncode adapter, _passthrough_. Passthrough will be a clone of the FFmpeg adapter, where the FFmpeg commands are taken out and a bit of special handling is added.

### Done Looks Like
- New clone adapter for ActiveEncode named _passthrough_ is created
- FFmpeg commands removed and special handling added to passthrough adapter

**Comment by cjcolvar** [comment]
Special handling means accepting a hash of the pre-transcoded files (labels -> files) as an option and turning those all into outputs.  The input file supplied to the adapter should be the highest quality derivative that is a stand-in for the master file.

**Comment by cjcolvar** [comment]
Testing on spruce:
- UI upload and dropbox with skip transcoding selected work
- Batch ingest with skip transcoding works for single file but with multiple qualities it fails.
The adapter tries to find the label for the output but fails due to the difference between the incoming filename (input.high.mp4) and the outputs (input.high-high.mp4, input.medium-medium.mp4, input.low-low.mp4).  This should be pretty east to solve.
