### ISSUE TITLE
Sanitize Filename Before Processing in ActiveEncode 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3926]
# Description
There are characters common in filenames which are not able to be used with some of the services used by Avalon. It would be ideal if sanitization happening at the beginning of the processing process, so that encoding platforms, streaming servers etc. are able to read the filename without issues. Users should be able to:
- Users can submit filenames with Unicode characters and otherwise special but normal characters frequently used: $,!,.,), etc.
- No errors related to filename are encountered during transcoding process

# Issues We've Encountered
- #4444 (Quote characters case errors)
- #4287 Special characters break in AWS
- #3952 (Spaces in Docker setup)
- #4411 (Wowza does not respect filenames with repeated period characters in the filename)
- #4414 Issues with spaces
- #3925 (Allow Unicode Characters in Media Files)

# Done Looks Like
- List created of areas in the application that need attention or fixes for filename handling.

# Reference
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

**Comment by joncameron** [comment]
Where does this list exist? Do we need to check the AWS and streaming server docs to compile a list, or is there some other simpler method?

**Comment by joncameron** [comment]
We have something somewhere about this (or was it about UTF-8?). We need to figure out the cases that this applies to (AWS? Docker?) @phuongdh has a list in another ticket that should be attached to this ticket.

**Comment by masaball** [comment]
### Notes on each ticket
#4444 (Quote characters cause errors): Quotation marks and single quotes are problematic in all of the adapters. AWS recommends to completely avoid using quotation marks and ffmpeg needs both styles of quote mark to be escaped, as far as I can tell. I think the best way forward is to sanitize based on AWS restrictions because they are less permissive than ffmpeg, from what I can tell, but having consistent sanitizing would be easier to maintain. Ffmpeg adapter already has [some sanitizing setup](https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L220) but it is after processing. There may be some sanitizing needed before processing in [the create method](https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L14) to escape characters so that the file is properly found.

#4287 Special characters break in AWS: It looks like the AWS adapters work in similar ways. They both check the s3 bucket for the file and then upload the file to the input s3 bucket if it does not already exist in there. [ElasticTranscoder](https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/elastic_transcoder_adapter.rb#L127) and [MediaConvert](https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/media_convert_adapter.rb#L485). Sanitizing the filename before the upload may solve this ticket.

#3952 (Spaces in Docker setup): Was this solved by #4781? Or another PR? I was not encountering hung up jobs in the testing I was doing.

#4414 Issues with spaces: For some reason files with spaces are not having the technical metadata automatically generated. From the media object dashboard, the transcode appears to go through without error, but the resulting encoding has no output information so the player has nothing to load and stream. The technical metadata is [created by this method](https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L286). My guess is that the file_path variable being passed in when this method gets called is not matching the actual file path or is otherwise causing the `Nokogiri::XML File.read(file_path)` to not read the file properly. There is a similar method in the pass_through_adapter which would also need to be bolstered.

#3925 (Allow Unicode Characters in Media Files): There is some discussion in the ticket about how a check for ASCII characters may have been put in place because Matterhorn (now OpenCast, I think?) did not support non-ASCII or at least not full unicode but Avalon does not use that transcoder anymore. This ticket can probably be resolved by removing the [error generation found here](https://github.com/avalonmediasystem/avalon/blob/90832296809f3684405acb7b4e44d7ed0720d92e/app/services/master_file_builder.rb#L37).

#4411: I'm not sure on where the likely pain point is with wowza yet.

### List of attention points

Ffmpeg adapter:

- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L286
- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L14
- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/ffmpeg_adapter.rb#L220

Pass through adapter:
- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/pass_through_adapter.rb#L217

AWS Adapters:

- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/elastic_transcoder_adapter.rb#L127: copy_to_input_bucket method.
- https://github.com/samvera-labs/active_encode/blob/dc4b82c6593deaf9e49ad60f0bdd7db83fc00e69/lib/active_encode/engine_adapters/media_convert_adapter.rb#L485: s3_uri, check_s3_bucket, and upload_to_s3 methods.

Unicode characters:

- https://github.com/avalonmediasystem/avalon/blob/90832296809f3684405acb7b4e44d7ed0720d92e/app/services/master_file_builder.rb#L37
