### ISSUE TITLE
Bring IU Styling Changes into Core

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3962]
### Description
Porting the styling changes that have been made for IU production, which fix a number of issues, into the core codebase.

### Done Looks Like
- List of changes determined
- Code pulled into current develop for Avalon

**Comment by Dananji** [comment]
Changes brought in from IU customization:

1.Safely handle case where master file doesn't exist
2. Add pagination to the bottom of the collections landing page
3. Align create and import variations buttons in Playlists and Timelines pages
4. Hide browser auto complete so it doesn't hide the date widget
5. Tighten up collection cards
6. Rejoin statement of responsibility with title on item page
7. Add `preventDefault` on search box form submit button on enter key on Collections pages
8. Set Timeliner to full width
9. Use 4 columns instead of 3 in Collections pages
10. Show full unit name in AZSort when there is no description in Collections page
11. Make field buttons gray on `Resource Description` step in file ingestion
12. Wrap long file names into a new line when there are no white spaces, `Manage Files(s)` and `Structure` steps in file ingestion
13. Make timeline action buttons consistent with playlists buttons
14. Add placeholder text when there is no description in playlists
