### ISSUE TITLE
Avalon 7.0.1 Patch Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3963]
### Description
Combining bug fixes and styling changes into a patch release for Avalon.

### Done Looks Like
-

**Comment by cjcolvar** [comment]
Rough changelog:
>#3935 - Increase Intercom timeout
#3942 - Show all collections on admin collections index page
#3946 - Fix email sending in AWS environments
#3950 - Remove unnecessary article on homepage
#3955 - Turn on timeliner in development environment
#3954 - Standardize styling for tables
#3956, #3968, #3993 - Updated SME build with new peaks.js and bug fixes
#3972 - Ingest api stores hls_url
#3975 - Performance improvement loading item view page when it has comments
#3969 - Number of UI improvements brought in from MCO
#3979, #4003, #4004, #4005 - Styling changes
#3967, #3990 - Ingest API improvements - MediaObject - add masterfile ids, derivative ids are actual ids instead of track ids now, structure can be inlined with query param; collection items are proper JSON instead of JSON string; Allow manager, editor, and depositors to get full media object json
#3986 - Fix playlist table sorting
#3989, #4001 - Fix player in IE11
#3987 - Intercom push button fixes
#3992 - Increase size and quality of thumbnails
#3809 - Cypress testing
#4000 - Dependency security upgrades

**Comment by joncameron** [comment]
Close in favor of #4010
