### ISSUE TITLE
Mco-stagging timeliner custom values start and end not correctly displayed

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#4054]
![timelines2.PNG](https://images.zenhubusercontent.com/5d67e1cbb530512d88c8f52c/d8d147e1-a9ad-45a6-aa23-9457e3e1b7bf)Unlike mco production, mco-stagging is not showing custom timeline values. It is displaying 00:00:00 as both start and end

**Comment by Dananji** [comment]
It takes a couple of seconds to load the derivative, if you click on `Create Timeline` button within that window the custom values are filled like this. Because the initial values are zero until the stream is fetched. This happens in other instances as well (MCO, spruce).
A possible solution (UI-wise) would be to, disable the buttons until the derivative is loaded into the player.
@mcwhitaker @joncameron What do you think?

**Comment by mcwhitaker** [comment]
@Dananji - are you suggesting disabling the "Create Timeline" button on the main page until the derivative is loaded? That seems like a good solution to me.

**Comment by Dananji** [comment]
@mcwhitaker Yes :+1:

**Comment by joncameron** [comment]
@Dananji Sounds great 👍

**Comment by Dananji** [comment]
Fixed and on mco-staging now :+1: 
@SumithBaddam Please test this and #4055 when you have time. Thanks!
