### ISSUE TITLE
Test Universal Viewer Support for Avalon Manifests

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4081]
### Description
We should explore and list issues of Universal Viewer playing Avalon-generated manifests. There are still some issues with UV playing our media, and it would be good for us to know what these are and what is causing them. 

### Done Looks Like
- Timeboxed investigation into issues with using Avalon manifests in UV
- List of issues compiled and possibly shared with UV development team

**Comment by Dananji** [comment]
Observed:

1. Avalon manifests are missing the property `format` for items (https://iiif.io/api/presentation/3.0/#format), and UV expects it to be present. Because of this UV can't load the manifest.

2. I updated a manifest from Spruce in JSONBin.io (link: https://api.jsonbin.io/b/5ea9a95e66e603359fe0cd7d/5) and tried loading it in UV, and it loads the player. When it is being played there's no sound even though the time is updated in the player. In the console in DevTools it keeps logging `loading media` indefinitely.

![Screenshot from 2020-04-29 13-54-59.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/eeb2fc95-3fae-419c-a730-04da2058e670)

It seems the `loadedmetadata` event in ME.js is not getting fired. And I can't figure out what's the reason for this.

3. IIIF 3.0 spec presentation manifests in maple loads and plays as expected.

**Comment by Dananji** [comment]
Tested on https://uv.netlify.app/;

1. Manifest from maple, (https://dlib.indiana.edu/iiif_av/lunchroom_manners/lunchroom_manners_v6_jwd.json) works well in this app
2. Manifests from both spruce and mco-staging, does not work in this. It fails trying to fetch additional data from the stream URL. 
For sample manifests with images, this action happens for fetching additional information for the images from the an image service. 
For Avalon manifests, the error occurs when trying to go through the `service` section in the items for authentication. According to 3.0 spec [here](https://iiif.io/api/presentation/3.0/#service), the `services` block has some changes from previous version. I read through it and couldn't find why this would fail from the manifest side.

**Comment by cjcolvar** [comment]
@Dananji The auth service that we're using is a proposed but not yet adopted form of the auth spec.  It could be that the new version of UV doesn't support it yet.  Here is the github issue and comment that defines the proposal: https://github.com/IIIF/api/issues/1290#issuecomment-414707643.  I'm happy to answer questions!  This might be more confusing than the flow chart but here is the cypress test I wrote for testing the auth flow (but haven't finished committing to develop): https://github.com/avalonmediasystem/avalon/blob/aef629c6ac21ccdd6bbcbd727a6f93a633973007/cypress/integration/iiif_auth_spec.js

**Comment by Dananji** [comment]
Reading through the GitHub issue and comments explains a lot. It has a lot of things I was trying to say in my comment (which I didn't understand most of it at the time). Thank you for sharing this :+1: 

So from UV perspective, http://universalviewer.io/examples was written for the previous IIIF spec, which supported auth services and the new one does not because now IIIF 3.0 spec registers only image services in their service registry?

**Comment by cjcolvar** [comment]
I'm not sure.  I don't think the versions of UV are IIIF Presentation spec version dependent.  I think they support whatever versions of the spec (and potentially developmental versions of the spec as well) the version of manifesto they were built with support.

**Comment by Dananji** [comment]
1. The error happening with regards to auth services failing, Chris found that the issue might be with the changes in the way `manifold` handles the responses in the [version used in UV previously](https://github.com/IIIF-Commons/manifold/blob/v1.2.36/src/ExternalResource.ts#L283-L293) to the [latest one in master](https://github.com/IIIF-Commons/manifold/blob/master/src/ExternalResource.ts#L446-L457). Here `JSON.parse(xhr.responseText)` fails when responseText is empty. 
Action item: make a PR to manifold to handle this gracefully

2. In the new [UV app](https://uv.netlify.app/), the auth services worked when the service block in manifest was changed from the following;
```
{
  "@id": "https://spruce.dlib.indiana.edu/iiif_auth_token/c821gj948",
  "@type": "AuthTokenService1",
  "profile": "http://iiif.io/api/auth/1/token"
}
```
to this;
```
{
  "@id": "https://spruce.dlib.indiana.edu/master_files/c821gj948/auto.m3u8",
  "@type": "AuthProbeService1",
  "profile": "http://iiif.io/api/auth/1/probe"
}
```
We don't think this is something that needs to be reported to UV, but is worth making a note of it for the time being.

3. The issue of mediaelement.js being halted trying to load the stream media by not firing the `loadedmetadata` event, Chris mentioned this is an issue with HLS in UV that keeps happening for a while now.

**Comment by cjcolvar** [comment]
Another issue that we found yesterday was that in the latest UV "Sound" canvases were trying to be matched with video "format"s and failing on "audio/mp4" but successfully loads with "video/mp4".

**Comment by joncameron** [comment]
- Make a PR for Manifold (get rid of error)
