### ISSUE TITLE
Roadmap Document

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4238]
### Description
Creating and sharing a new roadmap document.

### Done Looks Like
- Roadmap document is created in a shared space and shared with the team for review and comment.

**Comment by joncameron** [comment]
@joncameron

**Comment by joncameron** [comment]
https://iu.app.box.com/file/699611828135

**Comment by mcwhitaker** [comment]
@joncameron - thanks for the link. We need to discuss more this roadmap as we need to decide whether or not it makes sense to build avalon on top of hyku instead of on top of hyrax. That conversation has consequences in the roadmap, I think.

Also, do we still have to prioritize the MDPI-related items and vet that with them? There is a meeting scheduled for next week that we could use to prioritize.

**Comment by joncameron** [comment]
The Roadmap document linked in this roadmap has been reviewed so I'm going to close this. The next step will be updating the community Roadmaps Alignment Page and the public roadmap on the Avalon wiki.
