### ISSUE TITLE
Create test scenarios for SME

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#4243]

**Comment by Dananji** [comment]
Test scenario document @SumithBaddam created is [here](https://drive.google.com/file/d/1xXimWHD46ySwke9SWwAxNNT8D4h_gWU6/view?usp=sharing).

It looks good. I'd like if we can make the following changes:

1. The 2 waveform views are zoom view (on top) and overview (on bottom), which makes it more clear for anyone using this document
2. In Test Scenario_3 you have mentioned play/pause button, but there are actually 2 separate buttons for the each action in the editor (this is not that important, but making  I wanted to clarify)
3. I think you can separate the timespan creating and editing test scenarios, because they interact with different components
4. Can you add a test scenario for editing a heading (since it is different from editing a timespan, and do not interact with the waveform) ?
5. One test scenario you can add is that the 2 forms for adding new headings and timespans operate in tandem with each other (basically only one is visible at a time)
6. For me Test Scenario_7 's purpose is not clear, maybe you can keep that and change the title of it to something like Able to edit and delete each item in the structure? And these icons are different for headings and timespans. So have 2 parts for this scenario?
7. Since Test Scenario_7 doesn't specifically explains deleting, maybe you can add another scenario for deleting items? And emphasize on the fact when deleting headings the delete confirmation message gives the number of child elements that gets deleted.
