### ISSUE TITLE
Investigate Latest MediaElement and Possible Upgrade

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4259]
### Description
We should check into the latest version of MediaElement. 
- Can we migrate to this? 
- What local fixes to the older version of MediaElement we're using need to happen? (have these already been fixed upstream?)

**Comment by Dananji** [comment]
We had ugraded MediaElement.js in 2019 August to 4.2.10. And there are some minor fixes we did after that. And I think most of these local fixes can be pushed to upstream, since they are not specific to Avalon's use cases. The following list contains all the changes we did locally after the upgrade:
1. Don't hide player controls when hovering (https://github.com/avalonmediasystem/avalon/pull/2729)
2. Spacebar not working in Firefox when player is focused (https://github.com/avalonmediasystem/avalon/pull/3427)
3. Shows subsecond values (https://github.com/avalonmediasystem/avalon/pull/3508) - Avalon specific
4. Fix time rail highlight in player (https://github.com/avalonmediasystem/avalon/pull/3609) - Avalon specific
5. Time code update in media player going from 00:59 -> 01:00 (https://github.com/avalonmediasystem/avalon/pull/3639) - This seems to be fixed in upstream
6. Handle missing caption text at end of file (https://github.com/avalonmediasystem/avalon/pull/3675) - Brian has already added this to upstream
7. Embedded player wiggle in Safari (https://github.com/avalonmediasystem/avalon/pull/3832) - Avalon specific
8. Move timefloat when hovering over timerail (https://github.com/avalonmediasystem/avalon/pull/3839) - Related to embedded player
9. Media player disappearing in Edge 16 on reload (https://github.com/avalonmediasystem/avalon/pull/4022) - Maybe Avalon specific?
10. Preserve fullscreen when advancing to the next section (https://github.com/avalonmediasystem/avalon/pull/4075) - Avalon specific
11.  Add support for jump forward and backward (https://github.com/avalonmediasystem/avalon/pull/4151) - This is a ME plugin integration
12. Carry forward volume changes to the next section (https://github.com/avalonmediasystem/avalon/pull/4151) - This contains a bug fix for volume slider in ME.js

I think it's good if we can push some of these (more generic fixes - 1, 2, 12) upstream since they can be useful for others using this.
We can apply the Avalon specific changes on top of latest ME.js (4.2.16) after upgrading. It seems this is what we did with the last upgrade.

**Comment by Dananji** [comment]
ME.js support to display fragments of files in the player (custom start and end times)

**Comment by phuongdh** [comment]
@Dananji pushing them upstream would be great. Let me know if you need help with some of these.

**Comment by Dananji** [comment]
@phuongdh Do you think it would be better to make separate PRs for each fix rather than making one PR with all the 3 fixes?

**Comment by phuongdh** [comment]
I'd make separate PRs unless they're interdependent.

**Comment by Dananji** [comment]
Made 2 PRs to upstream ([fix # 1](https://github.com/mediaelement/mediaelement/pull/2813), [fix # 2](https://github.com/mediaelement/mediaelement/pull/2814)), the last bug was fixed upstream and I had missed it.
