### ISSUE TITLE
Media Player Investigation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4280]
### Description
With work on our new media player underway, other options for the underlying player are worth investigating. We'll be using this library for the foreseeable future and it'll be the basis for our fancy new player that consumes IIIF manifests, so there should be a good basis for the decision about which underlying framework to use. This could be a good swarm timebox; we could use up to 2 swarm sessions.

### Questions
- What players are out there?
  - Video.js
  - MediaElement.js
  - others?
- What is the support/community like?
- How easily extensible is it?
- Accessibility?

### Done Looks Like
- Investigation occurs on the field of currently maintained media players for the web
- A document is generated to list these findings and associated discussion

**Comment by jrochkind** [comment]
> A document is generated to list these findings and associated discussion

Is there such a document? I'd love to see it!

**Comment by Dananji** [comment]
@jrochkind I'm afraid we didn't compile a document with the findings. This was completed as a part of the `iiif-react-media-player`'s initial setup work, where we decided to go with VideoJS mainly due to the following adavantages over MediaElement.js;
- Easy to integrate via npm
- Plugins available via npm
- Ability to develop custom components using VideoJS components

Hope this is helpful, even though it's not much.
