### ISSUE TITLE
Handle errors in bulk action jobs when publishing/unpublishing items

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4363]
### Description

When publishing/unpublishing multiple items the `BulkActionJobs::UpdateStatus` doesn't handle the exceptions when an item is invalid. 
When at least one item fails the validation the whole job fails without publishing any item.

![Screenshot from 2021-01-07 15-03-47.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/31c3e885-2b8a-439b-a4bc-44e0581b7440)

But in the GUI the flash message shows that the items are being published, which is incorrect.

![Screenshot from 2021-01-07 15-04-02.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/e0246195-2dd6-4648-8100-f045fcd20e71)
### Done Looks Like

- [ ] Handle exceptions in `BulkActionJobs::UpdateStatus` and change the flash messages accordingly

#### Notes
Related to #4288

**Comment by masaball** [comment]
Apparently I did not do a good job verifying the issue was still occurring and was attempting to work on this in a different part of the code so didn't spot this before: Already fixed in a [commit from a couple years ago](https://github.com/avalonmediasystem/avalon/commit/7d5109e3feb0bff57daeba16e08d91e4e78d982e). Did a better job of testing and confirmed that the proper flash messages are displayed for the invalid items and that the valid items aren't failing.
