### ISSUE TITLE
Series - 8XX 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4384]
- Possibly 4XX as well
- Hyperlinking this value to a search for easy access to everything under a series

**Comment by jlhardes** [comment]
Initial review of my local copy of our MARC21slim2MODS3-5-avalon transform is that everything requested is included and transformed into MODS <relatedItem> somehow: 440, 490, 800, 810, 811, and 830

Need to double-check our current MARC21slim2MODS3-5-avalon to make sure that is all still in place and then look into what kind of <relatedItem>s these are in our MODS and what, if anything, we can do to show them in Avalon.

**Comment by jlhardes** [comment]
Current XSL transform in use by IU's Avalon has the same template calls for all of these MARC fields. I tried transforming an example MARC record from IUCAT: https://iucat.iu.edu/music/15266926

There is a 490 and an 810 in the MARC record and they have different information.

The transform is only including the 810 info in the MODS and that is a <relatedItem type="series"> in MODS but Avalon is not showing that information: https://media.dlib.indiana.edu/media_objects/pz50gx560

That 810 matches the Uniform series that displays for this record in IUCAT. IUCAT is also not showing the 490 in this case.

We have logic in place that says if there is a 490 and an 8xx, then more than likely only one of those will show and it will be the 8xx. This is partially due to what the catalog record indicates about the 490 so what has been entered in MARC is really telling us that the 8xx is what should be used. This is something to clarify with Michelle but that lines up with what IUCAT is showing too.

But we do get <relatedItem type="series"> in our MODS right now and we do not seem to have any way to show that in Avalon. That could use an update, I think. A new display field call "Series Title" would likely cover all of these 4xx and 8xx fields and I think they could be combined if there are multiple (if we want to show all of them instead of choosing one over another).

**Comment by jlhardes** [comment]
Emailed Michelle to ask about keeping the series logic as is (if both 490 and 8xx, use indicators to decide if 8xx is used for series info or not).

**Comment by jlhardes** [comment]
I haven't heard back from Michelle yet but since we are getting something in MODS now for 490/8xx I think this investigation can close and we can move forward to add a "Uniform series" display with this information (matching IUCAT). This would be a separate form field in the Resource Description Form. 

There might be some adjustments to the MARC to MODS transformation logic based on Michelle's thoughts but we seem to be following the MARC field rules and doing things that same way as IUCAT so I would think we'd want to keep metadata display the same across systems.

We'll still need to plan a mapping for this to RDF when we get to that work.
