### ISSUE TITLE
Fix sidekiq cron warnings 

### ISSUE THREAD

**Issue by robertochingon** [avalonmediasystem/avalon#4631]
Hi, 
  
 I´m using:
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]
Rails 7.0.2.2

My gems:
gem list --local | grep sidekiq
sidekiq (6.4.1)
sidekiq-cron (1.2.0)

gem list --local | grep redis  
google-cloud-redis (0.8.2)
redis (4.6.0)

I´m getting this:
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

(called from /Users/Rober/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:206:in `block in all'}

According to some stackoverflow post it´s fixed with sidekiq (6.4.1), but unfortunately it´s not working for me. I also added

**Comment by cjcolvar** [comment]
This issue as it appears in Avalon will be fixed in the upcoming 7.3 release, but given your description I suspect that you were intending to open this issue on `sidekiq-cron` instead of `avalon`.  From what I can tell sidekiq-cron does not have a stable release that resolves this and you may have to apply a monkey-patch like https://github.com/MaMpf-HD/mampf/pull/365/files#diff-c1fd91cb1911a0512578b99f657554526f3e1421decdb9e908712beab57e10f9.
