### ISSUE TITLE
FFmpeg Process Hangs During Waveform Generation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4709]
# Description
FFmpeg processes hang occasionally during waveform generation. This should be investigated and resolved. Currently the zombie processes need to be cleaned out by hand to let processes finish.

Timeboxed to 3.

# Done Criteria
- [x] Investigation into why this is occurring
- [x] Identify solutions to hanging processes

**Comment by masaball** [comment]
I talked to Chris this morning about the issue and the behavior is most consistently/easily triggered by pushing from Dark Avalon to MCO. To avoid using full production systems, we were able to confirm the behavior occurs between DA staging and MCO staging as well so we could do some testing there.

When Chris and I were looking, the ffmpeg process went through fine for a ~30 minute video but stalled out on a ~1.5 hour audio file. So it seems to be related to file length rather than the file size. This could potentially be triggered by the `IO.popen` buffers filling up. We could potentially try to refactor how the command is sent to FFmpeg to better flush the buffers, assuming that this is what is happening. But I can't be sure there isn't something else going on and refactoring how the command is being piped to the shell is potentially tricky.

Another solution could be to add a timeout to the FFmpeg command. Chris found that there is a [`rw_timeout`](https://github.iu.edu/AvalonIU/Avalon/issues/127) attribute for all ffmpeg processes. If we add that to the [ffmpeg command](https://github.com/avalonmediasystem/avalon/blob/941b660b2da9d9c7f1c4fbc98fd8fdc9e5fbd213/app/services/waveform_service.rb#L91) then we can force the process to terminate after a set amount of time, rather than ending them manually. What Chris has found is that all of the waveform information is getting generated, the process is just not terminating itself. As long as the timeout is sufficiently long that any file can reasonably be expected to finish processing, it should be good for our needs. I did some testing and the timeout does work as expected. We would just need to decide on an acceptable timeout value.

**Comment by elynema** [comment]
If adding ffmpeg timeout, theoretically there is a risk that the timeout could be too short. Even a 5 minute timeout was enough for everything to have processed for a 1.5 hour file. So a large value timeout is unlikely to encounter this problem.

**Comment by elynema** [comment]
@masaball Go ahead and implement the ffmpeg timeout for now, and we can discuss further if necessary when Jon C. returns.

**Comment by joncameron** [comment]
Created new issue https://github.com/avalonmediasystem/avalon/issues/5117
