### ISSUE TITLE
Add Video to Timeliner for NER output editing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4835]
# Description
An AMP goal is providing video in addition to audio when present in the media stream. This will allow AMP users to view the image when doing NER correction with the Timeliner/NER editor in AMP.

# Done Criteria
- [x] What are the code changes in Timeliner for AMP?
- [x] Would adding video be feasible in the shared code?
- [x] What would the design of the video playback be?
- [x] How could we collaborate on that?

**Comment by Dananji** [comment]
Thoughts from looking at the codes for both shared and AMP customization of the Timeliner code;
- Code changes: regardless of the code base we add video to, it could be implemented as a separate component similar to Audio component. When there are video manifests switch from the audio element to video for the playback. And then wire it up to work with the play/pause buttons that are already in the timeliner and the central state management system. 
- Feasibility of adding video to the shared code: it would be good to add this code in the shared code with a mechanism to turn on/off the display of the video component. That way if there's an ever a need to display video in Avalon's timeliner in the future it can be turned on. Also, this code could be contributed upstream to Digirati's repository.
- Design of video playback: looking at both shared timeliner and AMP's customized timeliner, I came up with the following design, so that it works in both interfaces. They don't look identical, but the idea is that the video component will be placed in this order. These are just mock-ups and feedback is welcome!
In AMP's Timeliner:
![timeliner-amp-video.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/a3cf9212-17a6-42b4-8d2b-5e8ae28be0ac)
In shared Timeliner:
![timeliner-shared-video-alt.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/b72a4bfa-bd53-42f5-9bbe-30e9c7b5ae7e)
- Collaboration: we could maybe further discuss among the teams and come up with a plan on this?

**Comment by Dananji** [comment]
For smaller screens the video may get cut off, account for that with reducing the blank space on top part of the timeliner and/or use playing in picture-in-picture mode in the video player if possible.

**Comment by mcwhitaker** [comment]
@Dananji -  I remember a conversation about making the player components available such that the layout could be flexible, i.e., such that one could place the visual elements in different locations on the screen. Is this not possible? I am asking because I think it would be ideal not to waste that space under the player controls that we see in your mock. One idea could be to place the video player above the player controls, which is common; but in here it looks like this won't be such a good idea because of the placement of the scrubber, for which we'd rather allow full width (and it would be good to have the controls near the scrubber). So for AMP we could place the video player under the player controls, thus allowing for the whole height of the right side (below the scrubber) to be used for the table of NER terms (and, if Avalon would like it, for the Structure details in the Timeliner version).

**Comment by mcwhitaker** [comment]
@Dananji - and I like the idea of using playing in picture-in-picture mode! Thank you for your work on this.

**Comment by Dananji** [comment]
> @Dananji - I remember a conversation about making the player components available such that the layout could be flexible, i.e., such that one could place the visual elements in different locations on the screen. Is this not possible? I am asking because I think it would be ideal not to waste that space under the player controls that we see in your mock.

@mcwhitaker I agree, placing the video as shown in the mock would waste the space under the controls. And layout flexibility conversation we had totally slipped my mind. Thanks for reminding me that. 
I think it's possible to achieve layout flexibility. As I have mentioned in the first point in my first comment, developing the video as a separate component will give us the ability to place it in a desired layout without having to concern ourselves with breaking the functionality, since all the implementation (e.g. communications with other components and state management) will be written inside the component. This way, we should be able to use this component in any place of the Timeliner by passing the required props and it would work as expected.
