### ISSUE TITLE
Add Video to Timeliner for NER output editing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4880]
# Description
An AMP goal is providing video in addition to audio when present in the media stream. This will allow AMP users to view the image when doing NER correction with the Timeliner/NER editor in AMP.

# Investigation Issue 
#4835

# Done Criteria
- [x] Video component and rendering in the Timeliner added to the Timeliner code

PR: https://github.com/IUBLibTech/timeliner/pull/45

**Comment by Dananji** [comment]
Test how the sizing of the video player works in different layouts and with page scrolling.

**Comment by Dananji** [comment]
Note: It was discussed and decided to not to add the picture-in-picture plugin to MediaElement.js video player at this stage, since most of the modern browsers have picture-in-picture built-in or available via extensions.
After further research, I came across the [Picture-in-picture web API](https://w3c.github.io/picture-in-picture/), which can be utilized in browsers supporting this API to display picture-in-picture window.
This works in Chrome, but not in Firefox. Firefox has picture-in-picture build into the browser, which works well. Needs to be tested in Edge and Safari browsers.

**Comment by Dananji** [comment]
There's a Timeliner functionality called `Open audio file`, which can be used to load a new manifest. This renders the timeliner from the new manifest (both media and annotations). There's a slight time difference in the video and audio players when media file gets swapped.
To reproduce this;
1. Load a manifest
2. Play media file
3. Pause the media
4. Upload a new manifest with `Open audio file` functionality in toolbar (plus icon)
5. Play media file and observe currentTime difference in the audio and video players
This seems to be something that is used in the standalone timeliner, but not in Avalon's timeliner at the moment. I have asked from AMP folks whether this is something they are using.

For this stage of implementation, this is left as it is. And need to be revisited in the future.
