### ISSUE TITLE
Checkouts Page Displays "Item Unavailable" Instead of Checkout/Return Button

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4983]
# Description
In avalon-staging, the Checkouts page for the admin user is displaying an "Item Unavailable" message for valid items instead of the Checkout/Return button. This is visible after checking the "Display all" box.

# Expected Behavior
A button renders if the item is available (i.e it is an existing item in the system).

**Comment by masaball** [comment]
I have looked this over and I think it is behavior that I had intended. Each checkout is individual, with its own specific checkout time and return time. So the behavior that was intended is that:

1. Item is not checked out -> renders `Checkout` button for all users
2. Item is checked out to the current user -> Historic checkouts of the same item show `Item Unavailable` because you cannot check out the item multiple times at once and it is a different checkout than the current one so it would be confusing to a have a return option for an already returned checkout. Current checkout renders `Return` button.
3. Item is checked out to a different user -> Historic checkouts of the same item show 'Item Unavailable' because you cannot checkout an item that someone else has already checked out. 

What behavior would we like to see for that column? Should every entry for a specific item render a `Return` button that will return the current checkout? Should this be for every user or just admins? If we are rendering the button, how should checkout/return time of historic checkouts be handled to avoid confusion with there being a `Return` option for a checkout that is past the displayed return time? 

If we aren't rendering a `Return` button on each line, what phrase should we use to indicate that an item is already checked out to the current user and what phrase for an item checked out to a different user?

**Comment by elynema** [comment]
Thanks for clarifying that this is an intentional behavior.

For:
#2 - Honestly I think it should just be blank. There's nothing for the user to do in this case. The item is already available to them. 
#3 - can we use some kind of language that is more clear, like "Checked out to another user"? That won't fit well in the space, but there's nothing else that would communicate to the user why they can't check that item out.

Alternatively, would the phrase "Checked out" cover both these cases? #2 is checked out by current user, #3 to another user. But that could be confusing as to why you don't see a Return button?

**Comment by joncameron** [comment]
I agree on #2—having it blank with no text or button in that column seems best, since there's no action to take.

For #3 let's do the same—I think it's fine to have nothing in the column. The user can always click the link to the item to go to the view page.

**Comment by elynema** [comment]
Verified on avalon-dev in Chrome and Firefox.
