### ISSUE TITLE
Avalon manifests do not show video in IIIF players 

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5020]
Avalon manifests are not showing / playing video in most other IIIF players: UV ([v3](https://uv-v3.netlify.app/), [v4](https://uv-v4.netlify.app/)), [Mirador](https://mirador-dev.netlify.app/__tests__/integration/mirador/video), [Clover](https://samvera-labs.github.io/clover-iiif/), [Aviary](http://aviary-iiif.s3-website-us-east-1.amazonaws.com/).

The metadata from the manifests seem to be showing up, but in most players the video player area is just blank / empty.

Here is one manifest we have used for testing: https://demo.avalonmediasystem.org/media_objects/pk02cb02n/manifest.json

**Comment by elynema** [comment]
Verified that we see the same behavior (video is blank / doesn't play) in Safari.

**Comment by elynema** [comment]
Mason tried removing auth completely for an open item and no changes. Going to look at code for at least one other player. Different players may use different underlying media players (mediaElement.js vs. video.js). Our manifests work with IIIF React media player, which we built, but we built according to the IIIF spec (not according to Avalon manifests).

**Comment by elynema** [comment]
Link to test Europeana player, which also focuses on AV: https://glenrobson.github.io/iiif_stuff/europeana-media-player/index.html?iiif-content=https://iiif.io/api/cookbook/recipe/0002-mvm-audio/manifest.json

**Comment by masaball** [comment]
Manifests being generated by Avalon are currently missing IDs for the Annotation and Annotation Body components. This can cause issue with some players since the manifest is not meeting the specification. 

After manually adding the missing ID fields Mirador, Aviary, and Europeana indicated that they are not able to stream HLS videos (unable to decode 'application/x-mpegURL' format media). 

UV successfully requests and receives the auto.m3u8 file but gives a JSON parsing error. It seems that the step that UV receives the m3u8 file it is expecting to receive a JSON document instead? 

Clover is supposed to be compatible with HLS streaming but even after adding in the missing ID fields I am still seeing the same behavior of the metadata loading but the video player being a static black screen. Maybe there are other missing fields or something else that is out of spec in our manifests that have been overlooked so far?

**Comment by elynema** [comment]
Once we push out the updated iiif-manifest gem to Avalon demo, we can update the AV interoperability testing spreadsheet. Then can potentially work with Mat at NW on Clover to help us determine the issues. Can open issues for UV.

**Comment by elynema** [comment]
Mason submitted a bug report to UV and they responded that it looks like a bug in our manifest. One of the authorization methods we set up is supposed to return JSON and we are not returning JSON. 

See https://github.com/UniversalViewer/universalviewer/issues/907

**Comment by masaball** [comment]
I was able to get a manifest to work in Clover this morning. Our implementation of providing multiple quality options within the IIIF manifest is not in a form that works with Clover.![Screenshot_20230207_114746.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/a507c750-3dfe-414e-a9f0-f1da92d1cc29)
Here you can see that the `Body` section has type "Choice" and then a child `items` section with 4 subsequent children containing the information for each quality option.

If we reconfigure the body so that it only contains one quality, the video works in Clover.
![Screenshot_20230207_114636.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/67915fb6-c444-4159-8b9f-36fa47fd4fec)

I am unsure what the proper/best way to approach this is. According to the [IIIF Cookbook](https://iiif.io/api/cookbook/recipe/0033-choice/), the multiple items within the `body.type == choice` construction is proper and should be handleable by client applications. Maybe it is because we are using A/V files or maybe there is something within the Choice body that is formatted wrong which is breaking things. Or maybe Clover is not setup to handle the `Choice` construction.

Note: I tried manifests with these changes in UV and they did not work. There may still be additional issues with our manifests preventing loading by UV.

**Comment by masaball** [comment]
https://github.com/samvera-labs/clover-iiif/issues/108

**Comment by elynema** [comment]
UV summary: UV is expecting a JSON response of some kind that is not part of the current auth probe spec, but might be part of v. 2 of the IIIF auth spec. However, if we remove auth from the Avalon manifest, there is no error show in UV, but there are still issues. Once #5065 is completed, should be a new round of testing with UV with a public manifest to determine remaining issues.
