### ISSUE TITLE
Avalon manifests error in UV

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5078]
# Description

Once we remove IIIF auth from public manifests, we can work again on UV issues. It appears that w/o auth, there are still issues with UV, but no obvious error. 

We should test our manifests with UV. Does UV support HLS streaming and other expectations? What do we need to change to successfully use an Avalon-generated manifest in UV? We can reach out to the UV team with questions about support in UV for these standards.

When using the VPN or a localhost proxy we can test our manifests on Avalon-dev with external players like UV. 

Timeboxed to a 2.
Depends upon #5065.

# Done Looks Like
- [x] Test public manifests without auth against UV and see what the behavior is
- [x] Create additional issues as needed with UV or Avalon

**Comment by masaball** [comment]
UV successfully requests and receives the IIIF manifest, but then fails to load the media. There is a download link in the canvas that allows you to download the m3u8 file:
![Screenshot_20230622_100414.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/31507e93-8eef-41fd-a3d2-7365e8dac552)
So the manifest is getting parsed and the item ID is being seen and associated with the canvas, but the media is not being loaded. This can be seen in the network tab as well:
![Screenshot_20230622_101520.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/c43f1ff2-099d-4bfe-9271-4e3cfe6a34ef)
The manifest is received and then no further requests are made.

There are working examples provided by UV that use the "Choice" construction so that shouldn't be the issue. It is interesting to note that UV is only providing the link to the first quality option and not generating a selector or providing links for the other quality options. Additionally, limiting the manifest to a single quality (removing "Choice") still results in the same behavior of UV only providing the download link.

There are working examples provided by UV that are HLS media so that shouldn't be the issue. 

Presentation validator found 2-3 minor issues but cleaning them up did not resolve the issues in UV.

I have put in a request to join the UV slack so I can see the conversation and there and ask about this issue.

**Comment by elynema** [comment]
UV Slack indicated this issue was too complex to troubleshoot quickly over Slack and sent some examples. Not clear from those examples what the problem is with our manifest. Trey Pendragon noted that his team had recently done some work to get HLS working again in UV. They just merged a PR that Trey thinks might be related, but Mason had cloned and test after that PR, so he's not sure it helps our issue.

Ticket submitted to UV GitHub.

**Comment by masaball** [comment]
UV ticket: https://github.com/UniversalViewer/universalviewer/issues/925
