### ISSUE TITLE
Network Errors When Saving and Closing Edit Structure

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5127]
# Description
Emily reported network errors when trying to edit structure saving it and closing it several times, and I was able to reproduce this on dev. Here are some example records where this is happening:

- https://avalon-dev.dlib.indiana.edu/media_objects/000000000/edit?step=structure
- https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213/edit?step=structure

# Screenshot
![Screenshot 2023-03-24 at 8.58.06 AM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/73bd004b-26d0-49a2-b5f3-c9e3581064fb)

**Comment by Dananji** [comment]
I tested these 2 items, and I don't see the network errors anymore. 

One thing I came across was that for a unchecked CDL item; you can go to the edit page, and when you open SME the component loads. But after sometime `Add timespan` functionality gets blocked since access to the stream media is blocked by Avalon. This blocking UI should happen immediately. I will create a ticket for this issue in SME.
