### ISSUE TITLE
Test template for bugs 

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5162]
**Description**:
 A detailed description of the problem, including the expected behavior and the actual behavior.

**Steps to Reproduce:** 
A list of steps that can be followed to reproduce the problem, including any input or configuration that is required.

**Actual Results:** 
A description of what happens when the steps are followed, including any error messages or unexpected behavior.

**Expected Results:** 
A description of what should happen when the steps are followed, including any expected output or behavior.

**Screenshots/Screen recording:**
 Screenshots that illustrate the problem, including any error messages or unexpected behavior.

**Environment identified:** 
**Operating System**: Mac OS
**Browser**: Chrome version 90.0.4430.93
**Device/Platform**: Laptop
- [ ] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release identified:**
Information about the release where the issue is happening (Can include the release number)

**Severity/Priority:** 
A rating of the severity or priority of the bug, based on its impact on the system or users.

**Bug type**
A field that indicates whether the bug is an iteration bug or a regression bug, or a defect (Bug is identified in the production environment)

**Production impact**
Details like The date and time when the bug was first observed in the production environment.
The frequency and duration of the problem.
The number of users or systems affected by the problem.
The impact of the problem on the business or customers, such as lost revenue or reduced productivity.

**Additional Notes**: 
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Tags**

**Comment by elynema** [comment]
@charumitraravi Jon C. and I agree that severity / priority don't really fit in this template, as the reporter can't necessarily judge that. It also works better as a label for filtering issues (we have a high priority label, which can be applied at Backlog Refinement or via convo in Slack). We'd also like to remove production impact from this as most often that is obvious from the description of the issue. Instead of having a bug type, we've created a text box so that the bug reporter can identify exactly what environment the bug was identified. We should also remove tags for now. Oh, and I'd like to merge Actual Results with Steps to Reproduce. I'm going to create a template in the repository with these proposed changes.

**Comment by charumitraravi** [comment]
Sure. Thanks for letting me know, Emily

**Comment by elynema** [comment]
Some changes to bug template proposed. See PR #5164
