### ISSUE TITLE
Add Descriptive Metadata to IIIF Manifests

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5170]
# Description
Avalon's IIIF manifests currently include metadata but are missing many of the supported metadata fields. These should be included in the same way that other fields are, as specified in the spec (link below). 

# IIIF spec reference
https://iiif.io/api/presentation/3.0/#metadata

# Metadata in IIIF manifest example
https://api.dc.library.northwestern.edu/api/v2/works/5f7cd4ca-0325-436c-a84f-23db179ed383?as=iiif

# Item on avalon-dev with full metadata for testing/validation
https://avalon-dev.dlib.indiana.edu/media_objects/6t053f984/manifest.json

# Done Criteria
The following fields are present in a media object's Presentation 3.0 manifest, if present in the descriptive metadata for the object:
- [x] Note (metadata key appears in manifest but value is null)
- [x] Physical Description
- [x] Terms of Use
- [x] Table of Contents
- [x] Collection
- [x] Unit
- [x] Language
- [x] Related Items
- [x] Other Identifiers

**Comment by elynema** [comment]
IIIF does not list <pre> as a safe tag to use, but these are being used on the media object page; do we need to retain these or not?

Included metadata in order on the media object page, including hyperlinks that are normally in place.

**Comment by elynema** [comment]
Use homepage element already in IIIF manifest rather than creating a new permalink metadata element.

**Comment by elynema** [comment]
QA results

@joncameron Rights Statement is in the manifest -- assume that should be there even though it was not on the list?

@cjcolvar @joncameron The other [sample implementation](https://api.dc.library.northwestern.edu/api/v2/works/5f7cd4ca-0325-436c-a84f-23db179ed383?as=iiif) cited separates out multiple entries for the same metadata field in a comma separated list rather than linking them together into a single string. Advantages to that approach could be to allow the IIIF viewer to determine if multiple entries should be displayed on new lines vs concatenated together. I tend to like that implementation; are there other factors to consider?

We also still have <pre> tags surrounding the content in Contents, Notes, and Summary. Sounds like we are going to do the work of removing those in #5182?

**Comment by elynema** [comment]
Serializing multiple entries in a field into an array according to IIIF spec has been added to #5182.
