### ISSUE TITLE
Change Fedora Handling of Sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5205]
# Description
Following from #5039, how Avalon uses Fedora can be improved to increase performance. 

We think this change will resolve issues Chris was having with upgrade to Fedora 6. Chris will fill this in with further details about what the scope is and how this can be altered. 

# Definition of Done
- [ ] drop ordered_aggregation and do a valkyrie style serialized array of ids

**Comment by cjcolvar** [comment]
The issue with a number of failing tests in the ActiveFedora/Fedora 6 branch is media objects appear to be missing the `hasPart` relationship to master files.
`<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://purl.org/dc/terms/hasPart> <http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> .`

Fedora 4:
>irb(main):006:0> puts mo.ldp_source.graph.dump(:ntriples)
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#RDFSource> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#Container> .                                  
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Container> .              
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Resource> .               
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#writable> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .              
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#hasParent> <http://134.68.26.232/scha-stg/rest/objects/avalon> .            
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/descMetadata> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/workflow> .  
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/master_files> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/list_source> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin" .                                             
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://purl.org/dc/terms/hasPart> <http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> .            
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.iana.org/assignments/relation/last> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/list_source#g67171160> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/prov#wasDerivedFrom> <http://localhost:9999/fedora3/objects/avalon:222063> .                        
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://avalonmediasystem.org/rdf/vocab/media_object#avalon_publisher> "jauhrich" .                                       
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <info:fedora/fedora-system:def/model#hasModel> "MediaObject" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://purl.org/dc/terms/identifier> "https://purl.dlib.indiana.edu/iudl/media/w42n20544w" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#createdBy> "bypassAdmin" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://avalonmediasystem.org/rdf/vocab/media_object#avalon_resource_type> "moving image" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#created> "2017-06-08T02:42:59.398Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://fedora.info/definitions/v4/repository#lastModified> "2022-03-23T12:36:55.407Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://id.loc.gov/vocabulary/identifiers/local> "avalon:222063" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://id.loc.gov/vocabulary/identifiers/local> "w42n20544w" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://avalonmediasystem.org/rdf/vocab/media_object#avalon_uploader> "jauhrich" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.w3.org/ns/auth/acl#accessControl> <http://134.68.26.232/scha-stg/rest/objects/avalon/b3/43/2e/b2/b3432eb2-4681-44ed-95ef-25f25c9dbeec> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://projecthydra.org/ns/relations#isGovernedBy> <http://134.68.26.232/scha-stg/rest/objects/avalon/00/00/0m/29/00000m29p> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#duration> "1125958" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://projecthydra.org/ns/relations#hasPermalink> "http://purl.dlib.indiana.edu/iudl/media/w42n20544w" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <http://134.68.26.232/scha-stg/rest/objects/avalon/00/00/0m/29/00000m29p> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> <http://www.iana.org/assignments/relation/first> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d/list_source#g67171160> .

Fedora 6:
>irb(main):007:0> puts mf.ldp_source.graph.dump(:ntriples)
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#RDFSource> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#Container> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Container> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Resource> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#writable> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#hasParent> <http://134.68.26.232/scha-stg/rest/objects/avalon> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849/poster> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/ns/ldp#contains> <http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849/thumbnail> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#aspectRatio> "1.3333333333333333" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.loc.gov/premis/rdf/v1#hasFormatName> "Moving image" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.w3.org/ns/prov#wasDerivedFrom> <http://localhost:9999/fedora3/objects/avalon:222064> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#width> "1440"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#fileSize> "14018998272" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locator> "/N/beryllium/avalon/Archiver_spool/avalon/avalon_222064-NY World's Fair Home Movies 1964-1965.mov" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#createdBy> "bypassAdmin" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#created> "2017-06-08T19:38:48.456Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename> "file:///N/beryllium/avalon/Archiver_spool/avalon/avalon_222064-NY World's Fair Home Movies 1964-1965.mov" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#workflowId> "175956" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#statusCode> "COMPLETED" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#operation> "Cleaning up" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue> "5f7b4c0d646c24c5810105c181e9c307" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/master_file#posterOffset> "978000" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/master_file#thumbnailOffset> "978000" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <info:fedora/fedora-system:def/model#hasModel> "MasterFile" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#dateCreated> "2016-09-19T13:25:04Z" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#percentComplete> "100.0" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <info:fedora/fedora-system:def/relations-external#isPartOf> <http://134.68.26.232/scha-stg/rest/objects/avalon/qj/72/p8/20/qj72p820d> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#percentFailed> "0" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/common#resolution> "1440x1080" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://purl.org/dc/terms/identifier> "https://purl.dlib.indiana.edu/iudl/media/346d07hr5b" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://fedora.info/definitions/v4/repository#lastModified> "2017-06-15T05:40:33.957Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#height> "1080"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://id.loc.gov/vocabulary/identifiers/local> "avalon:222064" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://id.loc.gov/vocabulary/identifiers/local> "346d07hr5b" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#workflowName> "avalon" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://projecthydra.org/ns/relations#hasPermalink> <http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://projecthydra.org/ns/relations#hasPermalink> "http://purl.dlib.indiana.edu/iudl/media/346d07hr5b" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#duration> "1125958" .
<http://134.68.26.232/scha-stg/rest/objects/avalon/jd/47/30/84/jd4730849> <http://avalonmediasystem.org/rdf/vocab/transcoding#percentSucceeded> "100.0" .

Here is some tracing I was doing to try to figure out where that relationship gets (or doesn't get) added:
>--> #0  ActiveFedora::Associations::CollectionAssociation.add_to_target(record#MasterFile, skip_callbacks#FalseClass) at /home/app/avalon/config/initializers/active_fedora_general.rb:185
    #1  block in ActiveFedora::Associations::CollectionAssociation.block in concat_records(*records#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/collection_association.rb:162
    ͱ-- #2  Array.each at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/collection_association.rb:160
    #3  ActiveFedora::Associations::CollectionAssociation.concat_records(*records#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/collection_association.rb:160
    #4  ActiveFedora::Associations::IndirectlyContainsAssociation.concat(*records#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/indirectly_contains_association.rb:10
    #5  ActiveFedora::Associations::OrdersAssociation.append_target(record#MasterFile, _skip_callbacks#FalseClass) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/orders_association.rb:55
    #6  ActiveFedora::Orders::TargetProxy.<<(obj#MasterFile) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/orders/target_proxy.rb:11
    #7  block in ActiveFedora::Orders::TargetProxy.block in concat(objs#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/orders/target_proxy.rb:17
    ͱ-- #8  Array.each at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/orders/target_proxy.rb:16
    #9  ActiveFedora::Orders::TargetProxy.concat(objs#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/orders/target_proxy.rb:16
    #10 ActiveFedora::Associations::OrdersAssociation.target_writer(nodes#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/orders_association.rb:22
    #11 block in MediaObject::GeneratedAssociationMethods.block in define_readers(nodes#Array) at /usr/local/bundle/gems/active-fedora-14.0.1/lib/active_fedora/associations/builder/orders.rb:21
    #12 MasterFile.media_object=(mo#MediaObject) at /home/app/avalon/app/models/master_file.rb:248

I *think* Fedora was magically adding the hasPart relationship into the parent media object when the ore:proxy node was saved but isn't doing that now in Feora 6.

I tried manually setting `hasPart` in `ActiveFedora::Associations::IndirectlyContainsAssociation#save_through_record`:
```
self.owner.ldp_source.graph.set_value(self.options[:has_member_relation], node.target)
change_set = ActiveFedora::ChangeSet.new(self.owner, self.owner.resource, [:master_files])
changes = { self.options[:has_member_relation] => change_set.graph.query({ subject: change_set.object.rdf_subject, predicate: self.options[:has_member_relation] }) }
ActiveFedora::SparqlInsert.new(changes).execute(self.owner.class.id_to_uri(self.owner.id))
```
But that lead to an error:
>     NoMethodError:
       undefined method `enum_statement' for [#<RDF::Statement:0x69b18(<http://fedora:8080/fcrepo/rest/test/pc/28/9j/04/pc289j04q> <info:fedora/fedora-system:def/relations-external#isPartOf> <http://fedora:8080/fcrepo/rest/test/p5/54/7r/36/p5547r367> .)>]:Array
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/rdf.rb:57:in `rdf_query'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/rdf.rb:52:in `rdf_uris'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/rdf.rb:35:in `filtered_results'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/rdf.rb:18:in `reader'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/singular_rdf.rb:9:in `reader'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/attributes.rb:49:in `[]'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/belongs_to_association.rb:68:in `stale_state'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/association.rb:59:in `stale_target?'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/singular_association.rb:10:in `reader'
     # /usr/local/bundle/bundler/gems/active_fedora-3a8ff7b0384d/lib/active_fedora/associations/builder/association.rb:95:in `media_object'
     # ./app/models/master_file.rb:249:in `media_object='

I think it is worth digging into this a little more but at some point it probably makes sense to give up and instead of trying to recreate the existing behavior drop the `ordered_aggregation` and do a valkyrie style serialized array of ids.  This would require an Avalon data migration and would be a bigger change, but could help with performance issues in general with many-sectioned items.

**Comment by joncameron** [comment]
We'll need to talk more about data migration. This can be turned into an epic since there are many tasks.
- data migration
- investigation

**Comment by elynema** [comment]
Chris was able to do Fedora 4 to Fedora 6 data migration without re-working how sections are handled. This would make the data migration path much easier for Avalon users. I believe this can be closed.
