### ISSUE TITLE
Poster Not Set for Video

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5206]
**Describe the bug**
While testing #4967, I found that the poster image was the default audio icon image, and that I couldn't set the poster image at all. This happened with the file_without_metadata.low.webm test file (https://github.com/samvera-labs/active_encode/blob/main/spec/fixtures/file_without_metadata.low.webm).

Example Item: https://avalon-dev.dlib.indiana.edu/media_objects/8s45q876k

I also created another new item with another test file, which I was able to set the poster on without a problem: https://avalon-dev.dlib.indiana.edu/media_objects/xk81jk370

**To Reproduce**
1. Create a new record and upload file_without_metadata.low.webm
2. Complete the steps and Go to the preview/show page
3. The poster is not correct
4. Setting the poster is not correct

**Expected behavior**
Poster image was from the video, and that setting the poster image showed images and not the broken image symbol.

**Screenshots/Screen Recording**
<img width="832" alt="Screenshot 2023-05-18 at 5 14 10 PM" src="https://github.com/avalonmediasystem/avalon/assets/1406618/71bc077a-bd8b-4773-910c-981f9e553e68">

<img width="895" alt="Screenshot 2023-05-18 at 5 14 41 PM" src="https://github.com/avalonmediasystem/avalon/assets/1406618/b43ac9d5-0f5c-4f89-b1c1-98f9a4df410f">

**Environment (please complete the following information):**
 - Firefox 113 on macOS 13.3.1
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Comment by masaball** [comment]
This was caused by Avalon trying to set the MasterFile duration from metadata taken from the original file, rather than from the ActiveEncode generated input metadata that properly processes a file missing metadata.

To fix this, we added a step to the MasterFile model #update_progress_on_success! method that sets the duration from the metadata in `encode.input`. Then a post transcode hook runs that sets the poster offset and updates the poster and thumbnail. This covers the case for manual uploads.

If a user tries to include a file missing metadata in a batch entry and sets poster offset in the spreadsheet, that file will fail. There is a validation on save that checks that the poster/thumbnail offset is between 0 and the Duration. With the current logic flow for the batch entry, that save and validation happens before the duration can be set from the encode.input. Rather than expand the scope of this ticket or create a new ticket, Chris and I discussed it and decided that a batch entry containing file(s) missing metadata with poster offset greater than 0 explicitly set is enough of an edge case to not worry about for the time being.
