### ISSUE TITLE
[BUG] Adding user to Editor staff role adds user to Manager instead

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5241]
**Describe the bug**
When an Admin level user tries to add another user to the Editor staff role, that user is added to the Manager role instead. I have not tested if the behavior also occurs when a non-Admin user is doing the addition.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to the Manage Content page for a collection
2. Scroll down to the `Assign Staff Roles` section
3. Fill in a username for the `Editor` Role
4. Click the `Add` button
5. Wait for the page to reload
6. Scroll down to the `Assign Staff Roles` section
7. The username added appears under the `Manager` role, not `Editor`

**Expected behavior**
Users in the Managers group can be added to any `Staff Role` successfully

**Environment (please complete the following information):**
 - laptop
 - OS: Ubuntu 22.04
 - Firefox 114.0.1
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

# Done Looks Like
- [ ]  Add new properties to admin collections for each role
- [ ]  Mirror that information into inherited_edit users
- [ ]  Changes to ability class and elsewhere as needed
- [ ]  Data Migration

**Comment by cjcolvar** [comment]
I'm assuming the issue here is not who does the adding but who is added.  Currently, both managers and editors of a collection are added to the `inherited_edit_users` with the distinction between the two being if they belong to the `manager` or `administrator` group or not. (See https://github.com/avalonmediasystem/avalon/blob/d37bc1703085eef26affe53d9f23695148666179/app/models/admin/collection.rb#L89-L91)  This is confusing as pointed out above.  It also causes problems where a user cannot be a manager of one collection and an editor of another.  To solve this, we'll probably need to add new properties to admin collections for each role and mirror that information into `inheritied_edit_users`.  We'll probably also need to make changes in the ability class and possibly elsewhere.

**Comment by joncameron** [comment]
I tested a bunch of different scenarios (using Persona and not) and the behavior was as expected.
