### ISSUE TITLE
Navigation Keyboard Shortcuts Not Working

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5360]
# Description
On avalon-dev the left/right arrow keys do not increment the playhead as expected in Ramp. On the Ramp demo site this works as expected, with left/right seeking, spacebar play/pausing etc.

# Done Looks Like
- [x] When the page has focus, keyboard events (left/right, up/down, spacebar) should be directed to the media player so that standard keyboard shortcuts work as intended

**Comment by joncameron** [comment]
MediaElement code had focus checks to make sure key events were bound to the right place; we may need to add this code.

**Comment by masaball** [comment]
@Dananji and I discussed this and determined that it would be best to make the fix on the Ramp side. The problem as it stands seems to be an issue with the asset pipeline, where Ramp is detecting the plugin we are using for hotkey support (because Ramp is not throwing any errors) but the plugin is not being properly loaded/initialized with the player. Attempts to manually initialize the plugin on Avalon's side were unsuccessful.

The most recent versions of VideoJs have [builtin hotkey support](https://videojs.com/guides/options/#useractionshotkeys), so we are going to try removing the videojs-hotkeys plugin and just use the built in functionality. This will require us to, for the time being, manually program all of the hotkeys we want because the builtin hotkeys do not have seek or volume control options and adding custom options disables the defaults. But the pattern for adding a specific hotkey is pretty simple, so implementation/upkeep should not be an issue.

**Comment by elynema** [comment]
PR in Ramp for new hotkey build that needs to be pulled into Avalon.

**Comment by elynema** [comment]
This page contains info about how the keyboard shortcuts are supposed to work: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953669/Accessibility. This bug specifically addressed the left/right and up/down arrow keys and spacebar to stop and start playback.

**Comment by elynema** [comment]
When a page loads, the media player seems to have focus and the media player shortcuts (up/down, left/right, space bar) are working. However, it does not seem to be possible to use TAB and SHIFT+ TAB to move through the interactive elements of the page. I will create a new issue for that.
