### ISSUE TITLE
Add ending time point to canvas references 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5370]
# Description
Enable Ramp to display durations for structure segments. With end time points it will be easier for Ramp to calculate the duration and present it in the UI to users along with the rendering of the structure.

Streaminfo has a duration param, which can be added to the end of the media fragments that are currently being produced. In general, we want to have a begin/end if possible, even when begin or end is missing but can be inferred.

# Done Looks Like
- [x] End times are added to canvas references in the structure section of a IIIF manifest
- [x] Playlist items are checked to make sure that these are consistent

**Comment by joncameron** [comment]
This is good to have but not required or high priority for immediate release.

**Comment by elynema** [comment]
@masaball I *think* I'm seeing that for playlist items, the canvas reference in the structure is getting the timepoints for the entire media item, rather than the duration of the playlist item itself. The playlist canvas is getting the correct playlist item timepoints.

Here's an example playlist: https://avalon-dev.dlib.indiana.edu/playlists/5?position=2

Looks like slo-mo cat video is 42 seconds in length (see [actual media object](https://avalon-dev.dlib.indiana.edu/media_objects/1z40ks800)), but from the playlist page and the playlist manifest, it looks like the playlist item is only 8 seconds of that video.

Here's the painting annotation in the Canvas. Note that the media fragment URL seems to be right, but the duration of the annotation is incorrect.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7760c0416ad714d9b6ca7fb753069be7f128ae52/image.png)

Here's the canvas reference in the structure, where the start and end point of the canvas URL don't seem to match the fragment in the canvas.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fe5d12c6085f0268b3218591b30c8aa39d88520/image.png)

I'm not sure if you want me to create a new issue for fixing the duration problem in the Canvas painting annotation?

**Comment by masaball** [comment]
Setting the canvas duration to the length of the full item is intentional. If we set the canvas duration to the duration of the playlist item it causes problems for anything whose start time is not 0 because it truncates the canvas. So, I have a lunchroom manners playlist item that starts at 1:00 and goes until 5:31. The playlist item shows as 0:00 - 4:31 with the first minute inaccessible if the parent canvas duration is set to the playlist item duration. So we lose the final minute of the clip, because the canvas is being shortened to the listed duration but the canvas still starts at 0:00 instead of 1:00.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aab7491a5a6011f3c000004644e9c2bbc4609e86/Screenshot_20231005_144212.png)

It may be worthwhile to open a ticket so we can circle back and discuss the expected manifest serialization and how ramp should display it and behave.

As for the references in the structure, I don't think it matters to Ramp in this case but for consistency (and likely compatibility with other players) it would be good to have the structure media fragments match the corresponding fragment in the canvas ids. That should be a quick one line change, so I'll get a PR up for that shortly.

**Comment by elynema** [comment]
@masaball I believe the canvas references in the structure are being used by Dananji to display durations in the structured navigation. So those references need to match the actual duration of the playlist item, rather than the canvas.

I think I understand what you are saying about duration! We need the canvas to be the full duration, but the annotation that paints the media item is only a fragment.

**Comment by elynema** [comment]
Mason merged a PR for this, so ready to be re-tested.
