### ISSUE TITLE
[BUG] IIIF manifest for items does not include all metadata

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5387]
**Describe the bug**
The IIIF manifest for items on avalon-dev and avalon-sandbox only seems to include metadata for about 8 fields, rather than all fields.

Here is an example manifest: https://avalon-dev.dlib.indiana.edu/media_objects/765371328/manifest.json
Here is what it looks like rendered in Avalon: https://avalon-dev.dlib.indiana.edu/media_objects/765371328
However, there are many more metadata fields in this record that could be displayed: https://avalon-dev.dlib.indiana.edu/media_objects/765371328/edit?step=resource-description

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to any record and add subject, language, or physical description (or other fields that are not displaying)
2. Save and Preview record
3. Those fields do not display in the Metadata panel and are not in the IIIF manifest

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Mac OS Monterey
 - Browser: Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Comment by elynema** [comment]
iiif-manifest gem expects specific formatting for info being serialized into the metadata. Maybe something is going wrong with how the items are entered that is breaking the formatting?

**Comment by cjcolvar** [comment]
@masaball and I investigated this and found that the source of the issue is the fields not appearing in the SpeedyAF proxy.  They aren't showing up in the proxy because they aren't being indexed as stored.  These fields have index keys such as `_sim` instead of `_ssim`.  I'm surprised we didn't notice this in earlier testing of the SpeedyAF changes.  

The work for this ticket now is:
- [ ] Write a test that all fields that display on the item view page are populated in the SpeedyAF proxy and match the values in the original MediaObject
- [ ] Fix index keys for metadata fields
- [ ] Reindex and test

**Comment by masaball** [comment]
There is a secondary issue that I encountered when trying to make these changes. Certain values are stored in the solr document with a different name than is represented in the Media Object model, e.x. `media_object.abstract == solr_doc['summary_ssi']`. When the values get added to the proxy from solr, they use the keys from solr. So even with the value stored we can't access it via the Media Object methods.

There are a few options that I see:
1. Change the solr_doc names to match the media object methods. I am unsure why the names are different though I would guess it has to do with the MODS document? This would require auditing and refactoring everything that uses the solr doc names. It may also not actually be an option if the solr doc has to match the MODS metadata fields.
2. Change SpeedyAF proxy method calls to use the solr doc names. This is probably the least desirable method. The proxy is supposed to be a stand in of the media object and so should be able to call the same methods as you would use on the Media Object itself.
3. Manually associate the appropriate names with their values e.x. `@attrs[:abstract] = solr_document["summary_ssi"]`. This would result in duplicate information in the proxy because the loop through the solr doc would already have added the value under the solr doc name. We could potentially loop through the proxy and remove the duplicate values with the wrong key.
4. Catch the wrong names in the initial loop and replace them with the correct ones e.x. `attr_name = "abstract" if attr_name == "summary_ssi"`. If we can't change how the values are being stored in the solr doc, this is possibly the most desirable solution because it avoids duplication without an extra removal step. However, implementation may be more difficult/finicky than the manual approach.

**Comment by elynema** [comment]
To test in QA: Mason has made some changes to how fields that are paired are represented in the Solr index (ex: note type and note). We should test adding multiple values for these paired, multi-valued fields to try to ensure that the right type and text value remain in sync in the Solr index and for display on the media object page.

**Comment by elynema** [comment]
QA:

- test all facets to make sure they are working properly
- test adding multiple values for fields with type and text (ex: note)

**Comment by elynema** [comment]
This will require a re-index to get changes into the index. Let's hold off on that until Nov. 15 or later so we're not doing right before user testing.

**Comment by charumitraravi** [comment]
Verified the details section and the manifest for all the fields, and I tried adding and modifying multiple types and values. I could'nt find the "permalink" field in either the manifest or the details. Is this expected?

**Comment by elynema** [comment]
@charumitraravi The permalink is leveraged under "Share this resource," so it's not displayed in the Details tab. When these fields are filled out on avalon-dev, they are indeed showed under "Share this resource." That was a great catch!
