### ISSUE TITLE
[BUG] IIIF manifest is missing a canvas

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5400]
**Describe the bug**
IIIF manifest on avalon-dev seems to be missing a canvas representing a section. On the Manage Files page when editing the media object, 5 sections are listed. In the IIIF, there are only 4 canvases.

Record: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

**Expected behavior**
The number of canvases should match the number of sections.

**Screenshots/Screen Recording**
4 canvases display:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55e6691ab86c1a7f5e7d5812619e4222b293cf85/image.png)

5 sections on records:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e67d1aa7adbb8c5c22bbc004ccc66bbbd1350a3e/image.png)

**Environment (please complete the following information):**
 - Device / platform [e.g. laptop, iphone pro 12]
 - OS: Mac OS Monterey
 - Browser: Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Additional notes**
Could this be related to the fact that two of the sections have the same filename? Could that cause a problem in iiif-manifest?

**Comment by elynema** [comment]
Not only is it missing a canvas, the canvases themselves seem to be wrong. Could there be some kind of drift in section IDs vs. ordered masterfile IDs? If there is drift, that would probably have to be fixed manually.

**Comment by cjcolvar** [comment]
@masaball and I investigated and it appears that the 3rd section ("Cat In Slow Mo - 43s 1280x720 24fps.mov") is missing derviatives.  There is code in avalon's IIIF manifest generation which filters out sections without derivatives (https://github.com/avalonmediasystem/avalon/blob/d37bc1703085eef26affe53d9f23695148666179/app/models/iiif_manifest_presenter.rb#L23C1-L26).  The other oddity with repeated structure was a red herring...the two sections actually had the same structure.

Given the work done on playlist items that have been deleted or are restricted using `placeholderCanvas`, we're wondering if something similar should be done here instead of skipping the file entirely in the manifest.
@elynema @joncameron Thoughts?

**Comment by elynema** [comment]
On the manifest side, implement a placeholderCanvas like we do for restricted items on the playlist. Text: "This item is unable to be played due to missing streaming derivatives. Please contact support to report this error."

**Comment by elynema** [comment]
Currently only looking for text in placeholderCanvas when it is a playlist; need to change Ramp to look for any placeholderCanvas with empty canvas (empty list of item?).
