### ISSUE TITLE
[BUG]  Zooming in breaks the UI of the media object page in mobile devices

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5410]
**Describe the bug**
In a mobile browser, The zoom text option  is not working as expected. The page text is not getting enlarged, and the player icons move out of visibility.

**To Reproduce**
1.Open an item in a mobile web browser. The item should contain a media file
2.From the browser settings, choose the zoom option (or "Zoom text" option) and start zooming in. 

**Expected behavior**
The text should be zoomed in, and the player icons and controls should be accessible

**Screenshots/Screen Recording**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b174fcee5af078888750b55e928d73a4b476da92/RecordIt-1696602207.mp4)

**Environment (please complete the following information):**
 - Device / platform - Mobile
 - OS: iOS,Android (need to verify)
 - Browser - Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Additional notes**
This scenario  is working fine in the staging environment

**Comment by joncameron** [comment]
Most of the elements other than the large play button is on video.js and the way it handles zoom.

**Comment by elynema** [comment]
Pinch and zoom seems to be behaving ok, text zoom is more of a problem. We assume that on mobile devices, users will be more likely to be using pinch and zoom.

Need to test pinch and zoom on iOS mobile device.

**Comment by Dananji** [comment]
I followed the same steps on the main site of VideoJS to zoom in the page, and observed the same behavior there;
<img width="399" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9d86b5468bf4f558629e9e68a2d29692d652184/bs_realios_Mobile_iPhone%2015%20Pro-17.0%281%29.jpg" alt="bs_realios_Mobile_iPhone 15 Pro-17.0(1).jpg" />


And also, I tested the existing player with MediaElement.js in MCO, it zooms in the player and shows all the icons as below;

<img width="399" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8b7e290043829a23f36b6209019947828446e29/bs_realios_Mobile_iPhone%2015%20Pro-17.0.jpg" alt="bs_realios_Mobile_iPhone 15 Pro-17.0.jpg" />

Maybe we could list this as a known issue for the time being until it is fixed in VideoJS?

**Comment by joncameron** [comment]
+1 to marking it as a known issue since it's coming from Video.js.

**Comment by elynema** [comment]
Text zoom seemed to work ok in Chrome on Android. Need to test a bit more to see what is happening.

**Comment by elynema** [comment]
Added a note to Known Issues page: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954635/Known+Issues
