### ISSUE TITLE
Tab Order for Avalon

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5484]
# Description
Specifying the desired tab order through the Avalon interface for an item page.
See #5440. 

If tab order begins with skip to main content link, then the media player will not be immediately the focused element and the hotkeys for the media player will not work. Ideally, we would listen for the hotkeys if there are no active elements on the page so they will work even if the media player is not focused.

# Tab Order
- Skip to main content
- Primary Nav Links (Browse, Collections, Playlist)
- Admin Buttons (on Item page)
- Player
- User Action Buttons
- StructuredNav
- TabbedNav

# Notes
Different behavior seen in Firefox and Chrome, so this may also need to be investigated.

# Done Looks Like
- [ ] Tab order for each page in Avalon respects the order outlined above
- [ ] Tested in Firefox and Chrome and Safari

**Comment by elynema** [comment]
In Safari, when I hit tab at the start of the page, I do not get taken to the skip to main content link. It takes me to the search box, then the Manage option at the end of the menu, then Push to Core Staging / Create Thumbnail, then the player. It skips the main menu and edit/unpublish buttons. After the player, it hits only the first section, but does not descend into the structured navigation, and then skips the tabs.

On Chrome, I notice that the media player hotkeys stop working when we hit the tabs with Details / Transcript / Files. Instead, the arrow keys navigate through the tabs, rather than activating the forward / back in the media player. @joncameron Not sure if that is the desired interaction?

**Comment by masaball** [comment]
@elynema I just tested the 5 or 6 most recent desktop safari versions on browserstack and was unable to replicate the behavior you were seeing. Tabbing worked as expected on Avalon-Dev when unauthenticated and when logged in. Not sure what was going on when you were testing, but everything looks good to me.

**Comment by elynema** [comment]
Tabbing for all menu items (not just textboxes and ordered lists) has to be turned on in Safari preferences. See this article: https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html. Looks like we also ran into this with Firefox earlier.

If this setting is not turned on in Safari, then Option + Tab can be used to tab as expected. Since this seems like something that users familiar with accessibility would be aware of, I imagine we can close this issue.
