### ISSUE TITLE
Timeline Listing Search Not Working as Expected

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5586]
# Description
Timeline searching using the search field on the Timelines page isn't returning results as expected. It seems to be very strict in the matching conditions, resulting in a poor user experience since users will not expect that the default will be exact string matching with case sensitivity.

# Examples
Searching `george` doesn't return `George Walker, Piano Sonata No. 1, 3rd movement`
`op 35` doesn't return `Cecile Chaminade, Op. 35 No. 1: Scherzo`
`Op 35` doesn't return `Cecile Chaminade, Op. 35 No. 1: Scherzo`

# Done Looks Like
- [x] Searching on the Timelines page is not case sensitive
- [x] Break query on space in the input, so SQL query searching returns multiple values
- [x] Other changes for fuzzier matching as available (such as ignoring punctuation, word order) investigated
- [ ] More complicated changes can be broken into a new ticket

**Comment by joncameron** [comment]
Avalon is being sent a DB query and returning the result to DataTables, so this is ultimately a SQL query underneath.

**Comment by joncameron** [comment]
Avalon is being sent a DB query and returning the result to DataTables, so this is ultimately a SQL query underneath.

**Comment by masaball** [comment]
We can split on spaces in the input with no trouble and construct queries that do not rely on word order. However, generating a truly fuzzy query is difficult. This first query splits on spaces and then searches  for each term in the resulting array. This returns too many results though, as a search term like "using a lot of words" would return any entry with a Description containing the letter "a". So that search would return a timeline with description "Meaningful times" because meaningful has an 'a' in it. This feels unclear because a user is not going to know why that timeline is being returned from that search. The standard SQL wildcards are `%` and `_`, representing '0 or more of any character' and 'exactly one of any character', respectively. Certain SQL brands have more options but we are limited to just those two wildcards so cannot make a more granular match case.

`scope :desc_like, ->(desc_filter) { where("LOWER(description) LIKE ANY(array[?])", desc_filter.split.map { |df| "%#{df.downcase}%" }) }`

This second query uses a Regex search. It is built to look for the search term within word boundaries which is too strict a search structure. With just the boundary checks a search for "Test" would not return "testing" and "te" would return neither. We could add the `.*` wildcard within the boundary checks, but then we run into the same issue as the first query where it is returning too much because it is matching any string containing a letter. Or we could remove the boundary checks but that also results in too much being returned. There is probably a way to setup a Regex search to return how we want but it would be very complicated and difficult to read/maintain.

`scope :desc_like, ->(desc_filter) { where("description ~* ?", desc_filter.split.map { |df| "(?<!\\w)#{df.downcase}(?!\\w)" }.join('|')) }`

I looked a bit into [SQL full text search](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html) but I don't think it is appropriate for this use case. The criteria for enabling it are very specific and different SQL varieties handle it slightly differently. Additionally, discussion online I saw indicates that it does not fuzzy match, it would just be a potentially more efficient regular search. I don't think it is worth pursuing that route any further.

**Comment by elynema** [comment]
@masaball With the first SQL query, it's not possible to to search for all the terms in the array? 

If not, I don't see any option but to table this one (except for case insensitivity)for now and consider coming back to it when we have more time.

Have you considered dropping punctuation, so we are searching on letters/numbers only?

For example, in this timeline:
`Cecile Chaminade, Op. 35 No. 1: Scherzo`

The user has to enter `Op. 35` as `Op 35` does not return any results.

**Comment by masaball** [comment]
We could possibly construct a query generator for word order where it splits the search phrase into an array and then generates a new search term for each arrangement of the array and queries each of those generated phrases, rather than querying each individual word. 

When I was initially looking at this, I did not have luck with punctuation but forgot to write it up in the ticket. As I'm thinking on it more right now, I may have an approach that I hadn't thought of when I was initially looking. We can potentially run a regex or other filter on the user's input to replace punctuation with the SQL wildcard and query with the result. If I have time this afternoon, I will test that out and see what results it gives.

**Comment by cjcolvar** [comment]
I did a quick experiment and I think this approach might satisfy the examples in this issue.
https://github.com/avalonmediasystem/avalon/pull/5627

**Comment by elynema** [comment]
@joncameron I tested this out in Safari and Chrome and it works GREAT! You ok with closing this one?

**Comment by joncameron** [comment]
Yes! This is working great.
