### ISSUE TITLE
Due Date Doesn't Appear For Checked-out CDL Item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5619]
# Description
When an item is checked out by a user under CDL, other users see a message within the media player on the view page informing them that the item is currently checked out by another user and displays the date it is due to be returned. The text says "This item is due to be returned on" and the date, but the date is no longer displaying as expected.

# Current Behavior
![Screenshot 2024-02-01 at 11 47 36 AM](https://github.com/avalonmediasystem/avalon/assets/1406618/40b890be-c417-4cfc-ad6a-ddae796258a0)

# Expected Behavior
- [ ] Date value displays as expected in the media player for checked out CDL items

**Comment by elynema** [comment]
@masaball Is it to be expected that I might see a different timestamp for return time when testing with Browserstack.

Here's what I see on an Android device:

<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1984da09df431c211ed1c98e6f3bbb4b4f0f81d7/image.png" alt="image.png" />

But on my local machine, I can see that the item is due at 5:12pm:

<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--246d0f6126897e33f2af7b5e059ab29114958164/image.png" alt="image.png" />

Is this because the date is localizing to the time zone of the device? I guess that would make this the correct behavior, right?

**Comment by elynema** [comment]
Looks good on Chrome, Safari on Mac; Safari and Chrome on iPad and iPhone, and Chrome and Firefox on Android!

**Comment by masaball** [comment]
Yes, I would expect that browserstack displays a different time. As you surmised, we use some JS to localize the time for display on the client side.
