### ISSUE TITLE
Empty playlists should display playlist description and tags

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5636]
# Description

Currently, empty playlists simply display a message that reads "This playlist is empty." They should, however, display the playlist description and tags that can be entered when creating the playlist.

Current:

<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1UxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4aa2279f05a0e6bb3a9daa4c6b2c222357da511/image.png" alt="image.png" />

Prior behavior for an empty playlist:

<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1kxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9946abf6c1a67bb6255af8a739d41c95cafccfbb/image.png" alt="image.png" />

**Comment by joncameron** [comment]
Tag, comment and description are loaded on the Avalon side. We could change Ramp behavior to display something similar to what we have with inaccessible items: empty div with the message, instead of the alert error. Right now Ramp reads this and crashes, and bubbles up the error (and doesn't show the other parts of the page). We can change this, again to match inaccessible items.

**Comment by joncameron** [comment]
See https://github.com/samvera-labs/ramp/issues/457
