### ISSUE TITLE
[BUG] Captions added to audio items cause CC gadget to show in audio player

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5681]
# Description

When a caption file is added to an audio item, the CC gadget shows up in the audio player, even though there is nowhere for captions to display. This is a regression from 7.6 in the new Ramp player.

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDF2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c31a9caee837a2318576ca4274e098d3aa1bc6ff/image.png" alt="image.png" />

# Done Looks Like
- [ ] Ramp doesn't display a CC gadget for audio only items

**Comment by joncameron** [comment]
@joncameron New issue for removing the ability to attach captions to files without video: - It makes sense not to allow users to upload captions to audio files, since they won't do anything. Users need to upload them as transcripts instead. So removing the captions upload option for audio files might actually help improve the likelihood that files are uploaded as transcripts instead.

**Comment by joncameron** [comment]
@joncameron Recreate this in the Ramp repository.

**Comment by Dananji** [comment]
This can be tested in the Ramp demo site.
