### ISSUE TITLE
Investigate storing/indexing transcript text in Solr

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5726]
# Description

Investigate best way to store transcript text in Solr to respond to our needs.

Showing "Found in" for search results requires Solr to be able to present # of hits across different sets of aggregated fields in Solr.

To provide IIIF Content Search API across a media item, we'd need to be able to indicate # of hits in transcript for each section. 

# Done Looks Like

- [x] Does transcript text need to be stored, or can it just be indexed?

# Investigate

- [x] What data in Solr does the highlighting tool need to present results?
- [x] What other tools or techniques exist for us to enable "Found in" display in search results?
- [x] Can transcripts be associated with sections in the index so IIIF Content Search API can return # of hits per transcript to show in interface? Or to enable # of hits per section in search result? What added complexity would this bring?

**Comment by cjcolvar** [comment]
Based on my experiments in solr 9.5 locally:

Does transcript text need to be stored, or can it just be indexed?
The transcript needs to be included in the solr document as a text field (`_t`) with probably better results for english with a  text_en field (`_te`).  Term hits require indexing but not storing.  Highlighting requires storing but not indexing.  Indexing and storing enables both.  I don't understand yet how term vectors (`_t*v`) effect the results or performance of these queries.

What data in Solr does the highlighting tool need to present results?
See above for indexing requirements.  For querying the following params need to be added to the query:
```
hl=true
&hl.fl=mods_tesim:cat
&hl.q=mods_tesim:cat
```
which will return the something like the following in the results at the top level like `facets`:
```
"highlighting":{
    "fb4948403":{
      "mods_tesim":["A summary of this item is that it is a single meow from a single <em>cat</em> ... a <em>cat's</em> meow.  And that's"]
    }
  },
```
There are more options available for customizing how this feature works.

What other tools or techniques exist for us to enable "Found in" display in search results?
Besides highlighting, the `termfreq` function can be used to count the number of times a term occurs in a field.  Unfortunately it appears that this only works on a single term and not a phrase.  This function can be used to augment a result doc with a new virtual field.  For example, adding the following params will count the number of times 'cat' appears in all of the values of the `mods_tesim` field.
```
fl=*,mods_tf:termfreq(mods_tesim,cat)
```
This will add the `mods_tf` virtual field to each result doc:
```
"mods_tf":4
```

Can transcripts be associated with sections in the index so IIIF Content Search API can return # of hits per transcript to show in interface? Or to enable # of hits per section in search result? What added complexity would this bring?

If we store the transcript in a multivalued text field in the solr doc for the section then we can return the number of hits in all of the transcripts of a section using the termfreq function.  Getting these counts for each section of each MediaObject with matching transcripts in the search results takes a bit more work but it is possible.  In order to do this we need to use a join query to find matching sections without having to duplicate all section transcripts in the parent MediaObject.  (It appears that the join query requires using `defType` `lucene`.)
```
q={!join to=id from=isPartOf_ssim}(has_model_ssim:MasterFile AND transcript_tesim:crockett)
&defType=lucene
```
To add in the term frequency counts (including MODS and caption counts alongside the transcript counts) add the following params (with local param `qq` to avoid repeating the search term):
```
&fl=*,transcript_tesim,master_files:[subquery],desc_tf:termfreq(mods_tesim,$qq)
&master_files.q=({!terms f=isPartOf_ssim v=$row.id} AND ({!terms f=transcript_tesim v=$qq} OR {!terms f=caption_tesim v=$qq}))
&master_files.defType=lucene
&master_files.fl=id,transcript_tf:termfreq(transcript_tesim,$qq),caption_tf:termfreq(caption_tesim,$qq)
&master_files.qq=crockett
```
This adds something like the following into each result doc:
```
      "master_files":{
        "numFound":1,
        "start":0,
        "numFoundExact":true,
        "docs":[{
          "id":"3f462540k",
          "transcript_tf":578,
          "caption_tf":0
        }]
      },
      "desc_tf":0
```

Further investigations
- How do we handle phrase queries?
- What are the performance implications of storing the full contents? full term vectors?

**Comment by cjcolvar** [comment]
While doing this investigation I found that indexing sometimes failed when trying to save the transcript in a _tesim field.
```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: Exception writing document id 3f462540k to the index; possible analysis error: Document contains at least one immense term in field="suggest" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[42, 107, 32, 94, 32, 37, 94, 45, 62, 32, 102, 32, 42, 94, 32, 37, 94, 45, 115, 32, 94, 32, 10, 10, 109, 109, 63, 32, 37, 111]...', original message: bytes can be at most 32766 in length; got 460070. Perhaps the document has an indexed string field (solr.StrField) which is too large
```

I was able to resolve this by commenting out the copy fields to "suggest".  This might also possibly reduce the size of the index if everything is reindexed without the copyFields (although it is only indexed and not stored).  Also could possibly speed up indexing time if it is skipped.
