### ISSUE TITLE
Use Ramp For Embedded Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5732]
# Description
Avalon is still using a bare Video.js instance for embed routes and not Ramp. We should update this so that the embedded player has everything that Ramp can provide, and to make sure user experience is consistent.

# Done Looks Like
- [x] Ramp MediaPlayer component used for /embed routes
- [x] Current Video.js code removed
- [x] Player API works with Ramp
- [ ] Title display works as before (needs to be added to Ramp)

**Comment by joncameron** [comment]
Refer to the previous issue for Video.js as the embedded player. Ramp instance control bar should contain all desired elements. Title is not in the list of option currently for Ramp's Video.js instance, but which is in the current Avalon embedded context.

**Comment by joncameron** [comment]
@joncameron create corresponding Ramp ticket for adding Title display support.

**Comment by masaball** [comment]
To populate the embedded Ramp player we currently need to request the full media object manifest and set the player to start from the requested section. This works fine, but we have a change in behavior where there are now previous and next buttons in the embedded player for objects with multiple sections. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9WQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4951f43c3016958b284786002442b99a817f38d8/screenRecording-27-3-2024-10-3.mp4)

We think that the behavior of being able to embed full media objects and playlists has been requested in the past. But how do we want to handle this?

- Keep the old behavior of embeds being limited to just the requested section
  - Implement a prop on the Ramp side to enable/disable previous/next buttons?
  - Create a minimal section manifest specifically for embeds so only a single item is included in the manifest, obviating the need for a prop in Ramp and reducing bandwidth needs and load times for embeds from many sectioned items?
- Keep the new behavior of supporting full Media Objects
  - Leave the implementation alone. Allow users to navigate through an embedded object with the previous and next buttons?
  - Create a minimal embed manifest for specific sections as described earlier and provide an option for users to embed either a specific section or embed an entire media object?

Are there other considerations we need to think about and are there other approaches that we could take?

Depending on what approach we choose to take we can create a follow up ticket to iterate on the work done for the initial implementation, if necessary.

**Comment by elynema** [comment]
@masaball Do you recall if this work was every finished? I'm looking at an example of embedded player, and I don't see a title displayed. I'm guessing that the corresponding Ramp issue was never created?

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14f694254edab509b0d0c52dd538d330e7d3f28d/image.png" alt="image.png" />

**Comment by joncameron** [comment]
@joncameron to create a follow-up ticket to finish the embedded player so it has parity with current embeds.

**Comment by elynema** [comment]
Need to create Ramp issue for displaying the title; and an Avalon issue for link back to the original item.

**Comment by elynema** [comment]
Definition of Done for prior implementation work (#5179)

- [ ]  Audio adjustment widget works for both audio and video
- [ ]  Includes link back to item in MCO - button in toolbar
- [ ]  For audio items, plays auto quality by default. No quality selector for audio items
- [ ]  For video items, title displays in top of player hyperlinked back to MCO item
- [ ]  Embed URLs respect media fragments (can start media at a single timepoint)
- [ ]  If time, investigate if we can add a user configuration to determine whether title displays in the embedded player for video

**Comment by elynema** [comment]
@masaball I'm using the w3schools

**Comment by elynema** [comment]
@masaball I'm using the w3schools iframe tester tool. It looks to me that audio only items are not being fully displayed, as part of the progress bar is cut off:

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0N4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9778aa8b7c3d0c66655bfbd29e6ab95296f353f/image.png" alt="image.png" />

The widgets for audio quality and playback speed are getting chopped off since they expand upward. Based on Done Looks Like from our prior implementation, the quality selector widget should not display for audio items. I think the audio widget is actually working correctly for audio only items, but it's hard to tell since I can only see part of the progress bar.

I'd like to pull this one back to In Progress.

@joncameron How do you want to handle the playback speed widget for embedded audio items? I'm thinking it could just switch on click like it works in the mobile context, rather than having a menu that expands upward.

**Comment by joncameron** [comment]
I think for the embedded player it makes sense to suppress the playback speed widget like it is in other contexts.

**Comment by elynema** [comment]
@joncameron When you say "suppress" do you mean remove the widget or change its behavior? We have this widget turned no in all other Avalon contexts at this time.

**Comment by masaball** [comment]
@joncameron @elynema FWIW, I have code working for the audio embed context for cycling through the playback rates on click/tap and CSS to hide the menu because I started experimenting with it before this discussion started. This is not a feature of our implementation in any other context that I've seen so far in my testing today. In all other contexts, the playback rate widget is on and produces a pop-up menu.

For this release, I see a few options:

1. Do not have the widget in audio embeds for this release but save the code for potential addition to the ramp codebase for next release
2. Have the rate cycle on click for audio embeds and see how it works out, potentially pull it back into main ramp for next release if everything is working
3. Figure out what contexts we need/want the cycling behavior and incorporate directly into Ramp for this release.

I feel like we are probably too late in the release cycle for #3 but I do not have a preference between the other 2 options.

**Comment by elynema** [comment]
@masaball @joncameron I could've sworn when I was testing the playback speed widget on mobile devices it didn't have a menu that opened, but I can see that is not true.

I support the second solution, but the first would also be fine if that's preferred (and faster).

**Comment by joncameron** [comment]
Went with option 1: the playback speed widget does not appear for audio embeds.

@masaball Is this one good to close now that everything is represented in #5906 and #5898?

**Comment by masaball** [comment]
@joncameron Yes, this is probably good to close. Anything that comes up in QA for this current batch of work can be documented in a new ticket.

**Comment by elynema** [comment]
@joncameron Did you QA the audio player to make sure it was displaying correctly? I don't see that in the list of things to check in #5899.

**Comment by joncameron** [comment]
It was missing from this list but I did test and have a new bug report in for some UI changes: #5908.
