### ISSUE TITLE
Investigate removing linked lists from ActiveFedora

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5749]
# Description

We may be able to remove the use of linked lists for multi-sectioned items in ActiveFedora even prior to Fedora 6 upgrade. This would likely be less complex in nature than Fedora 6 upgrade, so we might be able to scope into summer 2024 release. This seems like it could 

There are some questions that would be useful to investigate prior to determining whether to scope this issue into next release.

# Questions

- [x] What will the data migration look like for MCO and other Avalon users? How hard will this be?
- [ ] Can this improvement be made while still in Fedora 4? If so, will we have to do more additional work as part of Fedora 6 upgrade, or will we be able to retain this improvement as is?
- [ ] Can MCO / IU implement this change if it is not rolled out as part of the summer 2024 release, or is it a big enough fork in the codebase that we need to stay in sync with core board?

# Done Looks Like

 - [x] Quick pass at code / data migration on small record set to see what's involved
 - [x] Document thoughts on questions in this ticket
 - [x] Implement code changes if practical

**Comment by elynema** [comment]
@cjcolvar Can you document here the migration path for this change so I have it in writing?

**Comment by cjcolvar** [comment]
The migration from `ordered_aggregation` to a serialized JSON array of ids happens in-place.  When an item is loaded the state of `ordered_master_files` will be read and stored in-memory in `section_list`.  If the item is saved the `section_list` property will persist to fedora and subsequent times the item is loaded this property will be used instead of `ordered_master_files`.  This lazy migration will automatically migrate some items as they are edited in the course of normal work and new items will only ever use  `section_list`.  Since not all items will get edited normally, we'll need to write a background job or process which will identify items that haven't been migrated yet and save them to perform the migration.  This sweep to get all stragglers could take a considerable amount of time for MCO (my guess is days) which is why I made the migration be in-place.

When an item is migrated the new `section_list` property is added to the media object in fedora and `section_list_ssim` to its solr document.  (The presence of that field in solr can be used to find items that have been migrated or not.)  The `list_source` and `master_files` subresources will no longer be written but they will remain as a snapshot of pre-migration.  After the migration is complete then these could be cleaned up and the `ordered_aggregation` association in MediaObject could be changed to `indirectly_contains` or possibly `has_many`.

While the migration is lazy and ongoing until doing a final sweep and it would probably be nice to complete prior to a Fedora 6 upgrade, I don't think it is necessary to complete it before migrating to Fedora 6 and the code changes made should apply to Fedora 6 without changes (in fact I've pulled some changes from the Avalon Fedora 6 branch for this work).  Completing it prior could provide an opportunity to easily clean up `list_source` and `master_files` subresources and reduce the size of the Fedora 6 migration. This might also be advantageous since I've had trouble deleting some very large `list_source` objects directly from fedora.

**Comment by cjcolvar** [comment]
Nothing needs to be done as part of the 7.8 upgrade for this.  The property will automatically be added to fedora and the new field added to solr on save of the record.  I'll write up a ticket for the big migration process.

**Comment by elynema** [comment]
@charumitraravi If you could do some base level QA on this issue, that would be helpful. Here are some things to test:

- create a new item on avalon-dev. Add multiple files to the item. Make sure that the files remain in the same order on the Manage Files and Preview pages as the order that you added them.
- Find a pre-existing item on avalon-dev with multiple files. Make sure that the files are showing in the same order on the Preview page as on Manage Files
- Add a new section to an item that already has multiple sections on avalon-dev. Make sure that the new section is last on the Manage Files page and that the sections remain in the same order on the Manage Files and Preview page as they were prior to adding a new section.
- Open this older record that hasn't been touched in awhile: https://avalon-dev.dlib.indiana.edu/media_objects/kw52j8067. Edit metadata and save the record. It should be automatically migrated from the linked list to the new JSON array. Make sure that the sections are in the same order before and after you save the record.

**Comment by charumitraravi** [comment]
I am getting an error in the manage files page in this item: https://avalon-dev.dlib.indiana.edu/media_objects/3n203z084/edit?step=file-upload
<img width="981" alt="Screenshot 2024-06-27 at 10 31 05 PM" src="https://github.com/avalonmediasystem/avalon/assets/52535309/f6ccaad5-403a-445d-9885-33bfd812dea6">
Rest of the usecases are working as expected.

**Comment by elynema** [comment]
@masaball Does this look the same as the error being resolved in #5833? If so, we can close this ticket!

**Comment by masaball** [comment]
Yes, that looks to be the same error as #5883.
