### ISSUE TITLE
Slow Responses for Media Object Edit Pages

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5774]
# Description
Going through the edit steps for a media object can feel very slow, particularly when creating new items via the web interface, which is the common way to interact with item creation and editing for users. The requirement that each page is a step that must be navigated in a progression adds to this, especially since each page takes multiple seconds to return. This has been a common frustration for users adding new content.

Below are times reported by the network monitor in browser devtools in Firefox (avalon-dev) and Chrome (mco-staging) as a new item is created and "Save and continue" is selected to progress through the edit steps. Slower response times are expected on the development server, but the numbers from mco-staging show that this is across the board, and users in our production system wait for 17s+ for pages while creating a single item. Ideally this would be 1.5s or less for each page.

## avalon-dev
Create new item (Manage Files): 7.84s
Resource Description: 3.92s
Structure: 10.78s
Access Control: 6.08s
Item Page: 1.92s

## mco-staging
Create new item (Manage Files): 4.72s
Resource Description: 3.01s
Structure: 3.69s
Access Control: 4s
Item Page: 1.79s

# Questions
- Is this just because of costly Fedora calls?
- Will Solr tuning help?
- Will other ongoing work (rethinking linked lists etc.) help with this, or are there other bottlenecks?

# Done Looks Like
- [ ] Investigation/profiling of requests during processing and rendering of these pages

**Comment by elynema** [comment]
As of 6/11/24, avalon-dev timings seems somewhat better than this. Probably need to re-test this after 7.8 deployment to MCO?

**Comment by joncameron** [comment]
@joncameron will generate some new numbers and compare with expectations from previous. Should this be a priority in terms of performance improvements?

**Comment by masaball** [comment]
I'm not sure I used the exact same methodology as @joncameron, but starting from hitting "Create Item" on the manage collections page I got these timings on the network tab testing today:

## mco-staging (2 runs, Chrome):
- create new item (manage files): 7s for both
- Resource description: 15s & 9s
- Structure: 5.5s & 11s
- Access control: 9.5s & 5s
- Item page: 6s & 8s

## mco-stagine (1 run, firefox):
- create new item (manage files): 6.63 s
- Resource description: 4s
- Structure: 5.5s
- Access Control: 5.4s
- Item Page: 7s

## avalon-dev (2 runs, Firefox):
- create new item (manage files): 5.5s & 4s
- Resource description: 3s & 3.2s
- Structure: 10s & 3.29s
- Access control: 2.76s & 4.3s
- Item page: 4.5s & 4.5s (actual page load time seems closer to 2.5 seconds. I think the rest of the time in the network tab comes from Ramp finishing loading the media)

So timings are a bit all over the place for me, but at least in the ball park if not worse than they were last time benchmarking was done.

**Comment by elynema** [comment]
Work in prior releases on speeding up save focused on many-sectioned items. These tests were done when creating an item with a single section.

**Comment by elynema** [comment]
Jon and I agree that this data provides an initial benchmark for editing a single-section item, and we'd really like to improve these times. 

It would be beneficial to do a full-application benchmarking project, but I'd want to edit the linked spreadsheet as it is focused only on many-sectioned items and processes on many items at a time. But we also want to know benchmarking for single items. I would like to make that a separate project potentially for the QA student.

**Comment by elynema** [comment]
About 1/10th of save action is looking up leases. The way the edit steps are routed goes through an external library called avalon-workflow. Each edit step is its own model and has a save call. The update method in avalon-workflow also has a save. So we think every Save and Continue might be saving the media object at least twice.

**Comment by masaball** [comment]
It would be a very miniscule improvement, but we could probably speed up _ingest_steps rendering by using `collection: examples, as: example` formatting instead of a loop for rendering the ingeest steps sidebar

File upload step: 40% of load time (locally) is spent in FileUploadStep#before_step. ~75% of that time (so 30% of total load time) is spent waiting for Avalon::Dropbox#all which calls Avalon::Batch#find_open_files. Locally, this amounts to about 200 ms, but can take over a full second on MCO-staging.

Resource Descriptions step: 24% of load time is MediaObject::GeneratedAccociationMethods#collection, which comes from ActiveFedora? This seems to be a large portion of the time spent rendering the edit page, which is 32% of total load time. Could we implement caching of the resource_description partial?

Each step calls out to Solr with a HydraAccessControls query 4-5 times, and I think each of these solr requests trigger a fedora load so if we can get the request to cache or otherwise only be called once, that could potentially provide some improvement.

MediaObjectsController#build_context seems to be 8-10% of total load time on each save step. Are there any efficiency bumps we can get there?

MediaObjectsController#custom_edit is another longer action.

load_and_authorize_resource callback from CanCan is also lengthy. This is outside our codebase but are there potentially imrpovements we could make? Does it need to be a load_and_authorize callback or would a lighter one work?

During saving there is a MediaObject#to_solr call that lasts ~70ms, with ~60 ms of that being taken up by MediaObject#leases. These times are likely higher in production environments. Can we rework MediaObject#leases to not be so slow?

Avalon::Workflow::WorkflowControllerBehavior#update underlies around 80% of the save occurring. A lot of the immediate child methods/processes triggered from there are ActiveFedora. Most of our step models have at least one `media_object.save` in them, and the update method has an `if model_object.save`, so every step is saving at least twice I think. Resource description specifically saves at least 3 times for one of the code paths.

Resource description step model ln 20-32: update_attributes saves the model so we don't need to explicitly save media_object after the if...else block. Move media_object.save into the populate from catalog code flow.

 Access control step model ln 26: Why do we need to do a User.where look up here? It's not a time sink but seems odd.
- ln 35-126 feel like they could be refactored to be more efficient. I'm not sure currently how much time the operations take, but I feel like this code could be improved.

Can we in general reduce allocations? most of the steps, both saving the item and rendering the next step, are spending around 5-10% of their processing time doing garbage collection.

**Comment by masaball** [comment]
Issues for further investigation and remediation:

- #6069
- #6070
- #6071
- #6072

**Comment by elynema** [comment]
Closing this issue as new issues are created.
