### ISSUE TITLE
Update Batch Manifest Example Package

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5862]
## Description
The current archive for testing batch ingest with Avalon is hosted on Drupal via avalonmediasystem.org. This should be moved to a more manageable location like the Avalon Google Drive, and updated to include transcript column fields in the template and example fixtures. 

# Done Looks Like
- [x] Update batch testing archive package with new column fields in template
  - [x] Caption, Caption Label, Caption Language
- [x] Move archive to Google Drive and set to public permissions, download only
- [ ] Update links to batch manifest example package on Avalon sites and wikis to to the Drive link

**Comment by joncameron** [comment]
Things that may come in (or already be implemented an need documentation): "Caption Mark As Transcript", "Transcript Language".

**Comment by masaball** [comment]
I can confirm that Transcript language does not work currently.

We need to add `:transcript_language` to the array of fields [here](https://github.com/avalonmediasystem/avalon/blob/b37b9816865fdca02bca81e0044aa5e43408107f/lib/avalon/batch/manifest.rb#L24) and then will probably want to update tests in spec/lib/avalon/batch/entry_spec.rb to reflect the new field.

Adding a 'Treat as Transcript' field will be a little more effort but should not be too bad since the pattern to use already exists with 'Machine Generated'.

With needing to update automated tests and manual testing being a little lengthy for batch uploads, a ticket to add both fields would probably be 2 points.

**Comment by cjcolvar** [comment]
Extracted example batch manifest and put it in google sheets for easier editing: https://docs.google.com/spreadsheets/d/1_glq1X1MjrQXu9S0paJAflUtBPpYKcrf2XQqiSlGot0/edit?usp=sharing
I added a caption file, caption label, caption language, and marked it as treat as transcript.

Created new example batch ingest package and made it world viewable by link: https://drive.google.com/file/d/15cRB8NmqtCh8k_vm3Df3TdI1wRhIK_a2/view?usp=sharing

@joncameron Can you test that the batch is working as expected and then update the links to it?

**Comment by joncameron** [comment]
I updated the new archive and manifest that Chris created with a few tweaks. It should successfully ingest now. The filename is DemoBatch-Avalon7.8.tar.gz in https://drive.google.com/drive/folders/1Zqz5cF3_BQWeOgulPdTdjP1OQff3MFPa.

Updated https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953586/Batch+Ingest+Package+Format with Google Drive link.
