### ISSUE TITLE
[BUG] ATOM feed requests are failing

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5967]
**Describe the bug**
I was looking at the logs on mco-staging and it looks like there is a bug with how ATOM requests interact with the transcript search. The ATOM feed is directly querying for `other_identifier_sim:query`, which goes through the search builder and becomes a query for `transcript_tsim:other_identifier_sim:query`  which solr can't parse. We had a similar issue with the Selected Items page which was fixed by skipping transcript search in the Bookmark context.  

**Expected behavior**
ATOM does not error when making requests

**Environment (please complete the following information):**
- [ ] avalon-dev
- [ ] avalon-staging
- [x] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.8

**Comment by masaball** [comment]
@elynema @joncameron 
I ultimately tracked down that it was specifically the curly braces that were causing the search to fail and that they cause the failure in the front end search as well. Even though we are escaping special characters before sending the query to solr, they were still causing issue. I could not tell if it was an issue with the `RSolr.solr_escape` method or if it is an issue with solr not respecting the escaping. Or some other intermediate processing screwing things up. For now, I have a PR to skip the transcript search if a curly brace is in the query.

It is possible there are other edge cases with searches involving special characters, but it is probably not worth the effort to try to track them all down and resolve them right now.

**Comment by elynema** [comment]
This would impact any Solr search. If we search the main site with a curly brace, we'll get an error from the "Found in" part of the main site search. Looks like there is also a console error if you do a search on the Transcript tab, but no error displays to the user. We can't exclude the curly braces from searches since they are needed in the search that RMD is submitting to Atom.

In the first pass at a solution, just not doing transcript search if there are curly braces in the search term.

We could merge this as a first pass fix for 7.8, and then create another issue to look at for next release to explore other alternatives.
