### ISSUE TITLE
Error in Waveform Jobs

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#6014]
# Description
https://app.honeybadger.io/projects/54117/faults/83002800

Waveforms jobs are throwing errors, and investigation needs to be done as to why this is the case and if it can be fixed.

# Done Looks Like
- [ ] Investigate waveform jobs errors to find the source of the issue

**Comment by joncameron** [comment]
Encountered a number of errors of different kinds. Has the issue of video without audio data causing issues with this been resolved?

**Comment by cjcolvar** [comment]
I checked production sidekiq errors from the past 5 months and failed waveform jobs fell into four groups:
1) Streaming file missing - 255
2) Ldp::Gone - 45
3) Bad test items (batch and API) - 3
4) Invalid URI - invalid scheme format - 1

Given this I think the problem seems to be an IU-specific concern except for the last case.  This one didn't actually fail generating a waveform but rather in `post_processing_move_filename` probably due to special characters in the original filename(`6. Alexander and Ruth at Hall of Fame 6:12:39.aiff`).

**Comment by joncameron** [comment]
See #6101 for filename issue. Otherwise, waveform jobs are successfully completing other than the instance-specific data issues mentioned by Chris above.
