### ISSUE TITLE
Test Sharepoint Sites in Browse Everything

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#6048]
# Description
Current Microsoft cloud storage support needs to be tested; do we need to take additional steps for auth on restricted drive shares, or will the default work for access needed for file transfer (will signing in through Browse Everything expose all of the desired files?).

# Done Looks Like
- [ ] Test Browse Everything with Sharepoint/OneDrive folders with restricted or group access
- [x] Reach out to SSSP/admins for further access if needed

**Comment by joncameron** [comment]
We'll QA the current proof of concept before testing sites in this ticket.

**Comment by elynema** [comment]
Need to submit a ticket to support with evidence of why we need admin access (in the form of screenshots) and what application they need to look for to approve. Since Mason registered this, we probably need to get that from him.

See details from Dananji at #5987.

**Comment by masaball** [comment]
This isn't quite the full list of sites that show up in BrowseEverything, but gives an idea of how much is there. We will probably need to figure out some way of limiting what gets returned.

<img width="634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f69515dba453089ff602544dea6a1e993c1c6513/Screenshot_20241101_100108.png" alt="Screenshot_20241101_100108.png" />
<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cc7094ded4832f4d9f58bee15dc26f276bac614/Screenshot_20241101_100137.png" alt="Screenshot_20241101_100137.png" />
<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32f32a193c10bc6d5245f75ad64c72bc9140e1c2/Screenshot_20241101_100147.png" alt="Screenshot_20241101_100147.png" />
<img width="634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lOQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac28e22d47ff60d3e8a5519b51d78d51bcc6b0a6/Screenshot_20241101_100159.png" alt="Screenshot_20241101_100159.png" />

**Comment by elynema** [comment]
Further admin access from security folks does not seem to be needed for this implementation; Mason is able to upload files from Sharepoint sites. Jon Dunn agrees that this mess is because folks don't know how to handle permissions in Sharepoint. There are definitely folders that should not be here.

Microsoft handles that by sorting the folders / sites you have most recently interacted with to the top. If we can somehow do that in the query, that would be useful.

Teams sites should either have prefix 0365- or [Sec] or [Sec-e]. We can filter to Teams sites. We can't really filter to 0365-BL-LIBR as we have non-Libraries and non-Bloomington users, but it's reasonable to have folks who want to use this feature use a Team with the proper naming convention. [Sec] and [Sec-e] are old Teams naming conventions.

Sites that begin with [BL-LIBR] are Sharepoint intranet sites and do not need to be included.

In the future, if this is popular, we could consider building some type of 'favorites' tool to allow users to star sites to appear at the top?

**Comment by joncameron** [comment]
This works really well; I've created #6111 for further refinement on the presentation of the folders, which isn't pleasant to navigate at the moment because it's currently exposing a huge list of folders which is too broad for our needs and tough to parse through.
