### ISSUE TITLE
Some Filenames Cause Errors During Processing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#6101]
# Description
Method error in `post_processing_move_filename` probably due to special characters in the filename `6. Alexander and Ruth at Hall of Fame 6:12:39.aiff`. ~~In the post_processing_move_filename method, we're using a tr function would is probably only replacing the first instance of a colon in a string, not all of the colons within. This can be changed to a gsub.~~

# Done Looks Like
- [ ] Investigate issue with filename (error: `Invalid URI - invalid scheme format`)
- [ ] Add handling to allow `post_processing_move_filename` to properly process `6. Alexander and Ruth at Hall of Fame 6:12:39.aiff`

**Comment by masaball** [comment]
Unable to replicate locally using a file with the given name, so it does not appear to be an issue with the `post_processing_move_filename` method itself. Looking at the previous ticket, the specific error was `Invalid URI - invalid scheme format` which indicates to me that the file was being loaded from an external service, maybe google drive? I'm going to increase the estimate on this to a 2 because there's some more investigation into what the actual issue is that needs to happen.

**Comment by masaball** [comment]
File uploaded from sharepoint did not run into error so it is not an issue related to browse-everything's processing. Google drive is not currently working on Dev so will need to test from google drive when that gets fixed.

**Comment by joncameron** [comment]
Sounds good! I was also unable to replicate; closing.
