### ISSUE TITLE
update mobile styles for playlists.

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#807]
Currently playlists have several visual issues. Functionality seems fine. 
- [ ] create mobile design
- [ ] implement mobile styles from design
- [ ] black bar at top of iPhone 6

**Comment by davidschober** [comment]
per discussion putting on hold.

**Comment by mschnaars** [comment]
Playlists and screens related to playlist actions currently do not have a mobile style, meaning users need to scroll horizontally in order to see everything. Even though the content displays correctly, it doesn't look very elegant.
View All Playlists screen:
![iphone6s_playlists](https://user-images.githubusercontent.com/25825877/30177633-71916c94-93d4-11e7-91bc-c21fccae3150.PNG)
Add Item to Playlist screen:
![add_item_to_playlist](https://user-images.githubusercontent.com/25825877/30177717-b0fc2a9a-93d4-11e7-8252-9023e2ce3d8b.PNG)
![add_item_to_playlist_2](https://user-images.githubusercontent.com/25825877/30177716-b0f5c736-93d4-11e7-8539-a8f370dfec23.PNG)

There are a few screens, however, that are not displaying correctly. These issues were found using the iPhone 6.

View Playlist screen (the AutoPlay button, Copy and Edit buttons, and the Share button are not lining up):
![iphone6_view_playlist](https://user-images.githubusercontent.com/25825877/30177859-0e1dd3c2-93d5-11e7-9fe8-2d0beda9aa32.PNG)
Edit Playlist Item screen (Start Time and End Time labels are flush right instead of flush left):
![iphone6_edit_playlist_item](https://user-images.githubusercontent.com/25825877/30177940-469b770e-93d5-11e7-9eb1-501510c7b5ea.PNG)
Edit Playlist screen (labels (e.g. "Name" and "Description") and values (e.g. "iOS Test Playlist") have the same indentation; they should be visually distinct from each other):
![iphone6_edit_playlist](https://user-images.githubusercontent.com/25825877/30178045-a76a69f0-93d5-11e7-963a-e6343a119c2c.PNG)

This seems to be the extent of the visual issues on mobile devices.
