### ISSUE TITLE
Review metadata presentation post migration

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#912]
### Done Looks Like

HTML on the MediaObject and Collection views display the same data they did in Fedora 3.

- [ ] Validate the metadata on the media object
- [ ] Validate the track/master file display on the media object

**Comment by davidschober** [comment]
Maybe automate with Selenium using a spreadsheet? Possibly do a spot check automatically. Create spreadsheet using Fedora 3 Solr. 

Someone may have to hand check the tree structure.

**Comment by carrickr** [comment]
As we work on this, this seems to have less value in its current form.  Specifically we're writing what are fundamentally view tests, but rather than add them to our testing suite as something as part of CI, they would just be run once.  Chris C and I are proposing we turn this into "I want view tests in Avalon 6's CI" (something we currently don't have).  This will test the views and display of data.  Then #1309 hands validating the actual data.  Between the two issues this would leave us with a result where our data is validated, the view that displays the data is validated, and our testing suite will throw warnings whenever the view changes moving forward.

**Comment by davidschober** [comment]
related to #1309

**Comment by joncameron** [comment]
@carrickr will change this to his recommendation in the comments and update #1309.

**Comment by carrickr** [comment]
This can be resized to be smaller, but is not complete as some tests are still failing on this.

**Comment by davidschober** [comment]
Sprint review: @cjcolvar How the migration tool is setup it's mostly just copying content. We have to do the moving ourselves. There will be a lot of grunt work verifying that for each field data was moved.

**Comment by carrickr** [comment]
There isn't much for POs to review here, since there are purely CI tests for this PR, but if a PO wants a walk through let me know.

**Comment by davidschober** [comment]
Sounds good.
